// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: novitabox/v1/boxlet.proto

package novitaboxv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSandboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	TemplateId    string                 `protobuf:"bytes,2,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	ImageId       string                 `protobuf:"bytes,3,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	SnapshotId    string                 `protobuf:"bytes,4,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	RuntimeType   RuntimeType            `protobuf:"varint,5,opt,name=runtime_type,json=runtimeType,proto3,enum=novitabox.v1.RuntimeType" json:"runtime_type,omitempty"`
	RuntimeSpec   *RuntimeSpec           `protobuf:"bytes,6,opt,name=runtime_spec,json=runtimeSpec,proto3" json:"runtime_spec,omitempty"`
	RootfsSource  *RootfsSourceSpec      `protobuf:"bytes,7,opt,name=rootfs_source,json=rootfsSource,proto3" json:"rootfs_source,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,20,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Annotations   map[string]string      `protobuf:"bytes,21,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSandboxRequest) Reset() {
	*x = CreateSandboxRequest{}
	mi := &file_novitabox_v1_boxlet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSandboxRequest) ProtoMessage() {}

func (x *CreateSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_boxlet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSandboxRequest.ProtoReflect.Descriptor instead.
func (*CreateSandboxRequest) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_boxlet_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSandboxRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *CreateSandboxRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *CreateSandboxRequest) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *CreateSandboxRequest) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *CreateSandboxRequest) GetRuntimeType() RuntimeType {
	if x != nil {
		return x.RuntimeType
	}
	return RuntimeType_RUNTIME_TYPE_UNSPECIFIED
}

func (x *CreateSandboxRequest) GetRuntimeSpec() *RuntimeSpec {
	if x != nil {
		return x.RuntimeSpec
	}
	return nil
}

func (x *CreateSandboxRequest) GetRootfsSource() *RootfsSourceSpec {
	if x != nil {
		return x.RootfsSource
	}
	return nil
}

func (x *CreateSandboxRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *CreateSandboxRequest) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

type PauseSandboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseSandboxRequest) Reset() {
	*x = PauseSandboxRequest{}
	mi := &file_novitabox_v1_boxlet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseSandboxRequest) ProtoMessage() {}

func (x *PauseSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_boxlet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseSandboxRequest.ProtoReflect.Descriptor instead.
func (*PauseSandboxRequest) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_boxlet_proto_rawDescGZIP(), []int{1}
}

func (x *PauseSandboxRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

type ResumeSandboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeSandboxRequest) Reset() {
	*x = ResumeSandboxRequest{}
	mi := &file_novitabox_v1_boxlet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeSandboxRequest) ProtoMessage() {}

func (x *ResumeSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_boxlet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeSandboxRequest.ProtoReflect.Descriptor instead.
func (*ResumeSandboxRequest) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_boxlet_proto_rawDescGZIP(), []int{2}
}

func (x *ResumeSandboxRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

type KillSandboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillSandboxRequest) Reset() {
	*x = KillSandboxRequest{}
	mi := &file_novitabox_v1_boxlet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillSandboxRequest) ProtoMessage() {}

func (x *KillSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_boxlet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillSandboxRequest.ProtoReflect.Descriptor instead.
func (*KillSandboxRequest) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_boxlet_proto_rawDescGZIP(), []int{3}
}

func (x *KillSandboxRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

type StartSandboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSandboxRequest) Reset() {
	*x = StartSandboxRequest{}
	mi := &file_novitabox_v1_boxlet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSandboxRequest) ProtoMessage() {}

func (x *StartSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_boxlet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSandboxRequest.ProtoReflect.Descriptor instead.
func (*StartSandboxRequest) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_boxlet_proto_rawDescGZIP(), []int{4}
}

func (x *StartSandboxRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

type StopSandboxRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SandboxId      string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	TimeoutSeconds uint32                 `protobuf:"varint,2,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StopSandboxRequest) Reset() {
	*x = StopSandboxRequest{}
	mi := &file_novitabox_v1_boxlet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopSandboxRequest) ProtoMessage() {}

func (x *StopSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_boxlet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopSandboxRequest.ProtoReflect.Descriptor instead.
func (*StopSandboxRequest) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_boxlet_proto_rawDescGZIP(), []int{5}
}

func (x *StopSandboxRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *StopSandboxRequest) GetTimeoutSeconds() uint32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type RebootSandboxRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SandboxId      string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	TimeoutSeconds uint32                 `protobuf:"varint,2,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RebootSandboxRequest) Reset() {
	*x = RebootSandboxRequest{}
	mi := &file_novitabox_v1_boxlet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebootSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebootSandboxRequest) ProtoMessage() {}

func (x *RebootSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_boxlet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebootSandboxRequest.ProtoReflect.Descriptor instead.
func (*RebootSandboxRequest) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_boxlet_proto_rawDescGZIP(), []int{6}
}

func (x *RebootSandboxRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *RebootSandboxRequest) GetTimeoutSeconds() uint32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type GetSandboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSandboxRequest) Reset() {
	*x = GetSandboxRequest{}
	mi := &file_novitabox_v1_boxlet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSandboxRequest) ProtoMessage() {}

func (x *GetSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_boxlet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSandboxRequest.ProtoReflect.Descriptor instead.
func (*GetSandboxRequest) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_boxlet_proto_rawDescGZIP(), []int{7}
}

func (x *GetSandboxRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

type ListSandboxesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LabelSelector map[string]string      `protobuf:"bytes,1,rep,name=label_selector,json=labelSelector,proto3" json:"label_selector,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSandboxesRequest) Reset() {
	*x = ListSandboxesRequest{}
	mi := &file_novitabox_v1_boxlet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSandboxesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSandboxesRequest) ProtoMessage() {}

func (x *ListSandboxesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_boxlet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSandboxesRequest.ProtoReflect.Descriptor instead.
func (*ListSandboxesRequest) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_boxlet_proto_rawDescGZIP(), []int{8}
}

func (x *ListSandboxesRequest) GetLabelSelector() map[string]string {
	if x != nil {
		return x.LabelSelector
	}
	return nil
}

type ListSandboxesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sandboxes     []*SandboxInfo         `protobuf:"bytes,1,rep,name=sandboxes,proto3" json:"sandboxes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSandboxesResponse) Reset() {
	*x = ListSandboxesResponse{}
	mi := &file_novitabox_v1_boxlet_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSandboxesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSandboxesResponse) ProtoMessage() {}

func (x *ListSandboxesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_boxlet_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSandboxesResponse.ProtoReflect.Descriptor instead.
func (*ListSandboxesResponse) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_boxlet_proto_rawDescGZIP(), []int{9}
}

func (x *ListSandboxesResponse) GetSandboxes() []*SandboxInfo {
	if x != nil {
		return x.Sandboxes
	}
	return nil
}

type UpdateSandboxBalloonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	AmountMib     uint32                 `protobuf:"varint,2,opt,name=amount_mib,json=amountMib,proto3" json:"amount_mib,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSandboxBalloonRequest) Reset() {
	*x = UpdateSandboxBalloonRequest{}
	mi := &file_novitabox_v1_boxlet_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSandboxBalloonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSandboxBalloonRequest) ProtoMessage() {}

func (x *UpdateSandboxBalloonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_boxlet_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSandboxBalloonRequest.ProtoReflect.Descriptor instead.
func (*UpdateSandboxBalloonRequest) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_boxlet_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateSandboxBalloonRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *UpdateSandboxBalloonRequest) GetAmountMib() uint32 {
	if x != nil {
		return x.AmountMib
	}
	return 0
}

type GetSandboxBalloonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSandboxBalloonRequest) Reset() {
	*x = GetSandboxBalloonRequest{}
	mi := &file_novitabox_v1_boxlet_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSandboxBalloonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSandboxBalloonRequest) ProtoMessage() {}

func (x *GetSandboxBalloonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_boxlet_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSandboxBalloonRequest.ProtoReflect.Descriptor instead.
func (*GetSandboxBalloonRequest) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_boxlet_proto_rawDescGZIP(), []int{11}
}

func (x *GetSandboxBalloonRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

type GetSandboxBalloonStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSandboxBalloonStatsRequest) Reset() {
	*x = GetSandboxBalloonStatsRequest{}
	mi := &file_novitabox_v1_boxlet_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSandboxBalloonStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSandboxBalloonStatsRequest) ProtoMessage() {}

func (x *GetSandboxBalloonStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_boxlet_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSandboxBalloonStatsRequest.ProtoReflect.Descriptor instead.
func (*GetSandboxBalloonStatsRequest) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_boxlet_proto_rawDescGZIP(), []int{12}
}

func (x *GetSandboxBalloonStatsRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

type UpdateSandboxBalloonStatsRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	SandboxId             string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	StatsPollingIntervalS uint32                 `protobuf:"varint,2,opt,name=stats_polling_interval_s,json=statsPollingIntervalS,proto3" json:"stats_polling_interval_s,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *UpdateSandboxBalloonStatsRequest) Reset() {
	*x = UpdateSandboxBalloonStatsRequest{}
	mi := &file_novitabox_v1_boxlet_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSandboxBalloonStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSandboxBalloonStatsRequest) ProtoMessage() {}

func (x *UpdateSandboxBalloonStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_boxlet_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSandboxBalloonStatsRequest.ProtoReflect.Descriptor instead.
func (*UpdateSandboxBalloonStatsRequest) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_boxlet_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateSandboxBalloonStatsRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *UpdateSandboxBalloonStatsRequest) GetStatsPollingIntervalS() uint32 {
	if x != nil {
		return x.StatsPollingIntervalS
	}
	return 0
}

type StartSandboxBalloonHintingRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SandboxId         string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	AcknowledgeOnStop bool                   `protobuf:"varint,3,opt,name=acknowledge_on_stop,json=acknowledgeOnStop,proto3" json:"acknowledge_on_stop,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StartSandboxBalloonHintingRequest) Reset() {
	*x = StartSandboxBalloonHintingRequest{}
	mi := &file_novitabox_v1_boxlet_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSandboxBalloonHintingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSandboxBalloonHintingRequest) ProtoMessage() {}

func (x *StartSandboxBalloonHintingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_boxlet_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSandboxBalloonHintingRequest.ProtoReflect.Descriptor instead.
func (*StartSandboxBalloonHintingRequest) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_boxlet_proto_rawDescGZIP(), []int{14}
}

func (x *StartSandboxBalloonHintingRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *StartSandboxBalloonHintingRequest) GetAcknowledgeOnStop() bool {
	if x != nil {
		return x.AcknowledgeOnStop
	}
	return false
}

type StopSandboxBalloonHintingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopSandboxBalloonHintingRequest) Reset() {
	*x = StopSandboxBalloonHintingRequest{}
	mi := &file_novitabox_v1_boxlet_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopSandboxBalloonHintingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopSandboxBalloonHintingRequest) ProtoMessage() {}

func (x *StopSandboxBalloonHintingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_boxlet_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopSandboxBalloonHintingRequest.ProtoReflect.Descriptor instead.
func (*StopSandboxBalloonHintingRequest) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_boxlet_proto_rawDescGZIP(), []int{15}
}

func (x *StopSandboxBalloonHintingRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

type GetSandboxBalloonHintingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSandboxBalloonHintingRequest) Reset() {
	*x = GetSandboxBalloonHintingRequest{}
	mi := &file_novitabox_v1_boxlet_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSandboxBalloonHintingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSandboxBalloonHintingRequest) ProtoMessage() {}

func (x *GetSandboxBalloonHintingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_boxlet_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSandboxBalloonHintingRequest.ProtoReflect.Descriptor instead.
func (*GetSandboxBalloonHintingRequest) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_boxlet_proto_rawDescGZIP(), []int{16}
}

func (x *GetSandboxBalloonHintingRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

type CreateTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TemplateId    string                 `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	SandboxId     string                 `protobuf:"bytes,2,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	ImageId       string                 `protobuf:"bytes,3,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	DockerImage   string                 `protobuf:"bytes,4,opt,name=docker_image,json=dockerImage,proto3" json:"docker_image,omitempty"`
	StartCmd      string                 `protobuf:"bytes,5,opt,name=start_cmd,json=startCmd,proto3" json:"start_cmd,omitempty"`
	FromTemplate  string                 `protobuf:"bytes,6,opt,name=from_template,json=fromTemplate,proto3" json:"from_template,omitempty"`
	ReadyCmd      string                 `protobuf:"bytes,7,opt,name=ready_cmd,json=readyCmd,proto3" json:"ready_cmd,omitempty"`
	Steps         []*TemplateBuildStep   `protobuf:"bytes,8,rep,name=steps,proto3" json:"steps,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,20,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTemplateRequest) Reset() {
	*x = CreateTemplateRequest{}
	mi := &file_novitabox_v1_boxlet_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTemplateRequest) ProtoMessage() {}

func (x *CreateTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_boxlet_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTemplateRequest.ProtoReflect.Descriptor instead.
func (*CreateTemplateRequest) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_boxlet_proto_rawDescGZIP(), []int{17}
}

func (x *CreateTemplateRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *CreateTemplateRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *CreateTemplateRequest) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *CreateTemplateRequest) GetDockerImage() string {
	if x != nil {
		return x.DockerImage
	}
	return ""
}

func (x *CreateTemplateRequest) GetStartCmd() string {
	if x != nil {
		return x.StartCmd
	}
	return ""
}

func (x *CreateTemplateRequest) GetFromTemplate() string {
	if x != nil {
		return x.FromTemplate
	}
	return ""
}

func (x *CreateTemplateRequest) GetReadyCmd() string {
	if x != nil {
		return x.ReadyCmd
	}
	return ""
}

func (x *CreateTemplateRequest) GetSteps() []*TemplateBuildStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *CreateTemplateRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type TemplateBuildStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Args          []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	FilesHash     string                 `protobuf:"bytes,3,opt,name=files_hash,json=filesHash,proto3" json:"files_hash,omitempty"`
	EnvVars       map[string]string      `protobuf:"bytes,4,rep,name=env_vars,json=envVars,proto3" json:"env_vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemplateBuildStep) Reset() {
	*x = TemplateBuildStep{}
	mi := &file_novitabox_v1_boxlet_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateBuildStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateBuildStep) ProtoMessage() {}

func (x *TemplateBuildStep) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_boxlet_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateBuildStep.ProtoReflect.Descriptor instead.
func (*TemplateBuildStep) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_boxlet_proto_rawDescGZIP(), []int{18}
}

func (x *TemplateBuildStep) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TemplateBuildStep) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *TemplateBuildStep) GetFilesHash() string {
	if x != nil {
		return x.FilesHash
	}
	return ""
}

func (x *TemplateBuildStep) GetEnvVars() map[string]string {
	if x != nil {
		return x.EnvVars
	}
	return nil
}

type DeleteTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TemplateId    string                 `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTemplateRequest) Reset() {
	*x = DeleteTemplateRequest{}
	mi := &file_novitabox_v1_boxlet_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTemplateRequest) ProtoMessage() {}

func (x *DeleteTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_boxlet_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTemplateRequest.ProtoReflect.Descriptor instead.
func (*DeleteTemplateRequest) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_boxlet_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteTemplateRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

type GetTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TemplateId    string                 `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTemplateRequest) Reset() {
	*x = GetTemplateRequest{}
	mi := &file_novitabox_v1_boxlet_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTemplateRequest) ProtoMessage() {}

func (x *GetTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_boxlet_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTemplateRequest.ProtoReflect.Descriptor instead.
func (*GetTemplateRequest) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_boxlet_proto_rawDescGZIP(), []int{20}
}

func (x *GetTemplateRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

type ListTemplatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LabelSelector map[string]string      `protobuf:"bytes,1,rep,name=label_selector,json=labelSelector,proto3" json:"label_selector,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTemplatesRequest) Reset() {
	*x = ListTemplatesRequest{}
	mi := &file_novitabox_v1_boxlet_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTemplatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTemplatesRequest) ProtoMessage() {}

func (x *ListTemplatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_boxlet_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTemplatesRequest.ProtoReflect.Descriptor instead.
func (*ListTemplatesRequest) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_boxlet_proto_rawDescGZIP(), []int{21}
}

func (x *ListTemplatesRequest) GetLabelSelector() map[string]string {
	if x != nil {
		return x.LabelSelector
	}
	return nil
}

type ListTemplatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Templates     []*TemplateInfo        `protobuf:"bytes,1,rep,name=templates,proto3" json:"templates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTemplatesResponse) Reset() {
	*x = ListTemplatesResponse{}
	mi := &file_novitabox_v1_boxlet_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTemplatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTemplatesResponse) ProtoMessage() {}

func (x *ListTemplatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_boxlet_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTemplatesResponse.ProtoReflect.Descriptor instead.
func (*ListTemplatesResponse) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_boxlet_proto_rawDescGZIP(), []int{22}
}

func (x *ListTemplatesResponse) GetTemplates() []*TemplateInfo {
	if x != nil {
		return x.Templates
	}
	return nil
}

type CreateImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageId       string                 `protobuf:"bytes,1,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	TemplateId    string                 `protobuf:"bytes,2,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,20,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateImageRequest) Reset() {
	*x = CreateImageRequest{}
	mi := &file_novitabox_v1_boxlet_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateImageRequest) ProtoMessage() {}

func (x *CreateImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_boxlet_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateImageRequest.ProtoReflect.Descriptor instead.
func (*CreateImageRequest) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_boxlet_proto_rawDescGZIP(), []int{23}
}

func (x *CreateImageRequest) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *CreateImageRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *CreateImageRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type DeleteImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageId       string                 `protobuf:"bytes,1,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteImageRequest) Reset() {
	*x = DeleteImageRequest{}
	mi := &file_novitabox_v1_boxlet_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteImageRequest) ProtoMessage() {}

func (x *DeleteImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_boxlet_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteImageRequest.ProtoReflect.Descriptor instead.
func (*DeleteImageRequest) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_boxlet_proto_rawDescGZIP(), []int{24}
}

func (x *DeleteImageRequest) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

type GetImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageId       string                 `protobuf:"bytes,1,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetImageRequest) Reset() {
	*x = GetImageRequest{}
	mi := &file_novitabox_v1_boxlet_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImageRequest) ProtoMessage() {}

func (x *GetImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_boxlet_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImageRequest.ProtoReflect.Descriptor instead.
func (*GetImageRequest) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_boxlet_proto_rawDescGZIP(), []int{25}
}

func (x *GetImageRequest) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

type ListImagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LabelSelector map[string]string      `protobuf:"bytes,1,rep,name=label_selector,json=labelSelector,proto3" json:"label_selector,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListImagesRequest) Reset() {
	*x = ListImagesRequest{}
	mi := &file_novitabox_v1_boxlet_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListImagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListImagesRequest) ProtoMessage() {}

func (x *ListImagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_boxlet_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListImagesRequest.ProtoReflect.Descriptor instead.
func (*ListImagesRequest) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_boxlet_proto_rawDescGZIP(), []int{26}
}

func (x *ListImagesRequest) GetLabelSelector() map[string]string {
	if x != nil {
		return x.LabelSelector
	}
	return nil
}

type ListImagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Images        []*ImageInfo           `protobuf:"bytes,1,rep,name=images,proto3" json:"images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListImagesResponse) Reset() {
	*x = ListImagesResponse{}
	mi := &file_novitabox_v1_boxlet_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListImagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListImagesResponse) ProtoMessage() {}

func (x *ListImagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_boxlet_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListImagesResponse.ProtoReflect.Descriptor instead.
func (*ListImagesResponse) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_boxlet_proto_rawDescGZIP(), []int{27}
}

func (x *ListImagesResponse) GetImages() []*ImageInfo {
	if x != nil {
		return x.Images
	}
	return nil
}

type NodeStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeStatusRequest) Reset() {
	*x = NodeStatusRequest{}
	mi := &file_novitabox_v1_boxlet_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatusRequest) ProtoMessage() {}

func (x *NodeStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_boxlet_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatusRequest.ProtoReflect.Descriptor instead.
func (*NodeStatusRequest) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_boxlet_proto_rawDescGZIP(), []int{28}
}

type NodeStatusInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	RootDir       string                 `protobuf:"bytes,2,opt,name=root_dir,json=rootDir,proto3" json:"root_dir,omitempty"`
	Ready         bool                   `protobuf:"varint,3,opt,name=ready,proto3" json:"ready,omitempty"`
	RuntimeTypes  []RuntimeType          `protobuf:"varint,4,rep,packed,name=runtime_types,json=runtimeTypes,proto3,enum=novitabox.v1.RuntimeType" json:"runtime_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeStatusInfo) Reset() {
	*x = NodeStatusInfo{}
	mi := &file_novitabox_v1_boxlet_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatusInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatusInfo) ProtoMessage() {}

func (x *NodeStatusInfo) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_boxlet_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatusInfo.ProtoReflect.Descriptor instead.
func (*NodeStatusInfo) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_boxlet_proto_rawDescGZIP(), []int{29}
}

func (x *NodeStatusInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeStatusInfo) GetRootDir() string {
	if x != nil {
		return x.RootDir
	}
	return ""
}

func (x *NodeStatusInfo) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *NodeStatusInfo) GetRuntimeTypes() []RuntimeType {
	if x != nil {
		return x.RuntimeTypes
	}
	return nil
}

type ListRuntimesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRuntimesRequest) Reset() {
	*x = ListRuntimesRequest{}
	mi := &file_novitabox_v1_boxlet_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRuntimesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRuntimesRequest) ProtoMessage() {}

func (x *ListRuntimesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_boxlet_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRuntimesRequest.ProtoReflect.Descriptor instead.
func (*ListRuntimesRequest) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_boxlet_proto_rawDescGZIP(), []int{30}
}

type RuntimeSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuntimeType   RuntimeType            `protobuf:"varint,1,opt,name=runtime_type,json=runtimeType,proto3,enum=novitabox.v1.RuntimeType" json:"runtime_type,omitempty"`
	Capabilities  *RuntimeCapabilities   `protobuf:"bytes,2,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeSummary) Reset() {
	*x = RuntimeSummary{}
	mi := &file_novitabox_v1_boxlet_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeSummary) ProtoMessage() {}

func (x *RuntimeSummary) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_boxlet_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeSummary.ProtoReflect.Descriptor instead.
func (*RuntimeSummary) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_boxlet_proto_rawDescGZIP(), []int{31}
}

func (x *RuntimeSummary) GetRuntimeType() RuntimeType {
	if x != nil {
		return x.RuntimeType
	}
	return RuntimeType_RUNTIME_TYPE_UNSPECIFIED
}

func (x *RuntimeSummary) GetCapabilities() *RuntimeCapabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type ListRuntimesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Runtimes      []*RuntimeSummary      `protobuf:"bytes,1,rep,name=runtimes,proto3" json:"runtimes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRuntimesResponse) Reset() {
	*x = ListRuntimesResponse{}
	mi := &file_novitabox_v1_boxlet_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRuntimesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRuntimesResponse) ProtoMessage() {}

func (x *ListRuntimesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_boxlet_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRuntimesResponse.ProtoReflect.Descriptor instead.
func (*ListRuntimesResponse) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_boxlet_proto_rawDescGZIP(), []int{32}
}

func (x *ListRuntimesResponse) GetRuntimes() []*RuntimeSummary {
	if x != nil {
		return x.Runtimes
	}
	return nil
}

type GetRuntimeCapabilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuntimeType   RuntimeType            `protobuf:"varint,1,opt,name=runtime_type,json=runtimeType,proto3,enum=novitabox.v1.RuntimeType" json:"runtime_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRuntimeCapabilitiesRequest) Reset() {
	*x = GetRuntimeCapabilitiesRequest{}
	mi := &file_novitabox_v1_boxlet_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRuntimeCapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRuntimeCapabilitiesRequest) ProtoMessage() {}

func (x *GetRuntimeCapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_boxlet_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRuntimeCapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*GetRuntimeCapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_boxlet_proto_rawDescGZIP(), []int{33}
}

func (x *GetRuntimeCapabilitiesRequest) GetRuntimeType() RuntimeType {
	if x != nil {
		return x.RuntimeType
	}
	return RuntimeType_RUNTIME_TYPE_UNSPECIFIED
}

type RootfsSourceSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Image         string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	PullMode      string                 `protobuf:"bytes,3,opt,name=pull_mode,json=pullMode,proto3" json:"pull_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RootfsSourceSpec) Reset() {
	*x = RootfsSourceSpec{}
	mi := &file_novitabox_v1_boxlet_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RootfsSourceSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RootfsSourceSpec) ProtoMessage() {}

func (x *RootfsSourceSpec) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_boxlet_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RootfsSourceSpec.ProtoReflect.Descriptor instead.
func (*RootfsSourceSpec) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_boxlet_proto_rawDescGZIP(), []int{34}
}

func (x *RootfsSourceSpec) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *RootfsSourceSpec) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *RootfsSourceSpec) GetPullMode() string {
	if x != nil {
		return x.PullMode
	}
	return ""
}

var File_novitabox_v1_boxlet_proto protoreflect.FileDescriptor

const file_novitabox_v1_boxlet_proto_rawDesc = "" +
	"\n" +
	"\x19novitabox/v1/boxlet.proto\x12\fnovitabox.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x18novitabox/v1/types.proto\"\xed\x04\n" +
	"\x14CreateSandboxRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x1f\n" +
	"\vtemplate_id\x18\x02 \x01(\tR\n" +
	"templateId\x12\x19\n" +
	"\bimage_id\x18\x03 \x01(\tR\aimageId\x12\x1f\n" +
	"\vsnapshot_id\x18\x04 \x01(\tR\n" +
	"snapshotId\x12<\n" +
	"\fruntime_type\x18\x05 \x01(\x0e2\x19.novitabox.v1.RuntimeTypeR\vruntimeType\x12<\n" +
	"\fruntime_spec\x18\x06 \x01(\v2\x19.novitabox.v1.RuntimeSpecR\vruntimeSpec\x12C\n" +
	"\rrootfs_source\x18\a \x01(\v2\x1e.novitabox.v1.RootfsSourceSpecR\frootfsSource\x12F\n" +
	"\x06labels\x18\x14 \x03(\v2..novitabox.v1.CreateSandboxRequest.LabelsEntryR\x06labels\x12U\n" +
	"\vannotations\x18\x15 \x03(\v23.novitabox.v1.CreateSandboxRequest.AnnotationsEntryR\vannotations\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"4\n" +
	"\x13PauseSandboxRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\"5\n" +
	"\x14ResumeSandboxRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\"3\n" +
	"\x12KillSandboxRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\"4\n" +
	"\x13StartSandboxRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\"\\\n" +
	"\x12StopSandboxRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12'\n" +
	"\x0ftimeout_seconds\x18\x02 \x01(\rR\x0etimeoutSeconds\"^\n" +
	"\x14RebootSandboxRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12'\n" +
	"\x0ftimeout_seconds\x18\x02 \x01(\rR\x0etimeoutSeconds\"2\n" +
	"\x11GetSandboxRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\"\xb6\x01\n" +
	"\x14ListSandboxesRequest\x12\\\n" +
	"\x0elabel_selector\x18\x01 \x03(\v25.novitabox.v1.ListSandboxesRequest.LabelSelectorEntryR\rlabelSelector\x1a@\n" +
	"\x12LabelSelectorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"P\n" +
	"\x15ListSandboxesResponse\x127\n" +
	"\tsandboxes\x18\x01 \x03(\v2\x19.novitabox.v1.SandboxInfoR\tsandboxes\"[\n" +
	"\x1bUpdateSandboxBalloonRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x1d\n" +
	"\n" +
	"amount_mib\x18\x02 \x01(\rR\tamountMib\"9\n" +
	"\x18GetSandboxBalloonRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\">\n" +
	"\x1dGetSandboxBalloonStatsRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\"z\n" +
	" UpdateSandboxBalloonStatsRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x127\n" +
	"\x18stats_polling_interval_s\x18\x02 \x01(\rR\x15statsPollingIntervalS\"\x84\x01\n" +
	"!StartSandboxBalloonHintingRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12.\n" +
	"\x13acknowledge_on_stop\x18\x03 \x01(\bR\x11acknowledgeOnStopJ\x04\b\x02\x10\x03R\n" +
	"interval_s\"A\n" +
	" StopSandboxBalloonHintingRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\"@\n" +
	"\x1fGetSandboxBalloonHintingRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\"\xaf\x03\n" +
	"\x15CreateTemplateRequest\x12\x1f\n" +
	"\vtemplate_id\x18\x01 \x01(\tR\n" +
	"templateId\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x02 \x01(\tR\tsandboxId\x12\x19\n" +
	"\bimage_id\x18\x03 \x01(\tR\aimageId\x12!\n" +
	"\fdocker_image\x18\x04 \x01(\tR\vdockerImage\x12\x1b\n" +
	"\tstart_cmd\x18\x05 \x01(\tR\bstartCmd\x12#\n" +
	"\rfrom_template\x18\x06 \x01(\tR\ffromTemplate\x12\x1b\n" +
	"\tready_cmd\x18\a \x01(\tR\breadyCmd\x125\n" +
	"\x05steps\x18\b \x03(\v2\x1f.novitabox.v1.TemplateBuildStepR\x05steps\x12G\n" +
	"\x06labels\x18\x14 \x03(\v2/.novitabox.v1.CreateTemplateRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xdf\x01\n" +
	"\x11TemplateBuildStep\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\x12\x1d\n" +
	"\n" +
	"files_hash\x18\x03 \x01(\tR\tfilesHash\x12G\n" +
	"\benv_vars\x18\x04 \x03(\v2,.novitabox.v1.TemplateBuildStep.EnvVarsEntryR\aenvVars\x1a:\n" +
	"\fEnvVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"8\n" +
	"\x15DeleteTemplateRequest\x12\x1f\n" +
	"\vtemplate_id\x18\x01 \x01(\tR\n" +
	"templateId\"5\n" +
	"\x12GetTemplateRequest\x12\x1f\n" +
	"\vtemplate_id\x18\x01 \x01(\tR\n" +
	"templateId\"\xb6\x01\n" +
	"\x14ListTemplatesRequest\x12\\\n" +
	"\x0elabel_selector\x18\x01 \x03(\v25.novitabox.v1.ListTemplatesRequest.LabelSelectorEntryR\rlabelSelector\x1a@\n" +
	"\x12LabelSelectorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Q\n" +
	"\x15ListTemplatesResponse\x128\n" +
	"\ttemplates\x18\x01 \x03(\v2\x1a.novitabox.v1.TemplateInfoR\ttemplates\"\xd1\x01\n" +
	"\x12CreateImageRequest\x12\x19\n" +
	"\bimage_id\x18\x01 \x01(\tR\aimageId\x12\x1f\n" +
	"\vtemplate_id\x18\x02 \x01(\tR\n" +
	"templateId\x12D\n" +
	"\x06labels\x18\x14 \x03(\v2,.novitabox.v1.CreateImageRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"/\n" +
	"\x12DeleteImageRequest\x12\x19\n" +
	"\bimage_id\x18\x01 \x01(\tR\aimageId\",\n" +
	"\x0fGetImageRequest\x12\x19\n" +
	"\bimage_id\x18\x01 \x01(\tR\aimageId\"\xb0\x01\n" +
	"\x11ListImagesRequest\x12Y\n" +
	"\x0elabel_selector\x18\x01 \x03(\v22.novitabox.v1.ListImagesRequest.LabelSelectorEntryR\rlabelSelector\x1a@\n" +
	"\x12LabelSelectorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"E\n" +
	"\x12ListImagesResponse\x12/\n" +
	"\x06images\x18\x01 \x03(\v2\x17.novitabox.v1.ImageInfoR\x06images\"\x13\n" +
	"\x11NodeStatusRequest\"\x9a\x01\n" +
	"\x0eNodeStatusInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x19\n" +
	"\broot_dir\x18\x02 \x01(\tR\arootDir\x12\x14\n" +
	"\x05ready\x18\x03 \x01(\bR\x05ready\x12>\n" +
	"\rruntime_types\x18\x04 \x03(\x0e2\x19.novitabox.v1.RuntimeTypeR\fruntimeTypes\"\x15\n" +
	"\x13ListRuntimesRequest\"\x95\x01\n" +
	"\x0eRuntimeSummary\x12<\n" +
	"\fruntime_type\x18\x01 \x01(\x0e2\x19.novitabox.v1.RuntimeTypeR\vruntimeType\x12E\n" +
	"\fcapabilities\x18\x02 \x01(\v2!.novitabox.v1.RuntimeCapabilitiesR\fcapabilities\"P\n" +
	"\x14ListRuntimesResponse\x128\n" +
	"\bruntimes\x18\x01 \x03(\v2\x1c.novitabox.v1.RuntimeSummaryR\bruntimes\"]\n" +
	"\x1dGetRuntimeCapabilitiesRequest\x12<\n" +
	"\fruntime_type\x18\x01 \x01(\x0e2\x19.novitabox.v1.RuntimeTypeR\vruntimeType\"a\n" +
	"\x10RootfsSourceSpec\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12\x1b\n" +
	"\tpull_mode\x18\x03 \x01(\tR\bpullMode2\xb6\v\n" +
	"\x14BoxletSandboxService\x12N\n" +
	"\rCreateSandbox\x12\".novitabox.v1.CreateSandboxRequest\x1a\x19.novitabox.v1.SandboxInfo\x12M\n" +
	"\fPauseSandbox\x12!.novitabox.v1.PauseSandboxRequest\x1a\x1a.novitabox.v1.SnapshotInfo\x12N\n" +
	"\rResumeSandbox\x12\".novitabox.v1.ResumeSandboxRequest\x1a\x19.novitabox.v1.SandboxInfo\x12G\n" +
	"\vKillSandbox\x12 .novitabox.v1.KillSandboxRequest\x1a\x16.google.protobuf.Empty\x12L\n" +
	"\fStartSandbox\x12!.novitabox.v1.StartSandboxRequest\x1a\x19.novitabox.v1.SandboxInfo\x12J\n" +
	"\vStopSandbox\x12 .novitabox.v1.StopSandboxRequest\x1a\x19.novitabox.v1.SandboxInfo\x12N\n" +
	"\rRebootSandbox\x12\".novitabox.v1.RebootSandboxRequest\x1a\x19.novitabox.v1.SandboxInfo\x12H\n" +
	"\n" +
	"GetSandbox\x12\x1f.novitabox.v1.GetSandboxRequest\x1a\x19.novitabox.v1.SandboxInfo\x12X\n" +
	"\rListSandboxes\x12\".novitabox.v1.ListSandboxesRequest\x1a#.novitabox.v1.ListSandboxesResponse\x12^\n" +
	"\x14UpdateSandboxBalloon\x12).novitabox.v1.UpdateSandboxBalloonRequest\x1a\x1b.novitabox.v1.BalloonConfig\x12X\n" +
	"\x11GetSandboxBalloon\x12&.novitabox.v1.GetSandboxBalloonRequest\x1a\x1b.novitabox.v1.BalloonConfig\x12a\n" +
	"\x16GetSandboxBalloonStats\x12+.novitabox.v1.GetSandboxBalloonStatsRequest\x1a\x1a.novitabox.v1.BalloonStats\x12h\n" +
	"\x19UpdateSandboxBalloonStats\x12..novitabox.v1.UpdateSandboxBalloonStatsRequest\x1a\x1b.novitabox.v1.BalloonConfig\x12q\n" +
	"\x1aStartSandboxBalloonHinting\x12/.novitabox.v1.StartSandboxBalloonHintingRequest\x1a\".novitabox.v1.BalloonHintingStatus\x12o\n" +
	"\x19StopSandboxBalloonHinting\x12..novitabox.v1.StopSandboxBalloonHintingRequest\x1a\".novitabox.v1.BalloonHintingStatus\x12m\n" +
	"\x18GetSandboxBalloonHinting\x12-.novitabox.v1.GetSandboxBalloonHintingRequest\x1a\".novitabox.v1.BalloonHintingStatus2\x88\x05\n" +
	"\x15BoxletArtifactService\x12Q\n" +
	"\x0eCreateTemplate\x12#.novitabox.v1.CreateTemplateRequest\x1a\x1a.novitabox.v1.TemplateInfo\x12M\n" +
	"\x0eDeleteTemplate\x12#.novitabox.v1.DeleteTemplateRequest\x1a\x16.google.protobuf.Empty\x12K\n" +
	"\vGetTemplate\x12 .novitabox.v1.GetTemplateRequest\x1a\x1a.novitabox.v1.TemplateInfo\x12X\n" +
	"\rListTemplates\x12\".novitabox.v1.ListTemplatesRequest\x1a#.novitabox.v1.ListTemplatesResponse\x12H\n" +
	"\vCreateImage\x12 .novitabox.v1.CreateImageRequest\x1a\x17.novitabox.v1.ImageInfo\x12G\n" +
	"\vDeleteImage\x12 .novitabox.v1.DeleteImageRequest\x1a\x16.google.protobuf.Empty\x12B\n" +
	"\bGetImage\x12\x1d.novitabox.v1.GetImageRequest\x1a\x17.novitabox.v1.ImageInfo\x12O\n" +
	"\n" +
	"ListImages\x12\x1f.novitabox.v1.ListImagesRequest\x1a .novitabox.v1.ListImagesResponse2\xa1\x02\n" +
	"\x11BoxletNodeService\x12K\n" +
	"\n" +
	"NodeStatus\x12\x1f.novitabox.v1.NodeStatusRequest\x1a\x1c.novitabox.v1.NodeStatusInfo\x12U\n" +
	"\fListRuntimes\x12!.novitabox.v1.ListRuntimesRequest\x1a\".novitabox.v1.ListRuntimesResponse\x12h\n" +
	"\x16GetRuntimeCapabilities\x12+.novitabox.v1.GetRuntimeCapabilitiesRequest\x1a!.novitabox.v1.RuntimeCapabilitiesBFZDgithub.com/novitalabs/NovitaBox/internal/pb/novitabox/v1;novitaboxv1b\x06proto3"

var (
	file_novitabox_v1_boxlet_proto_rawDescOnce sync.Once
	file_novitabox_v1_boxlet_proto_rawDescData []byte
)

func file_novitabox_v1_boxlet_proto_rawDescGZIP() []byte {
	file_novitabox_v1_boxlet_proto_rawDescOnce.Do(func() {
		file_novitabox_v1_boxlet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_novitabox_v1_boxlet_proto_rawDesc), len(file_novitabox_v1_boxlet_proto_rawDesc)))
	})
	return file_novitabox_v1_boxlet_proto_rawDescData
}

var file_novitabox_v1_boxlet_proto_msgTypes = make([]protoimpl.MessageInfo, 43)
var file_novitabox_v1_boxlet_proto_goTypes = []any{
	(*CreateSandboxRequest)(nil),              // 0: novitabox.v1.CreateSandboxRequest
	(*PauseSandboxRequest)(nil),               // 1: novitabox.v1.PauseSandboxRequest
	(*ResumeSandboxRequest)(nil),              // 2: novitabox.v1.ResumeSandboxRequest
	(*KillSandboxRequest)(nil),                // 3: novitabox.v1.KillSandboxRequest
	(*StartSandboxRequest)(nil),               // 4: novitabox.v1.StartSandboxRequest
	(*StopSandboxRequest)(nil),                // 5: novitabox.v1.StopSandboxRequest
	(*RebootSandboxRequest)(nil),              // 6: novitabox.v1.RebootSandboxRequest
	(*GetSandboxRequest)(nil),                 // 7: novitabox.v1.GetSandboxRequest
	(*ListSandboxesRequest)(nil),              // 8: novitabox.v1.ListSandboxesRequest
	(*ListSandboxesResponse)(nil),             // 9: novitabox.v1.ListSandboxesResponse
	(*UpdateSandboxBalloonRequest)(nil),       // 10: novitabox.v1.UpdateSandboxBalloonRequest
	(*GetSandboxBalloonRequest)(nil),          // 11: novitabox.v1.GetSandboxBalloonRequest
	(*GetSandboxBalloonStatsRequest)(nil),     // 12: novitabox.v1.GetSandboxBalloonStatsRequest
	(*UpdateSandboxBalloonStatsRequest)(nil),  // 13: novitabox.v1.UpdateSandboxBalloonStatsRequest
	(*StartSandboxBalloonHintingRequest)(nil), // 14: novitabox.v1.StartSandboxBalloonHintingRequest
	(*StopSandboxBalloonHintingRequest)(nil),  // 15: novitabox.v1.StopSandboxBalloonHintingRequest
	(*GetSandboxBalloonHintingRequest)(nil),   // 16: novitabox.v1.GetSandboxBalloonHintingRequest
	(*CreateTemplateRequest)(nil),             // 17: novitabox.v1.CreateTemplateRequest
	(*TemplateBuildStep)(nil),                 // 18: novitabox.v1.TemplateBuildStep
	(*DeleteTemplateRequest)(nil),             // 19: novitabox.v1.DeleteTemplateRequest
	(*GetTemplateRequest)(nil),                // 20: novitabox.v1.GetTemplateRequest
	(*ListTemplatesRequest)(nil),              // 21: novitabox.v1.ListTemplatesRequest
	(*ListTemplatesResponse)(nil),             // 22: novitabox.v1.ListTemplatesResponse
	(*CreateImageRequest)(nil),                // 23: novitabox.v1.CreateImageRequest
	(*DeleteImageRequest)(nil),                // 24: novitabox.v1.DeleteImageRequest
	(*GetImageRequest)(nil),                   // 25: novitabox.v1.GetImageRequest
	(*ListImagesRequest)(nil),                 // 26: novitabox.v1.ListImagesRequest
	(*ListImagesResponse)(nil),                // 27: novitabox.v1.ListImagesResponse
	(*NodeStatusRequest)(nil),                 // 28: novitabox.v1.NodeStatusRequest
	(*NodeStatusInfo)(nil),                    // 29: novitabox.v1.NodeStatusInfo
	(*ListRuntimesRequest)(nil),               // 30: novitabox.v1.ListRuntimesRequest
	(*RuntimeSummary)(nil),                    // 31: novitabox.v1.RuntimeSummary
	(*ListRuntimesResponse)(nil),              // 32: novitabox.v1.ListRuntimesResponse
	(*GetRuntimeCapabilitiesRequest)(nil),     // 33: novitabox.v1.GetRuntimeCapabilitiesRequest
	(*RootfsSourceSpec)(nil),                  // 34: novitabox.v1.RootfsSourceSpec
	nil,                                       // 35: novitabox.v1.CreateSandboxRequest.LabelsEntry
	nil,                                       // 36: novitabox.v1.CreateSandboxRequest.AnnotationsEntry
	nil,                                       // 37: novitabox.v1.ListSandboxesRequest.LabelSelectorEntry
	nil,                                       // 38: novitabox.v1.CreateTemplateRequest.LabelsEntry
	nil,                                       // 39: novitabox.v1.TemplateBuildStep.EnvVarsEntry
	nil,                                       // 40: novitabox.v1.ListTemplatesRequest.LabelSelectorEntry
	nil,                                       // 41: novitabox.v1.CreateImageRequest.LabelsEntry
	nil,                                       // 42: novitabox.v1.ListImagesRequest.LabelSelectorEntry
	(RuntimeType)(0),                          // 43: novitabox.v1.RuntimeType
	(*RuntimeSpec)(nil),                       // 44: novitabox.v1.RuntimeSpec
	(*SandboxInfo)(nil),                       // 45: novitabox.v1.SandboxInfo
	(*TemplateInfo)(nil),                      // 46: novitabox.v1.TemplateInfo
	(*ImageInfo)(nil),                         // 47: novitabox.v1.ImageInfo
	(*RuntimeCapabilities)(nil),               // 48: novitabox.v1.RuntimeCapabilities
	(*SnapshotInfo)(nil),                      // 49: novitabox.v1.SnapshotInfo
	(*emptypb.Empty)(nil),                     // 50: google.protobuf.Empty
	(*BalloonConfig)(nil),                     // 51: novitabox.v1.BalloonConfig
	(*BalloonStats)(nil),                      // 52: novitabox.v1.BalloonStats
	(*BalloonHintingStatus)(nil),              // 53: novitabox.v1.BalloonHintingStatus
}
var file_novitabox_v1_boxlet_proto_depIdxs = []int32{
	43, // 0: novitabox.v1.CreateSandboxRequest.runtime_type:type_name -> novitabox.v1.RuntimeType
	44, // 1: novitabox.v1.CreateSandboxRequest.runtime_spec:type_name -> novitabox.v1.RuntimeSpec
	34, // 2: novitabox.v1.CreateSandboxRequest.rootfs_source:type_name -> novitabox.v1.RootfsSourceSpec
	35, // 3: novitabox.v1.CreateSandboxRequest.labels:type_name -> novitabox.v1.CreateSandboxRequest.LabelsEntry
	36, // 4: novitabox.v1.CreateSandboxRequest.annotations:type_name -> novitabox.v1.CreateSandboxRequest.AnnotationsEntry
	37, // 5: novitabox.v1.ListSandboxesRequest.label_selector:type_name -> novitabox.v1.ListSandboxesRequest.LabelSelectorEntry
	45, // 6: novitabox.v1.ListSandboxesResponse.sandboxes:type_name -> novitabox.v1.SandboxInfo
	18, // 7: novitabox.v1.CreateTemplateRequest.steps:type_name -> novitabox.v1.TemplateBuildStep
	38, // 8: novitabox.v1.CreateTemplateRequest.labels:type_name -> novitabox.v1.CreateTemplateRequest.LabelsEntry
	39, // 9: novitabox.v1.TemplateBuildStep.env_vars:type_name -> novitabox.v1.TemplateBuildStep.EnvVarsEntry
	40, // 10: novitabox.v1.ListTemplatesRequest.label_selector:type_name -> novitabox.v1.ListTemplatesRequest.LabelSelectorEntry
	46, // 11: novitabox.v1.ListTemplatesResponse.templates:type_name -> novitabox.v1.TemplateInfo
	41, // 12: novitabox.v1.CreateImageRequest.labels:type_name -> novitabox.v1.CreateImageRequest.LabelsEntry
	42, // 13: novitabox.v1.ListImagesRequest.label_selector:type_name -> novitabox.v1.ListImagesRequest.LabelSelectorEntry
	47, // 14: novitabox.v1.ListImagesResponse.images:type_name -> novitabox.v1.ImageInfo
	43, // 15: novitabox.v1.NodeStatusInfo.runtime_types:type_name -> novitabox.v1.RuntimeType
	43, // 16: novitabox.v1.RuntimeSummary.runtime_type:type_name -> novitabox.v1.RuntimeType
	48, // 17: novitabox.v1.RuntimeSummary.capabilities:type_name -> novitabox.v1.RuntimeCapabilities
	31, // 18: novitabox.v1.ListRuntimesResponse.runtimes:type_name -> novitabox.v1.RuntimeSummary
	43, // 19: novitabox.v1.GetRuntimeCapabilitiesRequest.runtime_type:type_name -> novitabox.v1.RuntimeType
	0,  // 20: novitabox.v1.BoxletSandboxService.CreateSandbox:input_type -> novitabox.v1.CreateSandboxRequest
	1,  // 21: novitabox.v1.BoxletSandboxService.PauseSandbox:input_type -> novitabox.v1.PauseSandboxRequest
	2,  // 22: novitabox.v1.BoxletSandboxService.ResumeSandbox:input_type -> novitabox.v1.ResumeSandboxRequest
	3,  // 23: novitabox.v1.BoxletSandboxService.KillSandbox:input_type -> novitabox.v1.KillSandboxRequest
	4,  // 24: novitabox.v1.BoxletSandboxService.StartSandbox:input_type -> novitabox.v1.StartSandboxRequest
	5,  // 25: novitabox.v1.BoxletSandboxService.StopSandbox:input_type -> novitabox.v1.StopSandboxRequest
	6,  // 26: novitabox.v1.BoxletSandboxService.RebootSandbox:input_type -> novitabox.v1.RebootSandboxRequest
	7,  // 27: novitabox.v1.BoxletSandboxService.GetSandbox:input_type -> novitabox.v1.GetSandboxRequest
	8,  // 28: novitabox.v1.BoxletSandboxService.ListSandboxes:input_type -> novitabox.v1.ListSandboxesRequest
	10, // 29: novitabox.v1.BoxletSandboxService.UpdateSandboxBalloon:input_type -> novitabox.v1.UpdateSandboxBalloonRequest
	11, // 30: novitabox.v1.BoxletSandboxService.GetSandboxBalloon:input_type -> novitabox.v1.GetSandboxBalloonRequest
	12, // 31: novitabox.v1.BoxletSandboxService.GetSandboxBalloonStats:input_type -> novitabox.v1.GetSandboxBalloonStatsRequest
	13, // 32: novitabox.v1.BoxletSandboxService.UpdateSandboxBalloonStats:input_type -> novitabox.v1.UpdateSandboxBalloonStatsRequest
	14, // 33: novitabox.v1.BoxletSandboxService.StartSandboxBalloonHinting:input_type -> novitabox.v1.StartSandboxBalloonHintingRequest
	15, // 34: novitabox.v1.BoxletSandboxService.StopSandboxBalloonHinting:input_type -> novitabox.v1.StopSandboxBalloonHintingRequest
	16, // 35: novitabox.v1.BoxletSandboxService.GetSandboxBalloonHinting:input_type -> novitabox.v1.GetSandboxBalloonHintingRequest
	17, // 36: novitabox.v1.BoxletArtifactService.CreateTemplate:input_type -> novitabox.v1.CreateTemplateRequest
	19, // 37: novitabox.v1.BoxletArtifactService.DeleteTemplate:input_type -> novitabox.v1.DeleteTemplateRequest
	20, // 38: novitabox.v1.BoxletArtifactService.GetTemplate:input_type -> novitabox.v1.GetTemplateRequest
	21, // 39: novitabox.v1.BoxletArtifactService.ListTemplates:input_type -> novitabox.v1.ListTemplatesRequest
	23, // 40: novitabox.v1.BoxletArtifactService.CreateImage:input_type -> novitabox.v1.CreateImageRequest
	24, // 41: novitabox.v1.BoxletArtifactService.DeleteImage:input_type -> novitabox.v1.DeleteImageRequest
	25, // 42: novitabox.v1.BoxletArtifactService.GetImage:input_type -> novitabox.v1.GetImageRequest
	26, // 43: novitabox.v1.BoxletArtifactService.ListImages:input_type -> novitabox.v1.ListImagesRequest
	28, // 44: novitabox.v1.BoxletNodeService.NodeStatus:input_type -> novitabox.v1.NodeStatusRequest
	30, // 45: novitabox.v1.BoxletNodeService.ListRuntimes:input_type -> novitabox.v1.ListRuntimesRequest
	33, // 46: novitabox.v1.BoxletNodeService.GetRuntimeCapabilities:input_type -> novitabox.v1.GetRuntimeCapabilitiesRequest
	45, // 47: novitabox.v1.BoxletSandboxService.CreateSandbox:output_type -> novitabox.v1.SandboxInfo
	49, // 48: novitabox.v1.BoxletSandboxService.PauseSandbox:output_type -> novitabox.v1.SnapshotInfo
	45, // 49: novitabox.v1.BoxletSandboxService.ResumeSandbox:output_type -> novitabox.v1.SandboxInfo
	50, // 50: novitabox.v1.BoxletSandboxService.KillSandbox:output_type -> google.protobuf.Empty
	45, // 51: novitabox.v1.BoxletSandboxService.StartSandbox:output_type -> novitabox.v1.SandboxInfo
	45, // 52: novitabox.v1.BoxletSandboxService.StopSandbox:output_type -> novitabox.v1.SandboxInfo
	45, // 53: novitabox.v1.BoxletSandboxService.RebootSandbox:output_type -> novitabox.v1.SandboxInfo
	45, // 54: novitabox.v1.BoxletSandboxService.GetSandbox:output_type -> novitabox.v1.SandboxInfo
	9,  // 55: novitabox.v1.BoxletSandboxService.ListSandboxes:output_type -> novitabox.v1.ListSandboxesResponse
	51, // 56: novitabox.v1.BoxletSandboxService.UpdateSandboxBalloon:output_type -> novitabox.v1.BalloonConfig
	51, // 57: novitabox.v1.BoxletSandboxService.GetSandboxBalloon:output_type -> novitabox.v1.BalloonConfig
	52, // 58: novitabox.v1.BoxletSandboxService.GetSandboxBalloonStats:output_type -> novitabox.v1.BalloonStats
	51, // 59: novitabox.v1.BoxletSandboxService.UpdateSandboxBalloonStats:output_type -> novitabox.v1.BalloonConfig
	53, // 60: novitabox.v1.BoxletSandboxService.StartSandboxBalloonHinting:output_type -> novitabox.v1.BalloonHintingStatus
	53, // 61: novitabox.v1.BoxletSandboxService.StopSandboxBalloonHinting:output_type -> novitabox.v1.BalloonHintingStatus
	53, // 62: novitabox.v1.BoxletSandboxService.GetSandboxBalloonHinting:output_type -> novitabox.v1.BalloonHintingStatus
	46, // 63: novitabox.v1.BoxletArtifactService.CreateTemplate:output_type -> novitabox.v1.TemplateInfo
	50, // 64: novitabox.v1.BoxletArtifactService.DeleteTemplate:output_type -> google.protobuf.Empty
	46, // 65: novitabox.v1.BoxletArtifactService.GetTemplate:output_type -> novitabox.v1.TemplateInfo
	22, // 66: novitabox.v1.BoxletArtifactService.ListTemplates:output_type -> novitabox.v1.ListTemplatesResponse
	47, // 67: novitabox.v1.BoxletArtifactService.CreateImage:output_type -> novitabox.v1.ImageInfo
	50, // 68: novitabox.v1.BoxletArtifactService.DeleteImage:output_type -> google.protobuf.Empty
	47, // 69: novitabox.v1.BoxletArtifactService.GetImage:output_type -> novitabox.v1.ImageInfo
	27, // 70: novitabox.v1.BoxletArtifactService.ListImages:output_type -> novitabox.v1.ListImagesResponse
	29, // 71: novitabox.v1.BoxletNodeService.NodeStatus:output_type -> novitabox.v1.NodeStatusInfo
	32, // 72: novitabox.v1.BoxletNodeService.ListRuntimes:output_type -> novitabox.v1.ListRuntimesResponse
	48, // 73: novitabox.v1.BoxletNodeService.GetRuntimeCapabilities:output_type -> novitabox.v1.RuntimeCapabilities
	47, // [47:74] is the sub-list for method output_type
	20, // [20:47] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_novitabox_v1_boxlet_proto_init() }
func file_novitabox_v1_boxlet_proto_init() {
	if File_novitabox_v1_boxlet_proto != nil {
		return
	}
	file_novitabox_v1_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_novitabox_v1_boxlet_proto_rawDesc), len(file_novitabox_v1_boxlet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   43,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_novitabox_v1_boxlet_proto_goTypes,
		DependencyIndexes: file_novitabox_v1_boxlet_proto_depIdxs,
		MessageInfos:      file_novitabox_v1_boxlet_proto_msgTypes,
	}.Build()
	File_novitabox_v1_boxlet_proto = out.File
	file_novitabox_v1_boxlet_proto_goTypes = nil
	file_novitabox_v1_boxlet_proto_depIdxs = nil
}
