// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: novitabox/v1/boxlet.proto

package novitaboxv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BoxletSandboxService_CreateSandbox_FullMethodName              = "/novitabox.v1.BoxletSandboxService/CreateSandbox"
	BoxletSandboxService_PauseSandbox_FullMethodName               = "/novitabox.v1.BoxletSandboxService/PauseSandbox"
	BoxletSandboxService_ResumeSandbox_FullMethodName              = "/novitabox.v1.BoxletSandboxService/ResumeSandbox"
	BoxletSandboxService_KillSandbox_FullMethodName                = "/novitabox.v1.BoxletSandboxService/KillSandbox"
	BoxletSandboxService_StartSandbox_FullMethodName               = "/novitabox.v1.BoxletSandboxService/StartSandbox"
	BoxletSandboxService_StopSandbox_FullMethodName                = "/novitabox.v1.BoxletSandboxService/StopSandbox"
	BoxletSandboxService_RebootSandbox_FullMethodName              = "/novitabox.v1.BoxletSandboxService/RebootSandbox"
	BoxletSandboxService_GetSandbox_FullMethodName                 = "/novitabox.v1.BoxletSandboxService/GetSandbox"
	BoxletSandboxService_ListSandboxes_FullMethodName              = "/novitabox.v1.BoxletSandboxService/ListSandboxes"
	BoxletSandboxService_UpdateSandboxBalloon_FullMethodName       = "/novitabox.v1.BoxletSandboxService/UpdateSandboxBalloon"
	BoxletSandboxService_GetSandboxBalloon_FullMethodName          = "/novitabox.v1.BoxletSandboxService/GetSandboxBalloon"
	BoxletSandboxService_GetSandboxBalloonStats_FullMethodName     = "/novitabox.v1.BoxletSandboxService/GetSandboxBalloonStats"
	BoxletSandboxService_UpdateSandboxBalloonStats_FullMethodName  = "/novitabox.v1.BoxletSandboxService/UpdateSandboxBalloonStats"
	BoxletSandboxService_StartSandboxBalloonHinting_FullMethodName = "/novitabox.v1.BoxletSandboxService/StartSandboxBalloonHinting"
	BoxletSandboxService_StopSandboxBalloonHinting_FullMethodName  = "/novitabox.v1.BoxletSandboxService/StopSandboxBalloonHinting"
	BoxletSandboxService_GetSandboxBalloonHinting_FullMethodName   = "/novitabox.v1.BoxletSandboxService/GetSandboxBalloonHinting"
)

// BoxletSandboxServiceClient is the client API for BoxletSandboxService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BoxletSandboxServiceClient interface {
	CreateSandbox(ctx context.Context, in *CreateSandboxRequest, opts ...grpc.CallOption) (*SandboxInfo, error)
	PauseSandbox(ctx context.Context, in *PauseSandboxRequest, opts ...grpc.CallOption) (*SnapshotInfo, error)
	ResumeSandbox(ctx context.Context, in *ResumeSandboxRequest, opts ...grpc.CallOption) (*SandboxInfo, error)
	KillSandbox(ctx context.Context, in *KillSandboxRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	StartSandbox(ctx context.Context, in *StartSandboxRequest, opts ...grpc.CallOption) (*SandboxInfo, error)
	StopSandbox(ctx context.Context, in *StopSandboxRequest, opts ...grpc.CallOption) (*SandboxInfo, error)
	RebootSandbox(ctx context.Context, in *RebootSandboxRequest, opts ...grpc.CallOption) (*SandboxInfo, error)
	GetSandbox(ctx context.Context, in *GetSandboxRequest, opts ...grpc.CallOption) (*SandboxInfo, error)
	ListSandboxes(ctx context.Context, in *ListSandboxesRequest, opts ...grpc.CallOption) (*ListSandboxesResponse, error)
	UpdateSandboxBalloon(ctx context.Context, in *UpdateSandboxBalloonRequest, opts ...grpc.CallOption) (*BalloonConfig, error)
	GetSandboxBalloon(ctx context.Context, in *GetSandboxBalloonRequest, opts ...grpc.CallOption) (*BalloonConfig, error)
	GetSandboxBalloonStats(ctx context.Context, in *GetSandboxBalloonStatsRequest, opts ...grpc.CallOption) (*BalloonStats, error)
	UpdateSandboxBalloonStats(ctx context.Context, in *UpdateSandboxBalloonStatsRequest, opts ...grpc.CallOption) (*BalloonConfig, error)
	StartSandboxBalloonHinting(ctx context.Context, in *StartSandboxBalloonHintingRequest, opts ...grpc.CallOption) (*BalloonHintingStatus, error)
	StopSandboxBalloonHinting(ctx context.Context, in *StopSandboxBalloonHintingRequest, opts ...grpc.CallOption) (*BalloonHintingStatus, error)
	GetSandboxBalloonHinting(ctx context.Context, in *GetSandboxBalloonHintingRequest, opts ...grpc.CallOption) (*BalloonHintingStatus, error)
}

type boxletSandboxServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBoxletSandboxServiceClient(cc grpc.ClientConnInterface) BoxletSandboxServiceClient {
	return &boxletSandboxServiceClient{cc}
}

func (c *boxletSandboxServiceClient) CreateSandbox(ctx context.Context, in *CreateSandboxRequest, opts ...grpc.CallOption) (*SandboxInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SandboxInfo)
	err := c.cc.Invoke(ctx, BoxletSandboxService_CreateSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boxletSandboxServiceClient) PauseSandbox(ctx context.Context, in *PauseSandboxRequest, opts ...grpc.CallOption) (*SnapshotInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SnapshotInfo)
	err := c.cc.Invoke(ctx, BoxletSandboxService_PauseSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boxletSandboxServiceClient) ResumeSandbox(ctx context.Context, in *ResumeSandboxRequest, opts ...grpc.CallOption) (*SandboxInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SandboxInfo)
	err := c.cc.Invoke(ctx, BoxletSandboxService_ResumeSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boxletSandboxServiceClient) KillSandbox(ctx context.Context, in *KillSandboxRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, BoxletSandboxService_KillSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boxletSandboxServiceClient) StartSandbox(ctx context.Context, in *StartSandboxRequest, opts ...grpc.CallOption) (*SandboxInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SandboxInfo)
	err := c.cc.Invoke(ctx, BoxletSandboxService_StartSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boxletSandboxServiceClient) StopSandbox(ctx context.Context, in *StopSandboxRequest, opts ...grpc.CallOption) (*SandboxInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SandboxInfo)
	err := c.cc.Invoke(ctx, BoxletSandboxService_StopSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boxletSandboxServiceClient) RebootSandbox(ctx context.Context, in *RebootSandboxRequest, opts ...grpc.CallOption) (*SandboxInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SandboxInfo)
	err := c.cc.Invoke(ctx, BoxletSandboxService_RebootSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boxletSandboxServiceClient) GetSandbox(ctx context.Context, in *GetSandboxRequest, opts ...grpc.CallOption) (*SandboxInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SandboxInfo)
	err := c.cc.Invoke(ctx, BoxletSandboxService_GetSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boxletSandboxServiceClient) ListSandboxes(ctx context.Context, in *ListSandboxesRequest, opts ...grpc.CallOption) (*ListSandboxesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSandboxesResponse)
	err := c.cc.Invoke(ctx, BoxletSandboxService_ListSandboxes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boxletSandboxServiceClient) UpdateSandboxBalloon(ctx context.Context, in *UpdateSandboxBalloonRequest, opts ...grpc.CallOption) (*BalloonConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BalloonConfig)
	err := c.cc.Invoke(ctx, BoxletSandboxService_UpdateSandboxBalloon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boxletSandboxServiceClient) GetSandboxBalloon(ctx context.Context, in *GetSandboxBalloonRequest, opts ...grpc.CallOption) (*BalloonConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BalloonConfig)
	err := c.cc.Invoke(ctx, BoxletSandboxService_GetSandboxBalloon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boxletSandboxServiceClient) GetSandboxBalloonStats(ctx context.Context, in *GetSandboxBalloonStatsRequest, opts ...grpc.CallOption) (*BalloonStats, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BalloonStats)
	err := c.cc.Invoke(ctx, BoxletSandboxService_GetSandboxBalloonStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boxletSandboxServiceClient) UpdateSandboxBalloonStats(ctx context.Context, in *UpdateSandboxBalloonStatsRequest, opts ...grpc.CallOption) (*BalloonConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BalloonConfig)
	err := c.cc.Invoke(ctx, BoxletSandboxService_UpdateSandboxBalloonStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boxletSandboxServiceClient) StartSandboxBalloonHinting(ctx context.Context, in *StartSandboxBalloonHintingRequest, opts ...grpc.CallOption) (*BalloonHintingStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BalloonHintingStatus)
	err := c.cc.Invoke(ctx, BoxletSandboxService_StartSandboxBalloonHinting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boxletSandboxServiceClient) StopSandboxBalloonHinting(ctx context.Context, in *StopSandboxBalloonHintingRequest, opts ...grpc.CallOption) (*BalloonHintingStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BalloonHintingStatus)
	err := c.cc.Invoke(ctx, BoxletSandboxService_StopSandboxBalloonHinting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boxletSandboxServiceClient) GetSandboxBalloonHinting(ctx context.Context, in *GetSandboxBalloonHintingRequest, opts ...grpc.CallOption) (*BalloonHintingStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BalloonHintingStatus)
	err := c.cc.Invoke(ctx, BoxletSandboxService_GetSandboxBalloonHinting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BoxletSandboxServiceServer is the server API for BoxletSandboxService service.
// All implementations must embed UnimplementedBoxletSandboxServiceServer
// for forward compatibility.
type BoxletSandboxServiceServer interface {
	CreateSandbox(context.Context, *CreateSandboxRequest) (*SandboxInfo, error)
	PauseSandbox(context.Context, *PauseSandboxRequest) (*SnapshotInfo, error)
	ResumeSandbox(context.Context, *ResumeSandboxRequest) (*SandboxInfo, error)
	KillSandbox(context.Context, *KillSandboxRequest) (*emptypb.Empty, error)
	StartSandbox(context.Context, *StartSandboxRequest) (*SandboxInfo, error)
	StopSandbox(context.Context, *StopSandboxRequest) (*SandboxInfo, error)
	RebootSandbox(context.Context, *RebootSandboxRequest) (*SandboxInfo, error)
	GetSandbox(context.Context, *GetSandboxRequest) (*SandboxInfo, error)
	ListSandboxes(context.Context, *ListSandboxesRequest) (*ListSandboxesResponse, error)
	UpdateSandboxBalloon(context.Context, *UpdateSandboxBalloonRequest) (*BalloonConfig, error)
	GetSandboxBalloon(context.Context, *GetSandboxBalloonRequest) (*BalloonConfig, error)
	GetSandboxBalloonStats(context.Context, *GetSandboxBalloonStatsRequest) (*BalloonStats, error)
	UpdateSandboxBalloonStats(context.Context, *UpdateSandboxBalloonStatsRequest) (*BalloonConfig, error)
	StartSandboxBalloonHinting(context.Context, *StartSandboxBalloonHintingRequest) (*BalloonHintingStatus, error)
	StopSandboxBalloonHinting(context.Context, *StopSandboxBalloonHintingRequest) (*BalloonHintingStatus, error)
	GetSandboxBalloonHinting(context.Context, *GetSandboxBalloonHintingRequest) (*BalloonHintingStatus, error)
	mustEmbedUnimplementedBoxletSandboxServiceServer()
}

// UnimplementedBoxletSandboxServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBoxletSandboxServiceServer struct{}

func (UnimplementedBoxletSandboxServiceServer) CreateSandbox(context.Context, *CreateSandboxRequest) (*SandboxInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSandbox not implemented")
}
func (UnimplementedBoxletSandboxServiceServer) PauseSandbox(context.Context, *PauseSandboxRequest) (*SnapshotInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method PauseSandbox not implemented")
}
func (UnimplementedBoxletSandboxServiceServer) ResumeSandbox(context.Context, *ResumeSandboxRequest) (*SandboxInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method ResumeSandbox not implemented")
}
func (UnimplementedBoxletSandboxServiceServer) KillSandbox(context.Context, *KillSandboxRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method KillSandbox not implemented")
}
func (UnimplementedBoxletSandboxServiceServer) StartSandbox(context.Context, *StartSandboxRequest) (*SandboxInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method StartSandbox not implemented")
}
func (UnimplementedBoxletSandboxServiceServer) StopSandbox(context.Context, *StopSandboxRequest) (*SandboxInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method StopSandbox not implemented")
}
func (UnimplementedBoxletSandboxServiceServer) RebootSandbox(context.Context, *RebootSandboxRequest) (*SandboxInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method RebootSandbox not implemented")
}
func (UnimplementedBoxletSandboxServiceServer) GetSandbox(context.Context, *GetSandboxRequest) (*SandboxInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSandbox not implemented")
}
func (UnimplementedBoxletSandboxServiceServer) ListSandboxes(context.Context, *ListSandboxesRequest) (*ListSandboxesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSandboxes not implemented")
}
func (UnimplementedBoxletSandboxServiceServer) UpdateSandboxBalloon(context.Context, *UpdateSandboxBalloonRequest) (*BalloonConfig, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSandboxBalloon not implemented")
}
func (UnimplementedBoxletSandboxServiceServer) GetSandboxBalloon(context.Context, *GetSandboxBalloonRequest) (*BalloonConfig, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSandboxBalloon not implemented")
}
func (UnimplementedBoxletSandboxServiceServer) GetSandboxBalloonStats(context.Context, *GetSandboxBalloonStatsRequest) (*BalloonStats, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSandboxBalloonStats not implemented")
}
func (UnimplementedBoxletSandboxServiceServer) UpdateSandboxBalloonStats(context.Context, *UpdateSandboxBalloonStatsRequest) (*BalloonConfig, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSandboxBalloonStats not implemented")
}
func (UnimplementedBoxletSandboxServiceServer) StartSandboxBalloonHinting(context.Context, *StartSandboxBalloonHintingRequest) (*BalloonHintingStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method StartSandboxBalloonHinting not implemented")
}
func (UnimplementedBoxletSandboxServiceServer) StopSandboxBalloonHinting(context.Context, *StopSandboxBalloonHintingRequest) (*BalloonHintingStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method StopSandboxBalloonHinting not implemented")
}
func (UnimplementedBoxletSandboxServiceServer) GetSandboxBalloonHinting(context.Context, *GetSandboxBalloonHintingRequest) (*BalloonHintingStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSandboxBalloonHinting not implemented")
}
func (UnimplementedBoxletSandboxServiceServer) mustEmbedUnimplementedBoxletSandboxServiceServer() {}
func (UnimplementedBoxletSandboxServiceServer) testEmbeddedByValue()                              {}

// UnsafeBoxletSandboxServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BoxletSandboxServiceServer will
// result in compilation errors.
type UnsafeBoxletSandboxServiceServer interface {
	mustEmbedUnimplementedBoxletSandboxServiceServer()
}

func RegisterBoxletSandboxServiceServer(s grpc.ServiceRegistrar, srv BoxletSandboxServiceServer) {
	// If the following call panics, it indicates UnimplementedBoxletSandboxServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BoxletSandboxService_ServiceDesc, srv)
}

func _BoxletSandboxService_CreateSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoxletSandboxServiceServer).CreateSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoxletSandboxService_CreateSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoxletSandboxServiceServer).CreateSandbox(ctx, req.(*CreateSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoxletSandboxService_PauseSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PauseSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoxletSandboxServiceServer).PauseSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoxletSandboxService_PauseSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoxletSandboxServiceServer).PauseSandbox(ctx, req.(*PauseSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoxletSandboxService_ResumeSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoxletSandboxServiceServer).ResumeSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoxletSandboxService_ResumeSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoxletSandboxServiceServer).ResumeSandbox(ctx, req.(*ResumeSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoxletSandboxService_KillSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KillSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoxletSandboxServiceServer).KillSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoxletSandboxService_KillSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoxletSandboxServiceServer).KillSandbox(ctx, req.(*KillSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoxletSandboxService_StartSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoxletSandboxServiceServer).StartSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoxletSandboxService_StartSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoxletSandboxServiceServer).StartSandbox(ctx, req.(*StartSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoxletSandboxService_StopSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoxletSandboxServiceServer).StopSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoxletSandboxService_StopSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoxletSandboxServiceServer).StopSandbox(ctx, req.(*StopSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoxletSandboxService_RebootSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RebootSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoxletSandboxServiceServer).RebootSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoxletSandboxService_RebootSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoxletSandboxServiceServer).RebootSandbox(ctx, req.(*RebootSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoxletSandboxService_GetSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoxletSandboxServiceServer).GetSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoxletSandboxService_GetSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoxletSandboxServiceServer).GetSandbox(ctx, req.(*GetSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoxletSandboxService_ListSandboxes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSandboxesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoxletSandboxServiceServer).ListSandboxes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoxletSandboxService_ListSandboxes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoxletSandboxServiceServer).ListSandboxes(ctx, req.(*ListSandboxesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoxletSandboxService_UpdateSandboxBalloon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSandboxBalloonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoxletSandboxServiceServer).UpdateSandboxBalloon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoxletSandboxService_UpdateSandboxBalloon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoxletSandboxServiceServer).UpdateSandboxBalloon(ctx, req.(*UpdateSandboxBalloonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoxletSandboxService_GetSandboxBalloon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSandboxBalloonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoxletSandboxServiceServer).GetSandboxBalloon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoxletSandboxService_GetSandboxBalloon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoxletSandboxServiceServer).GetSandboxBalloon(ctx, req.(*GetSandboxBalloonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoxletSandboxService_GetSandboxBalloonStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSandboxBalloonStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoxletSandboxServiceServer).GetSandboxBalloonStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoxletSandboxService_GetSandboxBalloonStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoxletSandboxServiceServer).GetSandboxBalloonStats(ctx, req.(*GetSandboxBalloonStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoxletSandboxService_UpdateSandboxBalloonStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSandboxBalloonStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoxletSandboxServiceServer).UpdateSandboxBalloonStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoxletSandboxService_UpdateSandboxBalloonStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoxletSandboxServiceServer).UpdateSandboxBalloonStats(ctx, req.(*UpdateSandboxBalloonStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoxletSandboxService_StartSandboxBalloonHinting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartSandboxBalloonHintingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoxletSandboxServiceServer).StartSandboxBalloonHinting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoxletSandboxService_StartSandboxBalloonHinting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoxletSandboxServiceServer).StartSandboxBalloonHinting(ctx, req.(*StartSandboxBalloonHintingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoxletSandboxService_StopSandboxBalloonHinting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopSandboxBalloonHintingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoxletSandboxServiceServer).StopSandboxBalloonHinting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoxletSandboxService_StopSandboxBalloonHinting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoxletSandboxServiceServer).StopSandboxBalloonHinting(ctx, req.(*StopSandboxBalloonHintingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoxletSandboxService_GetSandboxBalloonHinting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSandboxBalloonHintingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoxletSandboxServiceServer).GetSandboxBalloonHinting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoxletSandboxService_GetSandboxBalloonHinting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoxletSandboxServiceServer).GetSandboxBalloonHinting(ctx, req.(*GetSandboxBalloonHintingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BoxletSandboxService_ServiceDesc is the grpc.ServiceDesc for BoxletSandboxService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BoxletSandboxService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "novitabox.v1.BoxletSandboxService",
	HandlerType: (*BoxletSandboxServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSandbox",
			Handler:    _BoxletSandboxService_CreateSandbox_Handler,
		},
		{
			MethodName: "PauseSandbox",
			Handler:    _BoxletSandboxService_PauseSandbox_Handler,
		},
		{
			MethodName: "ResumeSandbox",
			Handler:    _BoxletSandboxService_ResumeSandbox_Handler,
		},
		{
			MethodName: "KillSandbox",
			Handler:    _BoxletSandboxService_KillSandbox_Handler,
		},
		{
			MethodName: "StartSandbox",
			Handler:    _BoxletSandboxService_StartSandbox_Handler,
		},
		{
			MethodName: "StopSandbox",
			Handler:    _BoxletSandboxService_StopSandbox_Handler,
		},
		{
			MethodName: "RebootSandbox",
			Handler:    _BoxletSandboxService_RebootSandbox_Handler,
		},
		{
			MethodName: "GetSandbox",
			Handler:    _BoxletSandboxService_GetSandbox_Handler,
		},
		{
			MethodName: "ListSandboxes",
			Handler:    _BoxletSandboxService_ListSandboxes_Handler,
		},
		{
			MethodName: "UpdateSandboxBalloon",
			Handler:    _BoxletSandboxService_UpdateSandboxBalloon_Handler,
		},
		{
			MethodName: "GetSandboxBalloon",
			Handler:    _BoxletSandboxService_GetSandboxBalloon_Handler,
		},
		{
			MethodName: "GetSandboxBalloonStats",
			Handler:    _BoxletSandboxService_GetSandboxBalloonStats_Handler,
		},
		{
			MethodName: "UpdateSandboxBalloonStats",
			Handler:    _BoxletSandboxService_UpdateSandboxBalloonStats_Handler,
		},
		{
			MethodName: "StartSandboxBalloonHinting",
			Handler:    _BoxletSandboxService_StartSandboxBalloonHinting_Handler,
		},
		{
			MethodName: "StopSandboxBalloonHinting",
			Handler:    _BoxletSandboxService_StopSandboxBalloonHinting_Handler,
		},
		{
			MethodName: "GetSandboxBalloonHinting",
			Handler:    _BoxletSandboxService_GetSandboxBalloonHinting_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "novitabox/v1/boxlet.proto",
}

const (
	BoxletArtifactService_CreateTemplate_FullMethodName = "/novitabox.v1.BoxletArtifactService/CreateTemplate"
	BoxletArtifactService_DeleteTemplate_FullMethodName = "/novitabox.v1.BoxletArtifactService/DeleteTemplate"
	BoxletArtifactService_GetTemplate_FullMethodName    = "/novitabox.v1.BoxletArtifactService/GetTemplate"
	BoxletArtifactService_ListTemplates_FullMethodName  = "/novitabox.v1.BoxletArtifactService/ListTemplates"
	BoxletArtifactService_CreateImage_FullMethodName    = "/novitabox.v1.BoxletArtifactService/CreateImage"
	BoxletArtifactService_DeleteImage_FullMethodName    = "/novitabox.v1.BoxletArtifactService/DeleteImage"
	BoxletArtifactService_GetImage_FullMethodName       = "/novitabox.v1.BoxletArtifactService/GetImage"
	BoxletArtifactService_ListImages_FullMethodName     = "/novitabox.v1.BoxletArtifactService/ListImages"
)

// BoxletArtifactServiceClient is the client API for BoxletArtifactService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BoxletArtifactServiceClient interface {
	CreateTemplate(ctx context.Context, in *CreateTemplateRequest, opts ...grpc.CallOption) (*TemplateInfo, error)
	DeleteTemplate(ctx context.Context, in *DeleteTemplateRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetTemplate(ctx context.Context, in *GetTemplateRequest, opts ...grpc.CallOption) (*TemplateInfo, error)
	ListTemplates(ctx context.Context, in *ListTemplatesRequest, opts ...grpc.CallOption) (*ListTemplatesResponse, error)
	CreateImage(ctx context.Context, in *CreateImageRequest, opts ...grpc.CallOption) (*ImageInfo, error)
	DeleteImage(ctx context.Context, in *DeleteImageRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetImage(ctx context.Context, in *GetImageRequest, opts ...grpc.CallOption) (*ImageInfo, error)
	ListImages(ctx context.Context, in *ListImagesRequest, opts ...grpc.CallOption) (*ListImagesResponse, error)
}

type boxletArtifactServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBoxletArtifactServiceClient(cc grpc.ClientConnInterface) BoxletArtifactServiceClient {
	return &boxletArtifactServiceClient{cc}
}

func (c *boxletArtifactServiceClient) CreateTemplate(ctx context.Context, in *CreateTemplateRequest, opts ...grpc.CallOption) (*TemplateInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TemplateInfo)
	err := c.cc.Invoke(ctx, BoxletArtifactService_CreateTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boxletArtifactServiceClient) DeleteTemplate(ctx context.Context, in *DeleteTemplateRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, BoxletArtifactService_DeleteTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boxletArtifactServiceClient) GetTemplate(ctx context.Context, in *GetTemplateRequest, opts ...grpc.CallOption) (*TemplateInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TemplateInfo)
	err := c.cc.Invoke(ctx, BoxletArtifactService_GetTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boxletArtifactServiceClient) ListTemplates(ctx context.Context, in *ListTemplatesRequest, opts ...grpc.CallOption) (*ListTemplatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTemplatesResponse)
	err := c.cc.Invoke(ctx, BoxletArtifactService_ListTemplates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boxletArtifactServiceClient) CreateImage(ctx context.Context, in *CreateImageRequest, opts ...grpc.CallOption) (*ImageInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImageInfo)
	err := c.cc.Invoke(ctx, BoxletArtifactService_CreateImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boxletArtifactServiceClient) DeleteImage(ctx context.Context, in *DeleteImageRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, BoxletArtifactService_DeleteImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boxletArtifactServiceClient) GetImage(ctx context.Context, in *GetImageRequest, opts ...grpc.CallOption) (*ImageInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImageInfo)
	err := c.cc.Invoke(ctx, BoxletArtifactService_GetImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boxletArtifactServiceClient) ListImages(ctx context.Context, in *ListImagesRequest, opts ...grpc.CallOption) (*ListImagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListImagesResponse)
	err := c.cc.Invoke(ctx, BoxletArtifactService_ListImages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BoxletArtifactServiceServer is the server API for BoxletArtifactService service.
// All implementations must embed UnimplementedBoxletArtifactServiceServer
// for forward compatibility.
type BoxletArtifactServiceServer interface {
	CreateTemplate(context.Context, *CreateTemplateRequest) (*TemplateInfo, error)
	DeleteTemplate(context.Context, *DeleteTemplateRequest) (*emptypb.Empty, error)
	GetTemplate(context.Context, *GetTemplateRequest) (*TemplateInfo, error)
	ListTemplates(context.Context, *ListTemplatesRequest) (*ListTemplatesResponse, error)
	CreateImage(context.Context, *CreateImageRequest) (*ImageInfo, error)
	DeleteImage(context.Context, *DeleteImageRequest) (*emptypb.Empty, error)
	GetImage(context.Context, *GetImageRequest) (*ImageInfo, error)
	ListImages(context.Context, *ListImagesRequest) (*ListImagesResponse, error)
	mustEmbedUnimplementedBoxletArtifactServiceServer()
}

// UnimplementedBoxletArtifactServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBoxletArtifactServiceServer struct{}

func (UnimplementedBoxletArtifactServiceServer) CreateTemplate(context.Context, *CreateTemplateRequest) (*TemplateInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTemplate not implemented")
}
func (UnimplementedBoxletArtifactServiceServer) DeleteTemplate(context.Context, *DeleteTemplateRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTemplate not implemented")
}
func (UnimplementedBoxletArtifactServiceServer) GetTemplate(context.Context, *GetTemplateRequest) (*TemplateInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTemplate not implemented")
}
func (UnimplementedBoxletArtifactServiceServer) ListTemplates(context.Context, *ListTemplatesRequest) (*ListTemplatesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTemplates not implemented")
}
func (UnimplementedBoxletArtifactServiceServer) CreateImage(context.Context, *CreateImageRequest) (*ImageInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateImage not implemented")
}
func (UnimplementedBoxletArtifactServiceServer) DeleteImage(context.Context, *DeleteImageRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteImage not implemented")
}
func (UnimplementedBoxletArtifactServiceServer) GetImage(context.Context, *GetImageRequest) (*ImageInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetImage not implemented")
}
func (UnimplementedBoxletArtifactServiceServer) ListImages(context.Context, *ListImagesRequest) (*ListImagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListImages not implemented")
}
func (UnimplementedBoxletArtifactServiceServer) mustEmbedUnimplementedBoxletArtifactServiceServer() {}
func (UnimplementedBoxletArtifactServiceServer) testEmbeddedByValue()                               {}

// UnsafeBoxletArtifactServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BoxletArtifactServiceServer will
// result in compilation errors.
type UnsafeBoxletArtifactServiceServer interface {
	mustEmbedUnimplementedBoxletArtifactServiceServer()
}

func RegisterBoxletArtifactServiceServer(s grpc.ServiceRegistrar, srv BoxletArtifactServiceServer) {
	// If the following call panics, it indicates UnimplementedBoxletArtifactServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BoxletArtifactService_ServiceDesc, srv)
}

func _BoxletArtifactService_CreateTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoxletArtifactServiceServer).CreateTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoxletArtifactService_CreateTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoxletArtifactServiceServer).CreateTemplate(ctx, req.(*CreateTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoxletArtifactService_DeleteTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoxletArtifactServiceServer).DeleteTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoxletArtifactService_DeleteTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoxletArtifactServiceServer).DeleteTemplate(ctx, req.(*DeleteTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoxletArtifactService_GetTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoxletArtifactServiceServer).GetTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoxletArtifactService_GetTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoxletArtifactServiceServer).GetTemplate(ctx, req.(*GetTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoxletArtifactService_ListTemplates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTemplatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoxletArtifactServiceServer).ListTemplates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoxletArtifactService_ListTemplates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoxletArtifactServiceServer).ListTemplates(ctx, req.(*ListTemplatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoxletArtifactService_CreateImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoxletArtifactServiceServer).CreateImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoxletArtifactService_CreateImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoxletArtifactServiceServer).CreateImage(ctx, req.(*CreateImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoxletArtifactService_DeleteImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoxletArtifactServiceServer).DeleteImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoxletArtifactService_DeleteImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoxletArtifactServiceServer).DeleteImage(ctx, req.(*DeleteImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoxletArtifactService_GetImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoxletArtifactServiceServer).GetImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoxletArtifactService_GetImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoxletArtifactServiceServer).GetImage(ctx, req.(*GetImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoxletArtifactService_ListImages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListImagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoxletArtifactServiceServer).ListImages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoxletArtifactService_ListImages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoxletArtifactServiceServer).ListImages(ctx, req.(*ListImagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BoxletArtifactService_ServiceDesc is the grpc.ServiceDesc for BoxletArtifactService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BoxletArtifactService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "novitabox.v1.BoxletArtifactService",
	HandlerType: (*BoxletArtifactServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTemplate",
			Handler:    _BoxletArtifactService_CreateTemplate_Handler,
		},
		{
			MethodName: "DeleteTemplate",
			Handler:    _BoxletArtifactService_DeleteTemplate_Handler,
		},
		{
			MethodName: "GetTemplate",
			Handler:    _BoxletArtifactService_GetTemplate_Handler,
		},
		{
			MethodName: "ListTemplates",
			Handler:    _BoxletArtifactService_ListTemplates_Handler,
		},
		{
			MethodName: "CreateImage",
			Handler:    _BoxletArtifactService_CreateImage_Handler,
		},
		{
			MethodName: "DeleteImage",
			Handler:    _BoxletArtifactService_DeleteImage_Handler,
		},
		{
			MethodName: "GetImage",
			Handler:    _BoxletArtifactService_GetImage_Handler,
		},
		{
			MethodName: "ListImages",
			Handler:    _BoxletArtifactService_ListImages_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "novitabox/v1/boxlet.proto",
}

const (
	BoxletNodeService_NodeStatus_FullMethodName             = "/novitabox.v1.BoxletNodeService/NodeStatus"
	BoxletNodeService_ListRuntimes_FullMethodName           = "/novitabox.v1.BoxletNodeService/ListRuntimes"
	BoxletNodeService_GetRuntimeCapabilities_FullMethodName = "/novitabox.v1.BoxletNodeService/GetRuntimeCapabilities"
)

// BoxletNodeServiceClient is the client API for BoxletNodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BoxletNodeServiceClient interface {
	NodeStatus(ctx context.Context, in *NodeStatusRequest, opts ...grpc.CallOption) (*NodeStatusInfo, error)
	ListRuntimes(ctx context.Context, in *ListRuntimesRequest, opts ...grpc.CallOption) (*ListRuntimesResponse, error)
	GetRuntimeCapabilities(ctx context.Context, in *GetRuntimeCapabilitiesRequest, opts ...grpc.CallOption) (*RuntimeCapabilities, error)
}

type boxletNodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBoxletNodeServiceClient(cc grpc.ClientConnInterface) BoxletNodeServiceClient {
	return &boxletNodeServiceClient{cc}
}

func (c *boxletNodeServiceClient) NodeStatus(ctx context.Context, in *NodeStatusRequest, opts ...grpc.CallOption) (*NodeStatusInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeStatusInfo)
	err := c.cc.Invoke(ctx, BoxletNodeService_NodeStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boxletNodeServiceClient) ListRuntimes(ctx context.Context, in *ListRuntimesRequest, opts ...grpc.CallOption) (*ListRuntimesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRuntimesResponse)
	err := c.cc.Invoke(ctx, BoxletNodeService_ListRuntimes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boxletNodeServiceClient) GetRuntimeCapabilities(ctx context.Context, in *GetRuntimeCapabilitiesRequest, opts ...grpc.CallOption) (*RuntimeCapabilities, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuntimeCapabilities)
	err := c.cc.Invoke(ctx, BoxletNodeService_GetRuntimeCapabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BoxletNodeServiceServer is the server API for BoxletNodeService service.
// All implementations must embed UnimplementedBoxletNodeServiceServer
// for forward compatibility.
type BoxletNodeServiceServer interface {
	NodeStatus(context.Context, *NodeStatusRequest) (*NodeStatusInfo, error)
	ListRuntimes(context.Context, *ListRuntimesRequest) (*ListRuntimesResponse, error)
	GetRuntimeCapabilities(context.Context, *GetRuntimeCapabilitiesRequest) (*RuntimeCapabilities, error)
	mustEmbedUnimplementedBoxletNodeServiceServer()
}

// UnimplementedBoxletNodeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBoxletNodeServiceServer struct{}

func (UnimplementedBoxletNodeServiceServer) NodeStatus(context.Context, *NodeStatusRequest) (*NodeStatusInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method NodeStatus not implemented")
}
func (UnimplementedBoxletNodeServiceServer) ListRuntimes(context.Context, *ListRuntimesRequest) (*ListRuntimesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRuntimes not implemented")
}
func (UnimplementedBoxletNodeServiceServer) GetRuntimeCapabilities(context.Context, *GetRuntimeCapabilitiesRequest) (*RuntimeCapabilities, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRuntimeCapabilities not implemented")
}
func (UnimplementedBoxletNodeServiceServer) mustEmbedUnimplementedBoxletNodeServiceServer() {}
func (UnimplementedBoxletNodeServiceServer) testEmbeddedByValue()                           {}

// UnsafeBoxletNodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BoxletNodeServiceServer will
// result in compilation errors.
type UnsafeBoxletNodeServiceServer interface {
	mustEmbedUnimplementedBoxletNodeServiceServer()
}

func RegisterBoxletNodeServiceServer(s grpc.ServiceRegistrar, srv BoxletNodeServiceServer) {
	// If the following call panics, it indicates UnimplementedBoxletNodeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BoxletNodeService_ServiceDesc, srv)
}

func _BoxletNodeService_NodeStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoxletNodeServiceServer).NodeStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoxletNodeService_NodeStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoxletNodeServiceServer).NodeStatus(ctx, req.(*NodeStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoxletNodeService_ListRuntimes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRuntimesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoxletNodeServiceServer).ListRuntimes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoxletNodeService_ListRuntimes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoxletNodeServiceServer).ListRuntimes(ctx, req.(*ListRuntimesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoxletNodeService_GetRuntimeCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRuntimeCapabilitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoxletNodeServiceServer).GetRuntimeCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoxletNodeService_GetRuntimeCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoxletNodeServiceServer).GetRuntimeCapabilities(ctx, req.(*GetRuntimeCapabilitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BoxletNodeService_ServiceDesc is the grpc.ServiceDesc for BoxletNodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BoxletNodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "novitabox.v1.BoxletNodeService",
	HandlerType: (*BoxletNodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NodeStatus",
			Handler:    _BoxletNodeService_NodeStatus_Handler,
		},
		{
			MethodName: "ListRuntimes",
			Handler:    _BoxletNodeService_ListRuntimes_Handler,
		},
		{
			MethodName: "GetRuntimeCapabilities",
			Handler:    _BoxletNodeService_GetRuntimeCapabilities_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "novitabox/v1/boxlet.proto",
}
