// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: novitabox/v1/boxshim.proto

package novitaboxv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BoxShim_CreateRuntime_FullMethodName = "/novitabox.v1.BoxShim/CreateRuntime"
	BoxShim_PauseRuntime_FullMethodName  = "/novitabox.v1.BoxShim/PauseRuntime"
	BoxShim_ResumeRuntime_FullMethodName = "/novitabox.v1.BoxShim/ResumeRuntime"
	BoxShim_KillRuntime_FullMethodName   = "/novitabox.v1.BoxShim/KillRuntime"
	BoxShim_StartRuntime_FullMethodName  = "/novitabox.v1.BoxShim/StartRuntime"
	BoxShim_StopRuntime_FullMethodName   = "/novitabox.v1.BoxShim/StopRuntime"
	BoxShim_RebootRuntime_FullMethodName = "/novitabox.v1.BoxShim/RebootRuntime"
	BoxShim_Status_FullMethodName        = "/novitabox.v1.BoxShim/Status"
	BoxShim_Capabilities_FullMethodName  = "/novitabox.v1.BoxShim/Capabilities"
)

// BoxShimClient is the client API for BoxShim service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BoxShimClient interface {
	CreateRuntime(ctx context.Context, in *CreateRuntimeRequest, opts ...grpc.CallOption) (*RuntimeInfo, error)
	PauseRuntime(ctx context.Context, in *PauseRuntimeRequest, opts ...grpc.CallOption) (*RuntimeInfo, error)
	ResumeRuntime(ctx context.Context, in *ResumeRuntimeRequest, opts ...grpc.CallOption) (*RuntimeInfo, error)
	KillRuntime(ctx context.Context, in *KillRuntimeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	StartRuntime(ctx context.Context, in *StartRuntimeRequest, opts ...grpc.CallOption) (*RuntimeInfo, error)
	StopRuntime(ctx context.Context, in *StopRuntimeRequest, opts ...grpc.CallOption) (*RuntimeInfo, error)
	RebootRuntime(ctx context.Context, in *RebootRuntimeRequest, opts ...grpc.CallOption) (*RuntimeInfo, error)
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*RuntimeInfo, error)
	Capabilities(ctx context.Context, in *CapabilitiesRequest, opts ...grpc.CallOption) (*RuntimeCapabilities, error)
}

type boxShimClient struct {
	cc grpc.ClientConnInterface
}

func NewBoxShimClient(cc grpc.ClientConnInterface) BoxShimClient {
	return &boxShimClient{cc}
}

func (c *boxShimClient) CreateRuntime(ctx context.Context, in *CreateRuntimeRequest, opts ...grpc.CallOption) (*RuntimeInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuntimeInfo)
	err := c.cc.Invoke(ctx, BoxShim_CreateRuntime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boxShimClient) PauseRuntime(ctx context.Context, in *PauseRuntimeRequest, opts ...grpc.CallOption) (*RuntimeInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuntimeInfo)
	err := c.cc.Invoke(ctx, BoxShim_PauseRuntime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boxShimClient) ResumeRuntime(ctx context.Context, in *ResumeRuntimeRequest, opts ...grpc.CallOption) (*RuntimeInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuntimeInfo)
	err := c.cc.Invoke(ctx, BoxShim_ResumeRuntime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boxShimClient) KillRuntime(ctx context.Context, in *KillRuntimeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, BoxShim_KillRuntime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boxShimClient) StartRuntime(ctx context.Context, in *StartRuntimeRequest, opts ...grpc.CallOption) (*RuntimeInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuntimeInfo)
	err := c.cc.Invoke(ctx, BoxShim_StartRuntime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boxShimClient) StopRuntime(ctx context.Context, in *StopRuntimeRequest, opts ...grpc.CallOption) (*RuntimeInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuntimeInfo)
	err := c.cc.Invoke(ctx, BoxShim_StopRuntime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boxShimClient) RebootRuntime(ctx context.Context, in *RebootRuntimeRequest, opts ...grpc.CallOption) (*RuntimeInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuntimeInfo)
	err := c.cc.Invoke(ctx, BoxShim_RebootRuntime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boxShimClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*RuntimeInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuntimeInfo)
	err := c.cc.Invoke(ctx, BoxShim_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boxShimClient) Capabilities(ctx context.Context, in *CapabilitiesRequest, opts ...grpc.CallOption) (*RuntimeCapabilities, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuntimeCapabilities)
	err := c.cc.Invoke(ctx, BoxShim_Capabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BoxShimServer is the server API for BoxShim service.
// All implementations must embed UnimplementedBoxShimServer
// for forward compatibility.
type BoxShimServer interface {
	CreateRuntime(context.Context, *CreateRuntimeRequest) (*RuntimeInfo, error)
	PauseRuntime(context.Context, *PauseRuntimeRequest) (*RuntimeInfo, error)
	ResumeRuntime(context.Context, *ResumeRuntimeRequest) (*RuntimeInfo, error)
	KillRuntime(context.Context, *KillRuntimeRequest) (*emptypb.Empty, error)
	StartRuntime(context.Context, *StartRuntimeRequest) (*RuntimeInfo, error)
	StopRuntime(context.Context, *StopRuntimeRequest) (*RuntimeInfo, error)
	RebootRuntime(context.Context, *RebootRuntimeRequest) (*RuntimeInfo, error)
	Status(context.Context, *StatusRequest) (*RuntimeInfo, error)
	Capabilities(context.Context, *CapabilitiesRequest) (*RuntimeCapabilities, error)
	mustEmbedUnimplementedBoxShimServer()
}

// UnimplementedBoxShimServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBoxShimServer struct{}

func (UnimplementedBoxShimServer) CreateRuntime(context.Context, *CreateRuntimeRequest) (*RuntimeInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRuntime not implemented")
}
func (UnimplementedBoxShimServer) PauseRuntime(context.Context, *PauseRuntimeRequest) (*RuntimeInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method PauseRuntime not implemented")
}
func (UnimplementedBoxShimServer) ResumeRuntime(context.Context, *ResumeRuntimeRequest) (*RuntimeInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method ResumeRuntime not implemented")
}
func (UnimplementedBoxShimServer) KillRuntime(context.Context, *KillRuntimeRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method KillRuntime not implemented")
}
func (UnimplementedBoxShimServer) StartRuntime(context.Context, *StartRuntimeRequest) (*RuntimeInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method StartRuntime not implemented")
}
func (UnimplementedBoxShimServer) StopRuntime(context.Context, *StopRuntimeRequest) (*RuntimeInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method StopRuntime not implemented")
}
func (UnimplementedBoxShimServer) RebootRuntime(context.Context, *RebootRuntimeRequest) (*RuntimeInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method RebootRuntime not implemented")
}
func (UnimplementedBoxShimServer) Status(context.Context, *StatusRequest) (*RuntimeInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedBoxShimServer) Capabilities(context.Context, *CapabilitiesRequest) (*RuntimeCapabilities, error) {
	return nil, status.Error(codes.Unimplemented, "method Capabilities not implemented")
}
func (UnimplementedBoxShimServer) mustEmbedUnimplementedBoxShimServer() {}
func (UnimplementedBoxShimServer) testEmbeddedByValue()                 {}

// UnsafeBoxShimServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BoxShimServer will
// result in compilation errors.
type UnsafeBoxShimServer interface {
	mustEmbedUnimplementedBoxShimServer()
}

func RegisterBoxShimServer(s grpc.ServiceRegistrar, srv BoxShimServer) {
	// If the following call panics, it indicates UnimplementedBoxShimServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BoxShim_ServiceDesc, srv)
}

func _BoxShim_CreateRuntime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRuntimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoxShimServer).CreateRuntime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoxShim_CreateRuntime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoxShimServer).CreateRuntime(ctx, req.(*CreateRuntimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoxShim_PauseRuntime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PauseRuntimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoxShimServer).PauseRuntime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoxShim_PauseRuntime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoxShimServer).PauseRuntime(ctx, req.(*PauseRuntimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoxShim_ResumeRuntime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeRuntimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoxShimServer).ResumeRuntime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoxShim_ResumeRuntime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoxShimServer).ResumeRuntime(ctx, req.(*ResumeRuntimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoxShim_KillRuntime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KillRuntimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoxShimServer).KillRuntime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoxShim_KillRuntime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoxShimServer).KillRuntime(ctx, req.(*KillRuntimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoxShim_StartRuntime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRuntimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoxShimServer).StartRuntime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoxShim_StartRuntime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoxShimServer).StartRuntime(ctx, req.(*StartRuntimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoxShim_StopRuntime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRuntimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoxShimServer).StopRuntime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoxShim_StopRuntime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoxShimServer).StopRuntime(ctx, req.(*StopRuntimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoxShim_RebootRuntime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RebootRuntimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoxShimServer).RebootRuntime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoxShim_RebootRuntime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoxShimServer).RebootRuntime(ctx, req.(*RebootRuntimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoxShim_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoxShimServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoxShim_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoxShimServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoxShim_Capabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CapabilitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoxShimServer).Capabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoxShim_Capabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoxShimServer).Capabilities(ctx, req.(*CapabilitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BoxShim_ServiceDesc is the grpc.ServiceDesc for BoxShim service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BoxShim_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "novitabox.v1.BoxShim",
	HandlerType: (*BoxShimServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRuntime",
			Handler:    _BoxShim_CreateRuntime_Handler,
		},
		{
			MethodName: "PauseRuntime",
			Handler:    _BoxShim_PauseRuntime_Handler,
		},
		{
			MethodName: "ResumeRuntime",
			Handler:    _BoxShim_ResumeRuntime_Handler,
		},
		{
			MethodName: "KillRuntime",
			Handler:    _BoxShim_KillRuntime_Handler,
		},
		{
			MethodName: "StartRuntime",
			Handler:    _BoxShim_StartRuntime_Handler,
		},
		{
			MethodName: "StopRuntime",
			Handler:    _BoxShim_StopRuntime_Handler,
		},
		{
			MethodName: "RebootRuntime",
			Handler:    _BoxShim_RebootRuntime_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _BoxShim_Status_Handler,
		},
		{
			MethodName: "Capabilities",
			Handler:    _BoxShim_Capabilities_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "novitabox/v1/boxshim.proto",
}
