// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: novitabox/v1/boxshim.proto

package novitaboxv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRuntimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuntimeSpec   *RuntimeSpec           `protobuf:"bytes,1,opt,name=runtime_spec,json=runtimeSpec,proto3" json:"runtime_spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRuntimeRequest) Reset() {
	*x = CreateRuntimeRequest{}
	mi := &file_novitabox_v1_boxshim_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRuntimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRuntimeRequest) ProtoMessage() {}

func (x *CreateRuntimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_boxshim_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRuntimeRequest.ProtoReflect.Descriptor instead.
func (*CreateRuntimeRequest) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_boxshim_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRuntimeRequest) GetRuntimeSpec() *RuntimeSpec {
	if x != nil {
		return x.RuntimeSpec
	}
	return nil
}

type PauseRuntimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseRuntimeRequest) Reset() {
	*x = PauseRuntimeRequest{}
	mi := &file_novitabox_v1_boxshim_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseRuntimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseRuntimeRequest) ProtoMessage() {}

func (x *PauseRuntimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_boxshim_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseRuntimeRequest.ProtoReflect.Descriptor instead.
func (*PauseRuntimeRequest) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_boxshim_proto_rawDescGZIP(), []int{1}
}

func (x *PauseRuntimeRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

type ResumeRuntimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuntimeSpec   *RuntimeSpec           `protobuf:"bytes,1,opt,name=runtime_spec,json=runtimeSpec,proto3" json:"runtime_spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeRuntimeRequest) Reset() {
	*x = ResumeRuntimeRequest{}
	mi := &file_novitabox_v1_boxshim_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeRuntimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeRuntimeRequest) ProtoMessage() {}

func (x *ResumeRuntimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_boxshim_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeRuntimeRequest.ProtoReflect.Descriptor instead.
func (*ResumeRuntimeRequest) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_boxshim_proto_rawDescGZIP(), []int{2}
}

func (x *ResumeRuntimeRequest) GetRuntimeSpec() *RuntimeSpec {
	if x != nil {
		return x.RuntimeSpec
	}
	return nil
}

type KillRuntimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillRuntimeRequest) Reset() {
	*x = KillRuntimeRequest{}
	mi := &file_novitabox_v1_boxshim_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillRuntimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillRuntimeRequest) ProtoMessage() {}

func (x *KillRuntimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_boxshim_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillRuntimeRequest.ProtoReflect.Descriptor instead.
func (*KillRuntimeRequest) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_boxshim_proto_rawDescGZIP(), []int{3}
}

func (x *KillRuntimeRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

type StartRuntimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuntimeSpec   *RuntimeSpec           `protobuf:"bytes,1,opt,name=runtime_spec,json=runtimeSpec,proto3" json:"runtime_spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRuntimeRequest) Reset() {
	*x = StartRuntimeRequest{}
	mi := &file_novitabox_v1_boxshim_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRuntimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRuntimeRequest) ProtoMessage() {}

func (x *StartRuntimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_boxshim_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRuntimeRequest.ProtoReflect.Descriptor instead.
func (*StartRuntimeRequest) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_boxshim_proto_rawDescGZIP(), []int{4}
}

func (x *StartRuntimeRequest) GetRuntimeSpec() *RuntimeSpec {
	if x != nil {
		return x.RuntimeSpec
	}
	return nil
}

type StopRuntimeRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SandboxId      string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	TimeoutSeconds uint32                 `protobuf:"varint,2,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StopRuntimeRequest) Reset() {
	*x = StopRuntimeRequest{}
	mi := &file_novitabox_v1_boxshim_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRuntimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRuntimeRequest) ProtoMessage() {}

func (x *StopRuntimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_boxshim_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRuntimeRequest.ProtoReflect.Descriptor instead.
func (*StopRuntimeRequest) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_boxshim_proto_rawDescGZIP(), []int{5}
}

func (x *StopRuntimeRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *StopRuntimeRequest) GetTimeoutSeconds() uint32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type RebootRuntimeRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SandboxId      string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	TimeoutSeconds uint32                 `protobuf:"varint,2,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RebootRuntimeRequest) Reset() {
	*x = RebootRuntimeRequest{}
	mi := &file_novitabox_v1_boxshim_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebootRuntimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebootRuntimeRequest) ProtoMessage() {}

func (x *RebootRuntimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_boxshim_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebootRuntimeRequest.ProtoReflect.Descriptor instead.
func (*RebootRuntimeRequest) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_boxshim_proto_rawDescGZIP(), []int{6}
}

func (x *RebootRuntimeRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *RebootRuntimeRequest) GetTimeoutSeconds() uint32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_novitabox_v1_boxshim_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_boxshim_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_boxshim_proto_rawDescGZIP(), []int{7}
}

func (x *StatusRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

type CapabilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuntimeType   RuntimeType            `protobuf:"varint,1,opt,name=runtime_type,json=runtimeType,proto3,enum=novitabox.v1.RuntimeType" json:"runtime_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilitiesRequest) Reset() {
	*x = CapabilitiesRequest{}
	mi := &file_novitabox_v1_boxshim_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesRequest) ProtoMessage() {}

func (x *CapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_boxshim_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*CapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_boxshim_proto_rawDescGZIP(), []int{8}
}

func (x *CapabilitiesRequest) GetRuntimeType() RuntimeType {
	if x != nil {
		return x.RuntimeType
	}
	return RuntimeType_RUNTIME_TYPE_UNSPECIFIED
}

type UpdateBalloonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	AmountMib     uint32                 `protobuf:"varint,2,opt,name=amount_mib,json=amountMib,proto3" json:"amount_mib,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBalloonRequest) Reset() {
	*x = UpdateBalloonRequest{}
	mi := &file_novitabox_v1_boxshim_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBalloonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBalloonRequest) ProtoMessage() {}

func (x *UpdateBalloonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_boxshim_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBalloonRequest.ProtoReflect.Descriptor instead.
func (*UpdateBalloonRequest) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_boxshim_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateBalloonRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *UpdateBalloonRequest) GetAmountMib() uint32 {
	if x != nil {
		return x.AmountMib
	}
	return 0
}

type GetBalloonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalloonRequest) Reset() {
	*x = GetBalloonRequest{}
	mi := &file_novitabox_v1_boxshim_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalloonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalloonRequest) ProtoMessage() {}

func (x *GetBalloonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_boxshim_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalloonRequest.ProtoReflect.Descriptor instead.
func (*GetBalloonRequest) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_boxshim_proto_rawDescGZIP(), []int{10}
}

func (x *GetBalloonRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

type GetBalloonStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalloonStatsRequest) Reset() {
	*x = GetBalloonStatsRequest{}
	mi := &file_novitabox_v1_boxshim_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalloonStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalloonStatsRequest) ProtoMessage() {}

func (x *GetBalloonStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_boxshim_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalloonStatsRequest.ProtoReflect.Descriptor instead.
func (*GetBalloonStatsRequest) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_boxshim_proto_rawDescGZIP(), []int{11}
}

func (x *GetBalloonStatsRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

type UpdateBalloonStatsRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	SandboxId             string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	StatsPollingIntervalS uint32                 `protobuf:"varint,2,opt,name=stats_polling_interval_s,json=statsPollingIntervalS,proto3" json:"stats_polling_interval_s,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *UpdateBalloonStatsRequest) Reset() {
	*x = UpdateBalloonStatsRequest{}
	mi := &file_novitabox_v1_boxshim_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBalloonStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBalloonStatsRequest) ProtoMessage() {}

func (x *UpdateBalloonStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_boxshim_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBalloonStatsRequest.ProtoReflect.Descriptor instead.
func (*UpdateBalloonStatsRequest) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_boxshim_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateBalloonStatsRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *UpdateBalloonStatsRequest) GetStatsPollingIntervalS() uint32 {
	if x != nil {
		return x.StatsPollingIntervalS
	}
	return 0
}

type StartBalloonHintingRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SandboxId         string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	AcknowledgeOnStop bool                   `protobuf:"varint,3,opt,name=acknowledge_on_stop,json=acknowledgeOnStop,proto3" json:"acknowledge_on_stop,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StartBalloonHintingRequest) Reset() {
	*x = StartBalloonHintingRequest{}
	mi := &file_novitabox_v1_boxshim_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartBalloonHintingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartBalloonHintingRequest) ProtoMessage() {}

func (x *StartBalloonHintingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_boxshim_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartBalloonHintingRequest.ProtoReflect.Descriptor instead.
func (*StartBalloonHintingRequest) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_boxshim_proto_rawDescGZIP(), []int{13}
}

func (x *StartBalloonHintingRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *StartBalloonHintingRequest) GetAcknowledgeOnStop() bool {
	if x != nil {
		return x.AcknowledgeOnStop
	}
	return false
}

type StopBalloonHintingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopBalloonHintingRequest) Reset() {
	*x = StopBalloonHintingRequest{}
	mi := &file_novitabox_v1_boxshim_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopBalloonHintingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopBalloonHintingRequest) ProtoMessage() {}

func (x *StopBalloonHintingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_boxshim_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopBalloonHintingRequest.ProtoReflect.Descriptor instead.
func (*StopBalloonHintingRequest) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_boxshim_proto_rawDescGZIP(), []int{14}
}

func (x *StopBalloonHintingRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

type GetBalloonHintingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalloonHintingRequest) Reset() {
	*x = GetBalloonHintingRequest{}
	mi := &file_novitabox_v1_boxshim_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalloonHintingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalloonHintingRequest) ProtoMessage() {}

func (x *GetBalloonHintingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_boxshim_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalloonHintingRequest.ProtoReflect.Descriptor instead.
func (*GetBalloonHintingRequest) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_boxshim_proto_rawDescGZIP(), []int{15}
}

func (x *GetBalloonHintingRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

var File_novitabox_v1_boxshim_proto protoreflect.FileDescriptor

const file_novitabox_v1_boxshim_proto_rawDesc = "" +
	"\n" +
	"\x1anovitabox/v1/boxshim.proto\x12\fnovitabox.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x18novitabox/v1/types.proto\"T\n" +
	"\x14CreateRuntimeRequest\x12<\n" +
	"\fruntime_spec\x18\x01 \x01(\v2\x19.novitabox.v1.RuntimeSpecR\vruntimeSpec\"4\n" +
	"\x13PauseRuntimeRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\"T\n" +
	"\x14ResumeRuntimeRequest\x12<\n" +
	"\fruntime_spec\x18\x01 \x01(\v2\x19.novitabox.v1.RuntimeSpecR\vruntimeSpec\"3\n" +
	"\x12KillRuntimeRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\"S\n" +
	"\x13StartRuntimeRequest\x12<\n" +
	"\fruntime_spec\x18\x01 \x01(\v2\x19.novitabox.v1.RuntimeSpecR\vruntimeSpec\"\\\n" +
	"\x12StopRuntimeRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12'\n" +
	"\x0ftimeout_seconds\x18\x02 \x01(\rR\x0etimeoutSeconds\"^\n" +
	"\x14RebootRuntimeRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12'\n" +
	"\x0ftimeout_seconds\x18\x02 \x01(\rR\x0etimeoutSeconds\".\n" +
	"\rStatusRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\"S\n" +
	"\x13CapabilitiesRequest\x12<\n" +
	"\fruntime_type\x18\x01 \x01(\x0e2\x19.novitabox.v1.RuntimeTypeR\vruntimeType\"T\n" +
	"\x14UpdateBalloonRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x1d\n" +
	"\n" +
	"amount_mib\x18\x02 \x01(\rR\tamountMib\"2\n" +
	"\x11GetBalloonRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\"7\n" +
	"\x16GetBalloonStatsRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\"s\n" +
	"\x19UpdateBalloonStatsRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x127\n" +
	"\x18stats_polling_interval_s\x18\x02 \x01(\rR\x15statsPollingIntervalS\"}\n" +
	"\x1aStartBalloonHintingRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12.\n" +
	"\x13acknowledge_on_stop\x18\x03 \x01(\bR\x11acknowledgeOnStopJ\x04\b\x02\x10\x03R\n" +
	"interval_s\":\n" +
	"\x19StopBalloonHintingRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\"9\n" +
	"\x18GetBalloonHintingRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId2\xba\n" +
	"\n" +
	"\aBoxShim\x12N\n" +
	"\rCreateRuntime\x12\".novitabox.v1.CreateRuntimeRequest\x1a\x19.novitabox.v1.RuntimeInfo\x12L\n" +
	"\fPauseRuntime\x12!.novitabox.v1.PauseRuntimeRequest\x1a\x19.novitabox.v1.RuntimeInfo\x12N\n" +
	"\rResumeRuntime\x12\".novitabox.v1.ResumeRuntimeRequest\x1a\x19.novitabox.v1.RuntimeInfo\x12G\n" +
	"\vKillRuntime\x12 .novitabox.v1.KillRuntimeRequest\x1a\x16.google.protobuf.Empty\x12L\n" +
	"\fStartRuntime\x12!.novitabox.v1.StartRuntimeRequest\x1a\x19.novitabox.v1.RuntimeInfo\x12J\n" +
	"\vStopRuntime\x12 .novitabox.v1.StopRuntimeRequest\x1a\x19.novitabox.v1.RuntimeInfo\x12N\n" +
	"\rRebootRuntime\x12\".novitabox.v1.RebootRuntimeRequest\x1a\x19.novitabox.v1.RuntimeInfo\x12@\n" +
	"\x06Status\x12\x1b.novitabox.v1.StatusRequest\x1a\x19.novitabox.v1.RuntimeInfo\x12T\n" +
	"\fCapabilities\x12!.novitabox.v1.CapabilitiesRequest\x1a!.novitabox.v1.RuntimeCapabilities\x12P\n" +
	"\rUpdateBalloon\x12\".novitabox.v1.UpdateBalloonRequest\x1a\x1b.novitabox.v1.BalloonConfig\x12J\n" +
	"\n" +
	"GetBalloon\x12\x1f.novitabox.v1.GetBalloonRequest\x1a\x1b.novitabox.v1.BalloonConfig\x12S\n" +
	"\x0fGetBalloonStats\x12$.novitabox.v1.GetBalloonStatsRequest\x1a\x1a.novitabox.v1.BalloonStats\x12Z\n" +
	"\x12UpdateBalloonStats\x12'.novitabox.v1.UpdateBalloonStatsRequest\x1a\x1b.novitabox.v1.BalloonConfig\x12c\n" +
	"\x13StartBalloonHinting\x12(.novitabox.v1.StartBalloonHintingRequest\x1a\".novitabox.v1.BalloonHintingStatus\x12a\n" +
	"\x12StopBalloonHinting\x12'.novitabox.v1.StopBalloonHintingRequest\x1a\".novitabox.v1.BalloonHintingStatus\x12_\n" +
	"\x11GetBalloonHinting\x12&.novitabox.v1.GetBalloonHintingRequest\x1a\".novitabox.v1.BalloonHintingStatusBFZDgithub.com/novitalabs/NovitaBox/internal/pb/novitabox/v1;novitaboxv1b\x06proto3"

var (
	file_novitabox_v1_boxshim_proto_rawDescOnce sync.Once
	file_novitabox_v1_boxshim_proto_rawDescData []byte
)

func file_novitabox_v1_boxshim_proto_rawDescGZIP() []byte {
	file_novitabox_v1_boxshim_proto_rawDescOnce.Do(func() {
		file_novitabox_v1_boxshim_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_novitabox_v1_boxshim_proto_rawDesc), len(file_novitabox_v1_boxshim_proto_rawDesc)))
	})
	return file_novitabox_v1_boxshim_proto_rawDescData
}

var file_novitabox_v1_boxshim_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_novitabox_v1_boxshim_proto_goTypes = []any{
	(*CreateRuntimeRequest)(nil),       // 0: novitabox.v1.CreateRuntimeRequest
	(*PauseRuntimeRequest)(nil),        // 1: novitabox.v1.PauseRuntimeRequest
	(*ResumeRuntimeRequest)(nil),       // 2: novitabox.v1.ResumeRuntimeRequest
	(*KillRuntimeRequest)(nil),         // 3: novitabox.v1.KillRuntimeRequest
	(*StartRuntimeRequest)(nil),        // 4: novitabox.v1.StartRuntimeRequest
	(*StopRuntimeRequest)(nil),         // 5: novitabox.v1.StopRuntimeRequest
	(*RebootRuntimeRequest)(nil),       // 6: novitabox.v1.RebootRuntimeRequest
	(*StatusRequest)(nil),              // 7: novitabox.v1.StatusRequest
	(*CapabilitiesRequest)(nil),        // 8: novitabox.v1.CapabilitiesRequest
	(*UpdateBalloonRequest)(nil),       // 9: novitabox.v1.UpdateBalloonRequest
	(*GetBalloonRequest)(nil),          // 10: novitabox.v1.GetBalloonRequest
	(*GetBalloonStatsRequest)(nil),     // 11: novitabox.v1.GetBalloonStatsRequest
	(*UpdateBalloonStatsRequest)(nil),  // 12: novitabox.v1.UpdateBalloonStatsRequest
	(*StartBalloonHintingRequest)(nil), // 13: novitabox.v1.StartBalloonHintingRequest
	(*StopBalloonHintingRequest)(nil),  // 14: novitabox.v1.StopBalloonHintingRequest
	(*GetBalloonHintingRequest)(nil),   // 15: novitabox.v1.GetBalloonHintingRequest
	(*RuntimeSpec)(nil),                // 16: novitabox.v1.RuntimeSpec
	(RuntimeType)(0),                   // 17: novitabox.v1.RuntimeType
	(*RuntimeInfo)(nil),                // 18: novitabox.v1.RuntimeInfo
	(*emptypb.Empty)(nil),              // 19: google.protobuf.Empty
	(*RuntimeCapabilities)(nil),        // 20: novitabox.v1.RuntimeCapabilities
	(*BalloonConfig)(nil),              // 21: novitabox.v1.BalloonConfig
	(*BalloonStats)(nil),               // 22: novitabox.v1.BalloonStats
	(*BalloonHintingStatus)(nil),       // 23: novitabox.v1.BalloonHintingStatus
}
var file_novitabox_v1_boxshim_proto_depIdxs = []int32{
	16, // 0: novitabox.v1.CreateRuntimeRequest.runtime_spec:type_name -> novitabox.v1.RuntimeSpec
	16, // 1: novitabox.v1.ResumeRuntimeRequest.runtime_spec:type_name -> novitabox.v1.RuntimeSpec
	16, // 2: novitabox.v1.StartRuntimeRequest.runtime_spec:type_name -> novitabox.v1.RuntimeSpec
	17, // 3: novitabox.v1.CapabilitiesRequest.runtime_type:type_name -> novitabox.v1.RuntimeType
	0,  // 4: novitabox.v1.BoxShim.CreateRuntime:input_type -> novitabox.v1.CreateRuntimeRequest
	1,  // 5: novitabox.v1.BoxShim.PauseRuntime:input_type -> novitabox.v1.PauseRuntimeRequest
	2,  // 6: novitabox.v1.BoxShim.ResumeRuntime:input_type -> novitabox.v1.ResumeRuntimeRequest
	3,  // 7: novitabox.v1.BoxShim.KillRuntime:input_type -> novitabox.v1.KillRuntimeRequest
	4,  // 8: novitabox.v1.BoxShim.StartRuntime:input_type -> novitabox.v1.StartRuntimeRequest
	5,  // 9: novitabox.v1.BoxShim.StopRuntime:input_type -> novitabox.v1.StopRuntimeRequest
	6,  // 10: novitabox.v1.BoxShim.RebootRuntime:input_type -> novitabox.v1.RebootRuntimeRequest
	7,  // 11: novitabox.v1.BoxShim.Status:input_type -> novitabox.v1.StatusRequest
	8,  // 12: novitabox.v1.BoxShim.Capabilities:input_type -> novitabox.v1.CapabilitiesRequest
	9,  // 13: novitabox.v1.BoxShim.UpdateBalloon:input_type -> novitabox.v1.UpdateBalloonRequest
	10, // 14: novitabox.v1.BoxShim.GetBalloon:input_type -> novitabox.v1.GetBalloonRequest
	11, // 15: novitabox.v1.BoxShim.GetBalloonStats:input_type -> novitabox.v1.GetBalloonStatsRequest
	12, // 16: novitabox.v1.BoxShim.UpdateBalloonStats:input_type -> novitabox.v1.UpdateBalloonStatsRequest
	13, // 17: novitabox.v1.BoxShim.StartBalloonHinting:input_type -> novitabox.v1.StartBalloonHintingRequest
	14, // 18: novitabox.v1.BoxShim.StopBalloonHinting:input_type -> novitabox.v1.StopBalloonHintingRequest
	15, // 19: novitabox.v1.BoxShim.GetBalloonHinting:input_type -> novitabox.v1.GetBalloonHintingRequest
	18, // 20: novitabox.v1.BoxShim.CreateRuntime:output_type -> novitabox.v1.RuntimeInfo
	18, // 21: novitabox.v1.BoxShim.PauseRuntime:output_type -> novitabox.v1.RuntimeInfo
	18, // 22: novitabox.v1.BoxShim.ResumeRuntime:output_type -> novitabox.v1.RuntimeInfo
	19, // 23: novitabox.v1.BoxShim.KillRuntime:output_type -> google.protobuf.Empty
	18, // 24: novitabox.v1.BoxShim.StartRuntime:output_type -> novitabox.v1.RuntimeInfo
	18, // 25: novitabox.v1.BoxShim.StopRuntime:output_type -> novitabox.v1.RuntimeInfo
	18, // 26: novitabox.v1.BoxShim.RebootRuntime:output_type -> novitabox.v1.RuntimeInfo
	18, // 27: novitabox.v1.BoxShim.Status:output_type -> novitabox.v1.RuntimeInfo
	20, // 28: novitabox.v1.BoxShim.Capabilities:output_type -> novitabox.v1.RuntimeCapabilities
	21, // 29: novitabox.v1.BoxShim.UpdateBalloon:output_type -> novitabox.v1.BalloonConfig
	21, // 30: novitabox.v1.BoxShim.GetBalloon:output_type -> novitabox.v1.BalloonConfig
	22, // 31: novitabox.v1.BoxShim.GetBalloonStats:output_type -> novitabox.v1.BalloonStats
	21, // 32: novitabox.v1.BoxShim.UpdateBalloonStats:output_type -> novitabox.v1.BalloonConfig
	23, // 33: novitabox.v1.BoxShim.StartBalloonHinting:output_type -> novitabox.v1.BalloonHintingStatus
	23, // 34: novitabox.v1.BoxShim.StopBalloonHinting:output_type -> novitabox.v1.BalloonHintingStatus
	23, // 35: novitabox.v1.BoxShim.GetBalloonHinting:output_type -> novitabox.v1.BalloonHintingStatus
	20, // [20:36] is the sub-list for method output_type
	4,  // [4:20] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_novitabox_v1_boxshim_proto_init() }
func file_novitabox_v1_boxshim_proto_init() {
	if File_novitabox_v1_boxshim_proto != nil {
		return
	}
	file_novitabox_v1_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_novitabox_v1_boxshim_proto_rawDesc), len(file_novitabox_v1_boxshim_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_novitabox_v1_boxshim_proto_goTypes,
		DependencyIndexes: file_novitabox_v1_boxshim_proto_depIdxs,
		MessageInfos:      file_novitabox_v1_boxshim_proto_msgTypes,
	}.Build()
	File_novitabox_v1_boxshim_proto = out.File
	file_novitabox_v1_boxshim_proto_goTypes = nil
	file_novitabox_v1_boxshim_proto_depIdxs = nil
}
