// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: novitabox/v1/boxshim.proto

package novitaboxv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRuntimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuntimeSpec   *RuntimeSpec           `protobuf:"bytes,1,opt,name=runtime_spec,json=runtimeSpec,proto3" json:"runtime_spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRuntimeRequest) Reset() {
	*x = CreateRuntimeRequest{}
	mi := &file_novitabox_v1_boxshim_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRuntimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRuntimeRequest) ProtoMessage() {}

func (x *CreateRuntimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_boxshim_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRuntimeRequest.ProtoReflect.Descriptor instead.
func (*CreateRuntimeRequest) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_boxshim_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRuntimeRequest) GetRuntimeSpec() *RuntimeSpec {
	if x != nil {
		return x.RuntimeSpec
	}
	return nil
}

type PauseRuntimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseRuntimeRequest) Reset() {
	*x = PauseRuntimeRequest{}
	mi := &file_novitabox_v1_boxshim_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseRuntimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseRuntimeRequest) ProtoMessage() {}

func (x *PauseRuntimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_boxshim_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseRuntimeRequest.ProtoReflect.Descriptor instead.
func (*PauseRuntimeRequest) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_boxshim_proto_rawDescGZIP(), []int{1}
}

func (x *PauseRuntimeRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

type ResumeRuntimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuntimeSpec   *RuntimeSpec           `protobuf:"bytes,1,opt,name=runtime_spec,json=runtimeSpec,proto3" json:"runtime_spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeRuntimeRequest) Reset() {
	*x = ResumeRuntimeRequest{}
	mi := &file_novitabox_v1_boxshim_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeRuntimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeRuntimeRequest) ProtoMessage() {}

func (x *ResumeRuntimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_boxshim_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeRuntimeRequest.ProtoReflect.Descriptor instead.
func (*ResumeRuntimeRequest) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_boxshim_proto_rawDescGZIP(), []int{2}
}

func (x *ResumeRuntimeRequest) GetRuntimeSpec() *RuntimeSpec {
	if x != nil {
		return x.RuntimeSpec
	}
	return nil
}

type KillRuntimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillRuntimeRequest) Reset() {
	*x = KillRuntimeRequest{}
	mi := &file_novitabox_v1_boxshim_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillRuntimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillRuntimeRequest) ProtoMessage() {}

func (x *KillRuntimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_boxshim_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillRuntimeRequest.ProtoReflect.Descriptor instead.
func (*KillRuntimeRequest) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_boxshim_proto_rawDescGZIP(), []int{3}
}

func (x *KillRuntimeRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

type StartRuntimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuntimeSpec   *RuntimeSpec           `protobuf:"bytes,1,opt,name=runtime_spec,json=runtimeSpec,proto3" json:"runtime_spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRuntimeRequest) Reset() {
	*x = StartRuntimeRequest{}
	mi := &file_novitabox_v1_boxshim_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRuntimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRuntimeRequest) ProtoMessage() {}

func (x *StartRuntimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_boxshim_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRuntimeRequest.ProtoReflect.Descriptor instead.
func (*StartRuntimeRequest) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_boxshim_proto_rawDescGZIP(), []int{4}
}

func (x *StartRuntimeRequest) GetRuntimeSpec() *RuntimeSpec {
	if x != nil {
		return x.RuntimeSpec
	}
	return nil
}

type StopRuntimeRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SandboxId      string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	TimeoutSeconds uint32                 `protobuf:"varint,2,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StopRuntimeRequest) Reset() {
	*x = StopRuntimeRequest{}
	mi := &file_novitabox_v1_boxshim_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRuntimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRuntimeRequest) ProtoMessage() {}

func (x *StopRuntimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_boxshim_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRuntimeRequest.ProtoReflect.Descriptor instead.
func (*StopRuntimeRequest) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_boxshim_proto_rawDescGZIP(), []int{5}
}

func (x *StopRuntimeRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *StopRuntimeRequest) GetTimeoutSeconds() uint32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type RebootRuntimeRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SandboxId      string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	TimeoutSeconds uint32                 `protobuf:"varint,2,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RebootRuntimeRequest) Reset() {
	*x = RebootRuntimeRequest{}
	mi := &file_novitabox_v1_boxshim_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebootRuntimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebootRuntimeRequest) ProtoMessage() {}

func (x *RebootRuntimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_boxshim_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebootRuntimeRequest.ProtoReflect.Descriptor instead.
func (*RebootRuntimeRequest) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_boxshim_proto_rawDescGZIP(), []int{6}
}

func (x *RebootRuntimeRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *RebootRuntimeRequest) GetTimeoutSeconds() uint32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_novitabox_v1_boxshim_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_boxshim_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_boxshim_proto_rawDescGZIP(), []int{7}
}

func (x *StatusRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

type CapabilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuntimeType   RuntimeType            `protobuf:"varint,1,opt,name=runtime_type,json=runtimeType,proto3,enum=novitabox.v1.RuntimeType" json:"runtime_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilitiesRequest) Reset() {
	*x = CapabilitiesRequest{}
	mi := &file_novitabox_v1_boxshim_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesRequest) ProtoMessage() {}

func (x *CapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_boxshim_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*CapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_boxshim_proto_rawDescGZIP(), []int{8}
}

func (x *CapabilitiesRequest) GetRuntimeType() RuntimeType {
	if x != nil {
		return x.RuntimeType
	}
	return RuntimeType_RUNTIME_TYPE_UNSPECIFIED
}

var File_novitabox_v1_boxshim_proto protoreflect.FileDescriptor

const file_novitabox_v1_boxshim_proto_rawDesc = "" +
	"\n" +
	"\x1anovitabox/v1/boxshim.proto\x12\fnovitabox.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x18novitabox/v1/types.proto\"T\n" +
	"\x14CreateRuntimeRequest\x12<\n" +
	"\fruntime_spec\x18\x01 \x01(\v2\x19.novitabox.v1.RuntimeSpecR\vruntimeSpec\"4\n" +
	"\x13PauseRuntimeRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\"T\n" +
	"\x14ResumeRuntimeRequest\x12<\n" +
	"\fruntime_spec\x18\x01 \x01(\v2\x19.novitabox.v1.RuntimeSpecR\vruntimeSpec\"3\n" +
	"\x12KillRuntimeRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\"S\n" +
	"\x13StartRuntimeRequest\x12<\n" +
	"\fruntime_spec\x18\x01 \x01(\v2\x19.novitabox.v1.RuntimeSpecR\vruntimeSpec\"\\\n" +
	"\x12StopRuntimeRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12'\n" +
	"\x0ftimeout_seconds\x18\x02 \x01(\rR\x0etimeoutSeconds\"^\n" +
	"\x14RebootRuntimeRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12'\n" +
	"\x0ftimeout_seconds\x18\x02 \x01(\rR\x0etimeoutSeconds\".\n" +
	"\rStatusRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\"S\n" +
	"\x13CapabilitiesRequest\x12<\n" +
	"\fruntime_type\x18\x01 \x01(\x0e2\x19.novitabox.v1.RuntimeTypeR\vruntimeType2\xc2\x05\n" +
	"\aBoxShim\x12N\n" +
	"\rCreateRuntime\x12\".novitabox.v1.CreateRuntimeRequest\x1a\x19.novitabox.v1.RuntimeInfo\x12L\n" +
	"\fPauseRuntime\x12!.novitabox.v1.PauseRuntimeRequest\x1a\x19.novitabox.v1.RuntimeInfo\x12N\n" +
	"\rResumeRuntime\x12\".novitabox.v1.ResumeRuntimeRequest\x1a\x19.novitabox.v1.RuntimeInfo\x12G\n" +
	"\vKillRuntime\x12 .novitabox.v1.KillRuntimeRequest\x1a\x16.google.protobuf.Empty\x12L\n" +
	"\fStartRuntime\x12!.novitabox.v1.StartRuntimeRequest\x1a\x19.novitabox.v1.RuntimeInfo\x12J\n" +
	"\vStopRuntime\x12 .novitabox.v1.StopRuntimeRequest\x1a\x19.novitabox.v1.RuntimeInfo\x12N\n" +
	"\rRebootRuntime\x12\".novitabox.v1.RebootRuntimeRequest\x1a\x19.novitabox.v1.RuntimeInfo\x12@\n" +
	"\x06Status\x12\x1b.novitabox.v1.StatusRequest\x1a\x19.novitabox.v1.RuntimeInfo\x12T\n" +
	"\fCapabilities\x12!.novitabox.v1.CapabilitiesRequest\x1a!.novitabox.v1.RuntimeCapabilitiesBFZDgithub.com/novitalabs/NovitaBox/internal/pb/novitabox/v1;novitaboxv1b\x06proto3"

var (
	file_novitabox_v1_boxshim_proto_rawDescOnce sync.Once
	file_novitabox_v1_boxshim_proto_rawDescData []byte
)

func file_novitabox_v1_boxshim_proto_rawDescGZIP() []byte {
	file_novitabox_v1_boxshim_proto_rawDescOnce.Do(func() {
		file_novitabox_v1_boxshim_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_novitabox_v1_boxshim_proto_rawDesc), len(file_novitabox_v1_boxshim_proto_rawDesc)))
	})
	return file_novitabox_v1_boxshim_proto_rawDescData
}

var file_novitabox_v1_boxshim_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_novitabox_v1_boxshim_proto_goTypes = []any{
	(*CreateRuntimeRequest)(nil), // 0: novitabox.v1.CreateRuntimeRequest
	(*PauseRuntimeRequest)(nil),  // 1: novitabox.v1.PauseRuntimeRequest
	(*ResumeRuntimeRequest)(nil), // 2: novitabox.v1.ResumeRuntimeRequest
	(*KillRuntimeRequest)(nil),   // 3: novitabox.v1.KillRuntimeRequest
	(*StartRuntimeRequest)(nil),  // 4: novitabox.v1.StartRuntimeRequest
	(*StopRuntimeRequest)(nil),   // 5: novitabox.v1.StopRuntimeRequest
	(*RebootRuntimeRequest)(nil), // 6: novitabox.v1.RebootRuntimeRequest
	(*StatusRequest)(nil),        // 7: novitabox.v1.StatusRequest
	(*CapabilitiesRequest)(nil),  // 8: novitabox.v1.CapabilitiesRequest
	(*RuntimeSpec)(nil),          // 9: novitabox.v1.RuntimeSpec
	(RuntimeType)(0),             // 10: novitabox.v1.RuntimeType
	(*RuntimeInfo)(nil),          // 11: novitabox.v1.RuntimeInfo
	(*emptypb.Empty)(nil),        // 12: google.protobuf.Empty
	(*RuntimeCapabilities)(nil),  // 13: novitabox.v1.RuntimeCapabilities
}
var file_novitabox_v1_boxshim_proto_depIdxs = []int32{
	9,  // 0: novitabox.v1.CreateRuntimeRequest.runtime_spec:type_name -> novitabox.v1.RuntimeSpec
	9,  // 1: novitabox.v1.ResumeRuntimeRequest.runtime_spec:type_name -> novitabox.v1.RuntimeSpec
	9,  // 2: novitabox.v1.StartRuntimeRequest.runtime_spec:type_name -> novitabox.v1.RuntimeSpec
	10, // 3: novitabox.v1.CapabilitiesRequest.runtime_type:type_name -> novitabox.v1.RuntimeType
	0,  // 4: novitabox.v1.BoxShim.CreateRuntime:input_type -> novitabox.v1.CreateRuntimeRequest
	1,  // 5: novitabox.v1.BoxShim.PauseRuntime:input_type -> novitabox.v1.PauseRuntimeRequest
	2,  // 6: novitabox.v1.BoxShim.ResumeRuntime:input_type -> novitabox.v1.ResumeRuntimeRequest
	3,  // 7: novitabox.v1.BoxShim.KillRuntime:input_type -> novitabox.v1.KillRuntimeRequest
	4,  // 8: novitabox.v1.BoxShim.StartRuntime:input_type -> novitabox.v1.StartRuntimeRequest
	5,  // 9: novitabox.v1.BoxShim.StopRuntime:input_type -> novitabox.v1.StopRuntimeRequest
	6,  // 10: novitabox.v1.BoxShim.RebootRuntime:input_type -> novitabox.v1.RebootRuntimeRequest
	7,  // 11: novitabox.v1.BoxShim.Status:input_type -> novitabox.v1.StatusRequest
	8,  // 12: novitabox.v1.BoxShim.Capabilities:input_type -> novitabox.v1.CapabilitiesRequest
	11, // 13: novitabox.v1.BoxShim.CreateRuntime:output_type -> novitabox.v1.RuntimeInfo
	11, // 14: novitabox.v1.BoxShim.PauseRuntime:output_type -> novitabox.v1.RuntimeInfo
	11, // 15: novitabox.v1.BoxShim.ResumeRuntime:output_type -> novitabox.v1.RuntimeInfo
	12, // 16: novitabox.v1.BoxShim.KillRuntime:output_type -> google.protobuf.Empty
	11, // 17: novitabox.v1.BoxShim.StartRuntime:output_type -> novitabox.v1.RuntimeInfo
	11, // 18: novitabox.v1.BoxShim.StopRuntime:output_type -> novitabox.v1.RuntimeInfo
	11, // 19: novitabox.v1.BoxShim.RebootRuntime:output_type -> novitabox.v1.RuntimeInfo
	11, // 20: novitabox.v1.BoxShim.Status:output_type -> novitabox.v1.RuntimeInfo
	13, // 21: novitabox.v1.BoxShim.Capabilities:output_type -> novitabox.v1.RuntimeCapabilities
	13, // [13:22] is the sub-list for method output_type
	4,  // [4:13] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_novitabox_v1_boxshim_proto_init() }
func file_novitabox_v1_boxshim_proto_init() {
	if File_novitabox_v1_boxshim_proto != nil {
		return
	}
	file_novitabox_v1_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_novitabox_v1_boxshim_proto_rawDesc), len(file_novitabox_v1_boxshim_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_novitabox_v1_boxshim_proto_goTypes,
		DependencyIndexes: file_novitabox_v1_boxshim_proto_depIdxs,
		MessageInfos:      file_novitabox_v1_boxshim_proto_msgTypes,
	}.Build()
	File_novitabox_v1_boxshim_proto = out.File
	file_novitabox_v1_boxshim_proto_goTypes = nil
	file_novitabox_v1_boxshim_proto_depIdxs = nil
}
