// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: novitabox/v1/types.proto

package novitaboxv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SandboxState int32

const (
	SandboxState_SANDBOX_STATE_UNSPECIFIED SandboxState = 0
	SandboxState_SANDBOX_STATE_CREATING    SandboxState = 1
	SandboxState_SANDBOX_STATE_RUNNING     SandboxState = 2
	SandboxState_SANDBOX_STATE_PAUSING     SandboxState = 3
	SandboxState_SANDBOX_STATE_PAUSED      SandboxState = 4
	SandboxState_SANDBOX_STATE_RESUMING    SandboxState = 5
	SandboxState_SANDBOX_STATE_STOPPING    SandboxState = 6
	SandboxState_SANDBOX_STATE_STOPPED     SandboxState = 7
	SandboxState_SANDBOX_STATE_STARTING    SandboxState = 8
	SandboxState_SANDBOX_STATE_REBOOTING   SandboxState = 9
	SandboxState_SANDBOX_STATE_KILLING     SandboxState = 10
	SandboxState_SANDBOX_STATE_KILLED      SandboxState = 11
	SandboxState_SANDBOX_STATE_FAILED      SandboxState = 12
	SandboxState_SANDBOX_STATE_UNKNOWN     SandboxState = 13
)

// Enum value maps for SandboxState.
var (
	SandboxState_name = map[int32]string{
		0:  "SANDBOX_STATE_UNSPECIFIED",
		1:  "SANDBOX_STATE_CREATING",
		2:  "SANDBOX_STATE_RUNNING",
		3:  "SANDBOX_STATE_PAUSING",
		4:  "SANDBOX_STATE_PAUSED",
		5:  "SANDBOX_STATE_RESUMING",
		6:  "SANDBOX_STATE_STOPPING",
		7:  "SANDBOX_STATE_STOPPED",
		8:  "SANDBOX_STATE_STARTING",
		9:  "SANDBOX_STATE_REBOOTING",
		10: "SANDBOX_STATE_KILLING",
		11: "SANDBOX_STATE_KILLED",
		12: "SANDBOX_STATE_FAILED",
		13: "SANDBOX_STATE_UNKNOWN",
	}
	SandboxState_value = map[string]int32{
		"SANDBOX_STATE_UNSPECIFIED": 0,
		"SANDBOX_STATE_CREATING":    1,
		"SANDBOX_STATE_RUNNING":     2,
		"SANDBOX_STATE_PAUSING":     3,
		"SANDBOX_STATE_PAUSED":      4,
		"SANDBOX_STATE_RESUMING":    5,
		"SANDBOX_STATE_STOPPING":    6,
		"SANDBOX_STATE_STOPPED":     7,
		"SANDBOX_STATE_STARTING":    8,
		"SANDBOX_STATE_REBOOTING":   9,
		"SANDBOX_STATE_KILLING":     10,
		"SANDBOX_STATE_KILLED":      11,
		"SANDBOX_STATE_FAILED":      12,
		"SANDBOX_STATE_UNKNOWN":     13,
	}
)

func (x SandboxState) Enum() *SandboxState {
	p := new(SandboxState)
	*p = x
	return p
}

func (x SandboxState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SandboxState) Descriptor() protoreflect.EnumDescriptor {
	return file_novitabox_v1_types_proto_enumTypes[0].Descriptor()
}

func (SandboxState) Type() protoreflect.EnumType {
	return &file_novitabox_v1_types_proto_enumTypes[0]
}

func (x SandboxState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SandboxState.Descriptor instead.
func (SandboxState) EnumDescriptor() ([]byte, []int) {
	return file_novitabox_v1_types_proto_rawDescGZIP(), []int{0}
}

type RuntimeType int32

const (
	RuntimeType_RUNTIME_TYPE_UNSPECIFIED      RuntimeType = 0
	RuntimeType_RUNTIME_TYPE_FIRECRACKER      RuntimeType = 1
	RuntimeType_RUNTIME_TYPE_CLOUD_HYPERVISOR RuntimeType = 2
	RuntimeType_RUNTIME_TYPE_CONTAINER        RuntimeType = 3
)

// Enum value maps for RuntimeType.
var (
	RuntimeType_name = map[int32]string{
		0: "RUNTIME_TYPE_UNSPECIFIED",
		1: "RUNTIME_TYPE_FIRECRACKER",
		2: "RUNTIME_TYPE_CLOUD_HYPERVISOR",
		3: "RUNTIME_TYPE_CONTAINER",
	}
	RuntimeType_value = map[string]int32{
		"RUNTIME_TYPE_UNSPECIFIED":      0,
		"RUNTIME_TYPE_FIRECRACKER":      1,
		"RUNTIME_TYPE_CLOUD_HYPERVISOR": 2,
		"RUNTIME_TYPE_CONTAINER":        3,
	}
)

func (x RuntimeType) Enum() *RuntimeType {
	p := new(RuntimeType)
	*p = x
	return p
}

func (x RuntimeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RuntimeType) Descriptor() protoreflect.EnumDescriptor {
	return file_novitabox_v1_types_proto_enumTypes[1].Descriptor()
}

func (RuntimeType) Type() protoreflect.EnumType {
	return &file_novitabox_v1_types_proto_enumTypes[1]
}

func (x RuntimeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RuntimeType.Descriptor instead.
func (RuntimeType) EnumDescriptor() ([]byte, []int) {
	return file_novitabox_v1_types_proto_rawDescGZIP(), []int{1}
}

type RuntimeState int32

const (
	RuntimeState_RUNTIME_STATE_UNSPECIFIED RuntimeState = 0
	RuntimeState_RUNTIME_STATE_CREATED     RuntimeState = 1
	RuntimeState_RUNTIME_STATE_RUNNING     RuntimeState = 2
	RuntimeState_RUNTIME_STATE_PAUSED      RuntimeState = 3
	RuntimeState_RUNTIME_STATE_STOPPED     RuntimeState = 4
	RuntimeState_RUNTIME_STATE_EXITED      RuntimeState = 5
	RuntimeState_RUNTIME_STATE_FAILED      RuntimeState = 6
	RuntimeState_RUNTIME_STATE_UNKNOWN     RuntimeState = 7
)

// Enum value maps for RuntimeState.
var (
	RuntimeState_name = map[int32]string{
		0: "RUNTIME_STATE_UNSPECIFIED",
		1: "RUNTIME_STATE_CREATED",
		2: "RUNTIME_STATE_RUNNING",
		3: "RUNTIME_STATE_PAUSED",
		4: "RUNTIME_STATE_STOPPED",
		5: "RUNTIME_STATE_EXITED",
		6: "RUNTIME_STATE_FAILED",
		7: "RUNTIME_STATE_UNKNOWN",
	}
	RuntimeState_value = map[string]int32{
		"RUNTIME_STATE_UNSPECIFIED": 0,
		"RUNTIME_STATE_CREATED":     1,
		"RUNTIME_STATE_RUNNING":     2,
		"RUNTIME_STATE_PAUSED":      3,
		"RUNTIME_STATE_STOPPED":     4,
		"RUNTIME_STATE_EXITED":      5,
		"RUNTIME_STATE_FAILED":      6,
		"RUNTIME_STATE_UNKNOWN":     7,
	}
)

func (x RuntimeState) Enum() *RuntimeState {
	p := new(RuntimeState)
	*p = x
	return p
}

func (x RuntimeState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RuntimeState) Descriptor() protoreflect.EnumDescriptor {
	return file_novitabox_v1_types_proto_enumTypes[2].Descriptor()
}

func (RuntimeState) Type() protoreflect.EnumType {
	return &file_novitabox_v1_types_proto_enumTypes[2]
}

func (x RuntimeState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RuntimeState.Descriptor instead.
func (RuntimeState) EnumDescriptor() ([]byte, []int) {
	return file_novitabox_v1_types_proto_rawDescGZIP(), []int{2}
}

type SandboxInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	State         SandboxState           `protobuf:"varint,2,opt,name=state,proto3,enum=novitabox.v1.SandboxState" json:"state,omitempty"`
	RuntimeType   RuntimeType            `protobuf:"varint,3,opt,name=runtime_type,json=runtimeType,proto3,enum=novitabox.v1.RuntimeType" json:"runtime_type,omitempty"`
	TemplateId    string                 `protobuf:"bytes,4,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	ImageId       string                 `protobuf:"bytes,5,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	SnapshotId    string                 `protobuf:"bytes,6,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	CreatedAtUnix int64                  `protobuf:"varint,7,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	UpdatedAtUnix int64                  `protobuf:"varint,8,opt,name=updated_at_unix,json=updatedAtUnix,proto3" json:"updated_at_unix,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,20,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Annotations   map[string]string      `protobuf:"bytes,21,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxInfo) Reset() {
	*x = SandboxInfo{}
	mi := &file_novitabox_v1_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxInfo) ProtoMessage() {}

func (x *SandboxInfo) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxInfo.ProtoReflect.Descriptor instead.
func (*SandboxInfo) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *SandboxInfo) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *SandboxInfo) GetState() SandboxState {
	if x != nil {
		return x.State
	}
	return SandboxState_SANDBOX_STATE_UNSPECIFIED
}

func (x *SandboxInfo) GetRuntimeType() RuntimeType {
	if x != nil {
		return x.RuntimeType
	}
	return RuntimeType_RUNTIME_TYPE_UNSPECIFIED
}

func (x *SandboxInfo) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *SandboxInfo) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *SandboxInfo) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *SandboxInfo) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

func (x *SandboxInfo) GetUpdatedAtUnix() int64 {
	if x != nil {
		return x.UpdatedAtUnix
	}
	return 0
}

func (x *SandboxInfo) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *SandboxInfo) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

type SnapshotInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnapshotId    string                 `protobuf:"bytes,1,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	SandboxId     string                 `protobuf:"bytes,2,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	RootfsPath    string                 `protobuf:"bytes,3,opt,name=rootfs_path,json=rootfsPath,proto3" json:"rootfs_path,omitempty"`
	MemfilePath   string                 `protobuf:"bytes,4,opt,name=memfile_path,json=memfilePath,proto3" json:"memfile_path,omitempty"`
	SnapfilePath  string                 `protobuf:"bytes,5,opt,name=snapfile_path,json=snapfilePath,proto3" json:"snapfile_path,omitempty"`
	CreatedAtUnix int64                  `protobuf:"varint,6,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,20,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotInfo) Reset() {
	*x = SnapshotInfo{}
	mi := &file_novitabox_v1_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotInfo) ProtoMessage() {}

func (x *SnapshotInfo) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotInfo.ProtoReflect.Descriptor instead.
func (*SnapshotInfo) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_types_proto_rawDescGZIP(), []int{1}
}

func (x *SnapshotInfo) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *SnapshotInfo) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *SnapshotInfo) GetRootfsPath() string {
	if x != nil {
		return x.RootfsPath
	}
	return ""
}

func (x *SnapshotInfo) GetMemfilePath() string {
	if x != nil {
		return x.MemfilePath
	}
	return ""
}

func (x *SnapshotInfo) GetSnapfilePath() string {
	if x != nil {
		return x.SnapfilePath
	}
	return ""
}

func (x *SnapshotInfo) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

func (x *SnapshotInfo) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type TemplateInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TemplateId    string                 `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	RootfsPath    string                 `protobuf:"bytes,2,opt,name=rootfs_path,json=rootfsPath,proto3" json:"rootfs_path,omitempty"`
	MemfilePath   string                 `protobuf:"bytes,3,opt,name=memfile_path,json=memfilePath,proto3" json:"memfile_path,omitempty"`
	SnapfilePath  string                 `protobuf:"bytes,4,opt,name=snapfile_path,json=snapfilePath,proto3" json:"snapfile_path,omitempty"`
	CreatedAtUnix int64                  `protobuf:"varint,5,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,20,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemplateInfo) Reset() {
	*x = TemplateInfo{}
	mi := &file_novitabox_v1_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateInfo) ProtoMessage() {}

func (x *TemplateInfo) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateInfo.ProtoReflect.Descriptor instead.
func (*TemplateInfo) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_types_proto_rawDescGZIP(), []int{2}
}

func (x *TemplateInfo) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *TemplateInfo) GetRootfsPath() string {
	if x != nil {
		return x.RootfsPath
	}
	return ""
}

func (x *TemplateInfo) GetMemfilePath() string {
	if x != nil {
		return x.MemfilePath
	}
	return ""
}

func (x *TemplateInfo) GetSnapfilePath() string {
	if x != nil {
		return x.SnapfilePath
	}
	return ""
}

func (x *TemplateInfo) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

func (x *TemplateInfo) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type ImageInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageId       string                 `protobuf:"bytes,1,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	RootfsPath    string                 `protobuf:"bytes,2,opt,name=rootfs_path,json=rootfsPath,proto3" json:"rootfs_path,omitempty"`
	CreatedAtUnix int64                  `protobuf:"varint,3,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,20,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageInfo) Reset() {
	*x = ImageInfo{}
	mi := &file_novitabox_v1_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageInfo) ProtoMessage() {}

func (x *ImageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageInfo.ProtoReflect.Descriptor instead.
func (*ImageInfo) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_types_proto_rawDescGZIP(), []int{3}
}

func (x *ImageInfo) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *ImageInfo) GetRootfsPath() string {
	if x != nil {
		return x.RootfsPath
	}
	return ""
}

func (x *ImageInfo) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

func (x *ImageInfo) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type MachineSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vcpu          uint32                 `protobuf:"varint,1,opt,name=vcpu,proto3" json:"vcpu,omitempty"`
	MemoryMb      uint32                 `protobuf:"varint,2,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	Hugepages     bool                   `protobuf:"varint,3,opt,name=hugepages,proto3" json:"hugepages,omitempty"`
	Gpu           uint32                 `protobuf:"varint,4,opt,name=gpu,proto3" json:"gpu,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineSpec) Reset() {
	*x = MachineSpec{}
	mi := &file_novitabox_v1_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineSpec) ProtoMessage() {}

func (x *MachineSpec) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineSpec.ProtoReflect.Descriptor instead.
func (*MachineSpec) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_types_proto_rawDescGZIP(), []int{4}
}

func (x *MachineSpec) GetVcpu() uint32 {
	if x != nil {
		return x.Vcpu
	}
	return 0
}

func (x *MachineSpec) GetMemoryMb() uint32 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *MachineSpec) GetHugepages() bool {
	if x != nil {
		return x.Hugepages
	}
	return false
}

func (x *MachineSpec) GetGpu() uint32 {
	if x != nil {
		return x.Gpu
	}
	return 0
}

type BalloonSpec struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	AmountMib             uint32                 `protobuf:"varint,1,opt,name=amount_mib,json=amountMib,proto3" json:"amount_mib,omitempty"`
	DeflateOnOom          bool                   `protobuf:"varint,2,opt,name=deflate_on_oom,json=deflateOnOom,proto3" json:"deflate_on_oom,omitempty"`
	StatsPollingIntervalS uint32                 `protobuf:"varint,3,opt,name=stats_polling_interval_s,json=statsPollingIntervalS,proto3" json:"stats_polling_interval_s,omitempty"`
	FreePageHinting       bool                   `protobuf:"varint,4,opt,name=free_page_hinting,json=freePageHinting,proto3" json:"free_page_hinting,omitempty"`
	FreePageReporting     bool                   `protobuf:"varint,5,opt,name=free_page_reporting,json=freePageReporting,proto3" json:"free_page_reporting,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *BalloonSpec) Reset() {
	*x = BalloonSpec{}
	mi := &file_novitabox_v1_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalloonSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalloonSpec) ProtoMessage() {}

func (x *BalloonSpec) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalloonSpec.ProtoReflect.Descriptor instead.
func (*BalloonSpec) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_types_proto_rawDescGZIP(), []int{5}
}

func (x *BalloonSpec) GetAmountMib() uint32 {
	if x != nil {
		return x.AmountMib
	}
	return 0
}

func (x *BalloonSpec) GetDeflateOnOom() bool {
	if x != nil {
		return x.DeflateOnOom
	}
	return false
}

func (x *BalloonSpec) GetStatsPollingIntervalS() uint32 {
	if x != nil {
		return x.StatsPollingIntervalS
	}
	return 0
}

func (x *BalloonSpec) GetFreePageHinting() bool {
	if x != nil {
		return x.FreePageHinting
	}
	return false
}

func (x *BalloonSpec) GetFreePageReporting() bool {
	if x != nil {
		return x.FreePageReporting
	}
	return false
}

type BalloonConfig struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	AmountMib             uint32                 `protobuf:"varint,1,opt,name=amount_mib,json=amountMib,proto3" json:"amount_mib,omitempty"`
	DeflateOnOom          bool                   `protobuf:"varint,2,opt,name=deflate_on_oom,json=deflateOnOom,proto3" json:"deflate_on_oom,omitempty"`
	StatsPollingIntervalS uint32                 `protobuf:"varint,3,opt,name=stats_polling_interval_s,json=statsPollingIntervalS,proto3" json:"stats_polling_interval_s,omitempty"`
	FreePageHinting       bool                   `protobuf:"varint,4,opt,name=free_page_hinting,json=freePageHinting,proto3" json:"free_page_hinting,omitempty"`
	FreePageReporting     bool                   `protobuf:"varint,5,opt,name=free_page_reporting,json=freePageReporting,proto3" json:"free_page_reporting,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *BalloonConfig) Reset() {
	*x = BalloonConfig{}
	mi := &file_novitabox_v1_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalloonConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalloonConfig) ProtoMessage() {}

func (x *BalloonConfig) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalloonConfig.ProtoReflect.Descriptor instead.
func (*BalloonConfig) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_types_proto_rawDescGZIP(), []int{6}
}

func (x *BalloonConfig) GetAmountMib() uint32 {
	if x != nil {
		return x.AmountMib
	}
	return 0
}

func (x *BalloonConfig) GetDeflateOnOom() bool {
	if x != nil {
		return x.DeflateOnOom
	}
	return false
}

func (x *BalloonConfig) GetStatsPollingIntervalS() uint32 {
	if x != nil {
		return x.StatsPollingIntervalS
	}
	return 0
}

func (x *BalloonConfig) GetFreePageHinting() bool {
	if x != nil {
		return x.FreePageHinting
	}
	return false
}

func (x *BalloonConfig) GetFreePageReporting() bool {
	if x != nil {
		return x.FreePageReporting
	}
	return false
}

type BalloonStats struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TargetMib          uint32                 `protobuf:"varint,1,opt,name=target_mib,json=targetMib,proto3" json:"target_mib,omitempty"`
	ActualMib          uint32                 `protobuf:"varint,2,opt,name=actual_mib,json=actualMib,proto3" json:"actual_mib,omitempty"`
	SwapIn             uint64                 `protobuf:"varint,3,opt,name=swap_in,json=swapIn,proto3" json:"swap_in,omitempty"`
	SwapOut            uint64                 `protobuf:"varint,4,opt,name=swap_out,json=swapOut,proto3" json:"swap_out,omitempty"`
	MajorFaults        uint64                 `protobuf:"varint,5,opt,name=major_faults,json=majorFaults,proto3" json:"major_faults,omitempty"`
	MinorFaults        uint64                 `protobuf:"varint,6,opt,name=minor_faults,json=minorFaults,proto3" json:"minor_faults,omitempty"`
	FreeMemory         uint64                 `protobuf:"varint,7,opt,name=free_memory,json=freeMemory,proto3" json:"free_memory,omitempty"`
	TotalMemory        uint64                 `protobuf:"varint,8,opt,name=total_memory,json=totalMemory,proto3" json:"total_memory,omitempty"`
	AvailableMemory    uint64                 `protobuf:"varint,9,opt,name=available_memory,json=availableMemory,proto3" json:"available_memory,omitempty"`
	DiskCaches         uint64                 `protobuf:"varint,10,opt,name=disk_caches,json=diskCaches,proto3" json:"disk_caches,omitempty"`
	HugetlbAllocations uint64                 `protobuf:"varint,11,opt,name=hugetlb_allocations,json=hugetlbAllocations,proto3" json:"hugetlb_allocations,omitempty"`
	HugetlbFailures    uint64                 `protobuf:"varint,12,opt,name=hugetlb_failures,json=hugetlbFailures,proto3" json:"hugetlb_failures,omitempty"`
	SharedMemory       uint64                 `protobuf:"varint,13,opt,name=shared_memory,json=sharedMemory,proto3" json:"shared_memory,omitempty"`
	UnevictableMemory  uint64                 `protobuf:"varint,14,opt,name=unevictable_memory,json=unevictableMemory,proto3" json:"unevictable_memory,omitempty"`
	OomKill            uint64                 `protobuf:"varint,15,opt,name=oom_kill,json=oomKill,proto3" json:"oom_kill,omitempty"`
	AllocStall         uint64                 `protobuf:"varint,16,opt,name=alloc_stall,json=allocStall,proto3" json:"alloc_stall,omitempty"`
	AsyncScan          uint64                 `protobuf:"varint,17,opt,name=async_scan,json=asyncScan,proto3" json:"async_scan,omitempty"`
	DirectScan         uint64                 `protobuf:"varint,18,opt,name=direct_scan,json=directScan,proto3" json:"direct_scan,omitempty"`
	AsyncReclaim       uint64                 `protobuf:"varint,19,opt,name=async_reclaim,json=asyncReclaim,proto3" json:"async_reclaim,omitempty"`
	DirectReclaim      uint64                 `protobuf:"varint,20,opt,name=direct_reclaim,json=directReclaim,proto3" json:"direct_reclaim,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *BalloonStats) Reset() {
	*x = BalloonStats{}
	mi := &file_novitabox_v1_types_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalloonStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalloonStats) ProtoMessage() {}

func (x *BalloonStats) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_types_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalloonStats.ProtoReflect.Descriptor instead.
func (*BalloonStats) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_types_proto_rawDescGZIP(), []int{7}
}

func (x *BalloonStats) GetTargetMib() uint32 {
	if x != nil {
		return x.TargetMib
	}
	return 0
}

func (x *BalloonStats) GetActualMib() uint32 {
	if x != nil {
		return x.ActualMib
	}
	return 0
}

func (x *BalloonStats) GetSwapIn() uint64 {
	if x != nil {
		return x.SwapIn
	}
	return 0
}

func (x *BalloonStats) GetSwapOut() uint64 {
	if x != nil {
		return x.SwapOut
	}
	return 0
}

func (x *BalloonStats) GetMajorFaults() uint64 {
	if x != nil {
		return x.MajorFaults
	}
	return 0
}

func (x *BalloonStats) GetMinorFaults() uint64 {
	if x != nil {
		return x.MinorFaults
	}
	return 0
}

func (x *BalloonStats) GetFreeMemory() uint64 {
	if x != nil {
		return x.FreeMemory
	}
	return 0
}

func (x *BalloonStats) GetTotalMemory() uint64 {
	if x != nil {
		return x.TotalMemory
	}
	return 0
}

func (x *BalloonStats) GetAvailableMemory() uint64 {
	if x != nil {
		return x.AvailableMemory
	}
	return 0
}

func (x *BalloonStats) GetDiskCaches() uint64 {
	if x != nil {
		return x.DiskCaches
	}
	return 0
}

func (x *BalloonStats) GetHugetlbAllocations() uint64 {
	if x != nil {
		return x.HugetlbAllocations
	}
	return 0
}

func (x *BalloonStats) GetHugetlbFailures() uint64 {
	if x != nil {
		return x.HugetlbFailures
	}
	return 0
}

func (x *BalloonStats) GetSharedMemory() uint64 {
	if x != nil {
		return x.SharedMemory
	}
	return 0
}

func (x *BalloonStats) GetUnevictableMemory() uint64 {
	if x != nil {
		return x.UnevictableMemory
	}
	return 0
}

func (x *BalloonStats) GetOomKill() uint64 {
	if x != nil {
		return x.OomKill
	}
	return 0
}

func (x *BalloonStats) GetAllocStall() uint64 {
	if x != nil {
		return x.AllocStall
	}
	return 0
}

func (x *BalloonStats) GetAsyncScan() uint64 {
	if x != nil {
		return x.AsyncScan
	}
	return 0
}

func (x *BalloonStats) GetDirectScan() uint64 {
	if x != nil {
		return x.DirectScan
	}
	return 0
}

func (x *BalloonStats) GetAsyncReclaim() uint64 {
	if x != nil {
		return x.AsyncReclaim
	}
	return 0
}

func (x *BalloonStats) GetDirectReclaim() uint64 {
	if x != nil {
		return x.DirectReclaim
	}
	return 0
}

type BalloonHintingStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	HostCmd       uint32                 `protobuf:"varint,3,opt,name=host_cmd,json=hostCmd,proto3" json:"host_cmd,omitempty"`
	GuestCmd      *uint32                `protobuf:"varint,4,opt,name=guest_cmd,json=guestCmd,proto3,oneof" json:"guest_cmd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BalloonHintingStatus) Reset() {
	*x = BalloonHintingStatus{}
	mi := &file_novitabox_v1_types_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalloonHintingStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalloonHintingStatus) ProtoMessage() {}

func (x *BalloonHintingStatus) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_types_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalloonHintingStatus.ProtoReflect.Descriptor instead.
func (*BalloonHintingStatus) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_types_proto_rawDescGZIP(), []int{8}
}

func (x *BalloonHintingStatus) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *BalloonHintingStatus) GetHostCmd() uint32 {
	if x != nil {
		return x.HostCmd
	}
	return 0
}

func (x *BalloonHintingStatus) GetGuestCmd() uint32 {
	if x != nil && x.GuestCmd != nil {
		return *x.GuestCmd
	}
	return 0
}

type KernelSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KernelPath    string                 `protobuf:"bytes,1,opt,name=kernel_path,json=kernelPath,proto3" json:"kernel_path,omitempty"`
	InitPath      string                 `protobuf:"bytes,2,opt,name=init_path,json=initPath,proto3" json:"init_path,omitempty"`
	KernelArgs    []string               `protobuf:"bytes,3,rep,name=kernel_args,json=kernelArgs,proto3" json:"kernel_args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KernelSpec) Reset() {
	*x = KernelSpec{}
	mi := &file_novitabox_v1_types_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KernelSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KernelSpec) ProtoMessage() {}

func (x *KernelSpec) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_types_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KernelSpec.ProtoReflect.Descriptor instead.
func (*KernelSpec) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_types_proto_rawDescGZIP(), []int{9}
}

func (x *KernelSpec) GetKernelPath() string {
	if x != nil {
		return x.KernelPath
	}
	return ""
}

func (x *KernelSpec) GetInitPath() string {
	if x != nil {
		return x.InitPath
	}
	return ""
}

func (x *KernelSpec) GetKernelArgs() []string {
	if x != nil {
		return x.KernelArgs
	}
	return nil
}

type RootfsSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Readonly      bool                   `protobuf:"varint,2,opt,name=readonly,proto3" json:"readonly,omitempty"`
	Format        string                 `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RootfsSpec) Reset() {
	*x = RootfsSpec{}
	mi := &file_novitabox_v1_types_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RootfsSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RootfsSpec) ProtoMessage() {}

func (x *RootfsSpec) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_types_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RootfsSpec.ProtoReflect.Descriptor instead.
func (*RootfsSpec) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_types_proto_rawDescGZIP(), []int{10}
}

func (x *RootfsSpec) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RootfsSpec) GetReadonly() bool {
	if x != nil {
		return x.Readonly
	}
	return false
}

func (x *RootfsSpec) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

type DriveSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriveId       string                 `protobuf:"bytes,1,opt,name=drive_id,json=driveId,proto3" json:"drive_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Readonly      bool                   `protobuf:"varint,3,opt,name=readonly,proto3" json:"readonly,omitempty"`
	Format        string                 `protobuf:"bytes,4,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriveSpec) Reset() {
	*x = DriveSpec{}
	mi := &file_novitabox_v1_types_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriveSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriveSpec) ProtoMessage() {}

func (x *DriveSpec) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_types_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriveSpec.ProtoReflect.Descriptor instead.
func (*DriveSpec) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_types_proto_rawDescGZIP(), []int{11}
}

func (x *DriveSpec) GetDriveId() string {
	if x != nil {
		return x.DriveId
	}
	return ""
}

func (x *DriveSpec) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DriveSpec) GetReadonly() bool {
	if x != nil {
		return x.Readonly
	}
	return false
}

func (x *DriveSpec) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

type SnapshotSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemfilePath   string                 `protobuf:"bytes,1,opt,name=memfile_path,json=memfilePath,proto3" json:"memfile_path,omitempty"`
	SnapfilePath  string                 `protobuf:"bytes,2,opt,name=snapfile_path,json=snapfilePath,proto3" json:"snapfile_path,omitempty"`
	SnapshotType  string                 `protobuf:"bytes,3,opt,name=snapshot_type,json=snapshotType,proto3" json:"snapshot_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotSpec) Reset() {
	*x = SnapshotSpec{}
	mi := &file_novitabox_v1_types_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotSpec) ProtoMessage() {}

func (x *SnapshotSpec) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_types_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotSpec.ProtoReflect.Descriptor instead.
func (*SnapshotSpec) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_types_proto_rawDescGZIP(), []int{12}
}

func (x *SnapshotSpec) GetMemfilePath() string {
	if x != nil {
		return x.MemfilePath
	}
	return ""
}

func (x *SnapshotSpec) GetSnapfilePath() string {
	if x != nil {
		return x.SnapfilePath
	}
	return ""
}

func (x *SnapshotSpec) GetSnapshotType() string {
	if x != nil {
		return x.SnapshotType
	}
	return ""
}

type NetworkSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NamespaceName string                 `protobuf:"bytes,1,opt,name=namespace_name,json=namespaceName,proto3" json:"namespace_name,omitempty"`
	TapName       string                 `protobuf:"bytes,2,opt,name=tap_name,json=tapName,proto3" json:"tap_name,omitempty"`
	GuestIp       string                 `protobuf:"bytes,3,opt,name=guest_ip,json=guestIp,proto3" json:"guest_ip,omitempty"`
	GatewayIp     string                 `protobuf:"bytes,4,opt,name=gateway_ip,json=gatewayIp,proto3" json:"gateway_ip,omitempty"`
	HostAccessIp  string                 `protobuf:"bytes,5,opt,name=host_access_ip,json=hostAccessIp,proto3" json:"host_access_ip,omitempty"`
	Mac           string                 `protobuf:"bytes,6,opt,name=mac,proto3" json:"mac,omitempty"`
	Slot          uint32                 `protobuf:"varint,7,opt,name=slot,proto3" json:"slot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkSpec) Reset() {
	*x = NetworkSpec{}
	mi := &file_novitabox_v1_types_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkSpec) ProtoMessage() {}

func (x *NetworkSpec) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_types_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkSpec.ProtoReflect.Descriptor instead.
func (*NetworkSpec) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_types_proto_rawDescGZIP(), []int{13}
}

func (x *NetworkSpec) GetNamespaceName() string {
	if x != nil {
		return x.NamespaceName
	}
	return ""
}

func (x *NetworkSpec) GetTapName() string {
	if x != nil {
		return x.TapName
	}
	return ""
}

func (x *NetworkSpec) GetGuestIp() string {
	if x != nil {
		return x.GuestIp
	}
	return ""
}

func (x *NetworkSpec) GetGatewayIp() string {
	if x != nil {
		return x.GatewayIp
	}
	return ""
}

func (x *NetworkSpec) GetHostAccessIp() string {
	if x != nil {
		return x.HostAccessIp
	}
	return ""
}

func (x *NetworkSpec) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *NetworkSpec) GetSlot() uint32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

type AgentSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Protocol      string                 `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Port          uint32                 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Token         string                 `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentSpec) Reset() {
	*x = AgentSpec{}
	mi := &file_novitabox_v1_types_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentSpec) ProtoMessage() {}

func (x *AgentSpec) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_types_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentSpec.ProtoReflect.Descriptor instead.
func (*AgentSpec) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_types_proto_rawDescGZIP(), []int{14}
}

func (x *AgentSpec) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AgentSpec) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *AgentSpec) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *AgentSpec) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type JailerSpec struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Enabled        bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	ChrootDir      string                 `protobuf:"bytes,2,opt,name=chroot_dir,json=chrootDir,proto3" json:"chroot_dir,omitempty"`
	Uid            string                 `protobuf:"bytes,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid            string                 `protobuf:"bytes,4,opt,name=gid,proto3" json:"gid,omitempty"`
	CgroupPath     string                 `protobuf:"bytes,5,opt,name=cgroup_path,json=cgroupPath,proto3" json:"cgroup_path,omitempty"`
	SeccompProfile string                 `protobuf:"bytes,6,opt,name=seccomp_profile,json=seccompProfile,proto3" json:"seccomp_profile,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *JailerSpec) Reset() {
	*x = JailerSpec{}
	mi := &file_novitabox_v1_types_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JailerSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JailerSpec) ProtoMessage() {}

func (x *JailerSpec) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_types_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JailerSpec.ProtoReflect.Descriptor instead.
func (*JailerSpec) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_types_proto_rawDescGZIP(), []int{15}
}

func (x *JailerSpec) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *JailerSpec) GetChrootDir() string {
	if x != nil {
		return x.ChrootDir
	}
	return ""
}

func (x *JailerSpec) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *JailerSpec) GetGid() string {
	if x != nil {
		return x.Gid
	}
	return ""
}

func (x *JailerSpec) GetCgroupPath() string {
	if x != nil {
		return x.CgroupPath
	}
	return ""
}

func (x *JailerSpec) GetSeccompProfile() string {
	if x != nil {
		return x.SeccompProfile
	}
	return ""
}

type RuntimeSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	RuntimeType   RuntimeType            `protobuf:"varint,2,opt,name=runtime_type,json=runtimeType,proto3,enum=novitabox.v1.RuntimeType" json:"runtime_type,omitempty"`
	Machine       *MachineSpec           `protobuf:"bytes,3,opt,name=machine,proto3" json:"machine,omitempty"`
	Kernel        *KernelSpec            `protobuf:"bytes,4,opt,name=kernel,proto3" json:"kernel,omitempty"`
	Rootfs        *RootfsSpec            `protobuf:"bytes,5,opt,name=rootfs,proto3" json:"rootfs,omitempty"`
	Snapshot      *SnapshotSpec          `protobuf:"bytes,6,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	Network       *NetworkSpec           `protobuf:"bytes,7,opt,name=network,proto3" json:"network,omitempty"`
	Agent         *AgentSpec             `protobuf:"bytes,8,opt,name=agent,proto3" json:"agent,omitempty"`
	Jailer        *JailerSpec            `protobuf:"bytes,9,opt,name=jailer,proto3" json:"jailer,omitempty"`
	ExtraDrives   []*DriveSpec           `protobuf:"bytes,10,rep,name=extra_drives,json=extraDrives,proto3" json:"extra_drives,omitempty"`
	Balloon       *BalloonSpec           `protobuf:"bytes,11,opt,name=balloon,proto3" json:"balloon,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,20,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Annotations   map[string]string      `protobuf:"bytes,21,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeSpec) Reset() {
	*x = RuntimeSpec{}
	mi := &file_novitabox_v1_types_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeSpec) ProtoMessage() {}

func (x *RuntimeSpec) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_types_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeSpec.ProtoReflect.Descriptor instead.
func (*RuntimeSpec) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_types_proto_rawDescGZIP(), []int{16}
}

func (x *RuntimeSpec) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *RuntimeSpec) GetRuntimeType() RuntimeType {
	if x != nil {
		return x.RuntimeType
	}
	return RuntimeType_RUNTIME_TYPE_UNSPECIFIED
}

func (x *RuntimeSpec) GetMachine() *MachineSpec {
	if x != nil {
		return x.Machine
	}
	return nil
}

func (x *RuntimeSpec) GetKernel() *KernelSpec {
	if x != nil {
		return x.Kernel
	}
	return nil
}

func (x *RuntimeSpec) GetRootfs() *RootfsSpec {
	if x != nil {
		return x.Rootfs
	}
	return nil
}

func (x *RuntimeSpec) GetSnapshot() *SnapshotSpec {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *RuntimeSpec) GetNetwork() *NetworkSpec {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *RuntimeSpec) GetAgent() *AgentSpec {
	if x != nil {
		return x.Agent
	}
	return nil
}

func (x *RuntimeSpec) GetJailer() *JailerSpec {
	if x != nil {
		return x.Jailer
	}
	return nil
}

func (x *RuntimeSpec) GetExtraDrives() []*DriveSpec {
	if x != nil {
		return x.ExtraDrives
	}
	return nil
}

func (x *RuntimeSpec) GetBalloon() *BalloonSpec {
	if x != nil {
		return x.Balloon
	}
	return nil
}

func (x *RuntimeSpec) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *RuntimeSpec) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

type RuntimeInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SandboxId         string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	RuntimeType       RuntimeType            `protobuf:"varint,2,opt,name=runtime_type,json=runtimeType,proto3,enum=novitabox.v1.RuntimeType" json:"runtime_type,omitempty"`
	State             RuntimeState           `protobuf:"varint,3,opt,name=state,proto3,enum=novitabox.v1.RuntimeState" json:"state,omitempty"`
	Pid               int64                  `protobuf:"varint,4,opt,name=pid,proto3" json:"pid,omitempty"`
	ShimSocketPath    string                 `protobuf:"bytes,5,opt,name=shim_socket_path,json=shimSocketPath,proto3" json:"shim_socket_path,omitempty"`
	RuntimeSocketPath string                 `protobuf:"bytes,6,opt,name=runtime_socket_path,json=runtimeSocketPath,proto3" json:"runtime_socket_path,omitempty"`
	ErrorMessage      string                 `protobuf:"bytes,7,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RuntimeInfo) Reset() {
	*x = RuntimeInfo{}
	mi := &file_novitabox_v1_types_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeInfo) ProtoMessage() {}

func (x *RuntimeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_types_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeInfo.ProtoReflect.Descriptor instead.
func (*RuntimeInfo) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_types_proto_rawDescGZIP(), []int{17}
}

func (x *RuntimeInfo) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *RuntimeInfo) GetRuntimeType() RuntimeType {
	if x != nil {
		return x.RuntimeType
	}
	return RuntimeType_RUNTIME_TYPE_UNSPECIFIED
}

func (x *RuntimeInfo) GetState() RuntimeState {
	if x != nil {
		return x.State
	}
	return RuntimeState_RUNTIME_STATE_UNSPECIFIED
}

func (x *RuntimeInfo) GetPid() int64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *RuntimeInfo) GetShimSocketPath() string {
	if x != nil {
		return x.ShimSocketPath
	}
	return ""
}

func (x *RuntimeInfo) GetRuntimeSocketPath() string {
	if x != nil {
		return x.RuntimeSocketPath
	}
	return ""
}

func (x *RuntimeInfo) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type RuntimeCapabilities struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	StartFromImage    bool                   `protobuf:"varint,1,opt,name=start_from_image,json=startFromImage,proto3" json:"start_from_image,omitempty"`
	StartFromTemplate bool                   `protobuf:"varint,2,opt,name=start_from_template,json=startFromTemplate,proto3" json:"start_from_template,omitempty"`
	StartFromSnapshot bool                   `protobuf:"varint,3,opt,name=start_from_snapshot,json=startFromSnapshot,proto3" json:"start_from_snapshot,omitempty"`
	Pause             bool                   `protobuf:"varint,10,opt,name=pause,proto3" json:"pause,omitempty"`
	Resume            bool                   `protobuf:"varint,11,opt,name=resume,proto3" json:"resume,omitempty"`
	FullSnapshot      bool                   `protobuf:"varint,12,opt,name=full_snapshot,json=fullSnapshot,proto3" json:"full_snapshot,omitempty"`
	DiffSnapshot      bool                   `protobuf:"varint,13,opt,name=diff_snapshot,json=diffSnapshot,proto3" json:"diff_snapshot,omitempty"`
	Gpu               bool                   `protobuf:"varint,20,opt,name=gpu,proto3" json:"gpu,omitempty"`
	Vsock             bool                   `protobuf:"varint,21,opt,name=vsock,proto3" json:"vsock,omitempty"`
	TapNetwork        bool                   `protobuf:"varint,22,opt,name=tap_network,json=tapNetwork,proto3" json:"tap_network,omitempty"`
	HotplugDisk       bool                   `protobuf:"varint,23,opt,name=hotplug_disk,json=hotplugDisk,proto3" json:"hotplug_disk,omitempty"`
	HotplugNetwork    bool                   `protobuf:"varint,24,opt,name=hotplug_network,json=hotplugNetwork,proto3" json:"hotplug_network,omitempty"`
	LiveResizeCpu     bool                   `protobuf:"varint,25,opt,name=live_resize_cpu,json=liveResizeCpu,proto3" json:"live_resize_cpu,omitempty"`
	LiveResizeMemory  bool                   `protobuf:"varint,26,opt,name=live_resize_memory,json=liveResizeMemory,proto3" json:"live_resize_memory,omitempty"`
	Balloon           bool                   `protobuf:"varint,27,opt,name=balloon,proto3" json:"balloon,omitempty"`
	GracefulShutdown  bool                   `protobuf:"varint,30,opt,name=graceful_shutdown,json=gracefulShutdown,proto3" json:"graceful_shutdown,omitempty"`
	SerialConsole     bool                   `protobuf:"varint,31,opt,name=serial_console,json=serialConsole,proto3" json:"serial_console,omitempty"`
	Jailer            bool                   `protobuf:"varint,32,opt,name=jailer,proto3" json:"jailer,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RuntimeCapabilities) Reset() {
	*x = RuntimeCapabilities{}
	mi := &file_novitabox_v1_types_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeCapabilities) ProtoMessage() {}

func (x *RuntimeCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_novitabox_v1_types_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeCapabilities.ProtoReflect.Descriptor instead.
func (*RuntimeCapabilities) Descriptor() ([]byte, []int) {
	return file_novitabox_v1_types_proto_rawDescGZIP(), []int{18}
}

func (x *RuntimeCapabilities) GetStartFromImage() bool {
	if x != nil {
		return x.StartFromImage
	}
	return false
}

func (x *RuntimeCapabilities) GetStartFromTemplate() bool {
	if x != nil {
		return x.StartFromTemplate
	}
	return false
}

func (x *RuntimeCapabilities) GetStartFromSnapshot() bool {
	if x != nil {
		return x.StartFromSnapshot
	}
	return false
}

func (x *RuntimeCapabilities) GetPause() bool {
	if x != nil {
		return x.Pause
	}
	return false
}

func (x *RuntimeCapabilities) GetResume() bool {
	if x != nil {
		return x.Resume
	}
	return false
}

func (x *RuntimeCapabilities) GetFullSnapshot() bool {
	if x != nil {
		return x.FullSnapshot
	}
	return false
}

func (x *RuntimeCapabilities) GetDiffSnapshot() bool {
	if x != nil {
		return x.DiffSnapshot
	}
	return false
}

func (x *RuntimeCapabilities) GetGpu() bool {
	if x != nil {
		return x.Gpu
	}
	return false
}

func (x *RuntimeCapabilities) GetVsock() bool {
	if x != nil {
		return x.Vsock
	}
	return false
}

func (x *RuntimeCapabilities) GetTapNetwork() bool {
	if x != nil {
		return x.TapNetwork
	}
	return false
}

func (x *RuntimeCapabilities) GetHotplugDisk() bool {
	if x != nil {
		return x.HotplugDisk
	}
	return false
}

func (x *RuntimeCapabilities) GetHotplugNetwork() bool {
	if x != nil {
		return x.HotplugNetwork
	}
	return false
}

func (x *RuntimeCapabilities) GetLiveResizeCpu() bool {
	if x != nil {
		return x.LiveResizeCpu
	}
	return false
}

func (x *RuntimeCapabilities) GetLiveResizeMemory() bool {
	if x != nil {
		return x.LiveResizeMemory
	}
	return false
}

func (x *RuntimeCapabilities) GetBalloon() bool {
	if x != nil {
		return x.Balloon
	}
	return false
}

func (x *RuntimeCapabilities) GetGracefulShutdown() bool {
	if x != nil {
		return x.GracefulShutdown
	}
	return false
}

func (x *RuntimeCapabilities) GetSerialConsole() bool {
	if x != nil {
		return x.SerialConsole
	}
	return false
}

func (x *RuntimeCapabilities) GetJailer() bool {
	if x != nil {
		return x.Jailer
	}
	return false
}

var File_novitabox_v1_types_proto protoreflect.FileDescriptor

const file_novitabox_v1_types_proto_rawDesc = "" +
	"\n" +
	"\x18novitabox/v1/types.proto\x12\fnovitabox.v1\"\xd1\x04\n" +
	"\vSandboxInfo\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x120\n" +
	"\x05state\x18\x02 \x01(\x0e2\x1a.novitabox.v1.SandboxStateR\x05state\x12<\n" +
	"\fruntime_type\x18\x03 \x01(\x0e2\x19.novitabox.v1.RuntimeTypeR\vruntimeType\x12\x1f\n" +
	"\vtemplate_id\x18\x04 \x01(\tR\n" +
	"templateId\x12\x19\n" +
	"\bimage_id\x18\x05 \x01(\tR\aimageId\x12\x1f\n" +
	"\vsnapshot_id\x18\x06 \x01(\tR\n" +
	"snapshotId\x12&\n" +
	"\x0fcreated_at_unix\x18\a \x01(\x03R\rcreatedAtUnix\x12&\n" +
	"\x0fupdated_at_unix\x18\b \x01(\x03R\rupdatedAtUnix\x12=\n" +
	"\x06labels\x18\x14 \x03(\v2%.novitabox.v1.SandboxInfo.LabelsEntryR\x06labels\x12L\n" +
	"\vannotations\x18\x15 \x03(\v2*.novitabox.v1.SandboxInfo.AnnotationsEntryR\vannotations\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xda\x02\n" +
	"\fSnapshotInfo\x12\x1f\n" +
	"\vsnapshot_id\x18\x01 \x01(\tR\n" +
	"snapshotId\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x02 \x01(\tR\tsandboxId\x12\x1f\n" +
	"\vrootfs_path\x18\x03 \x01(\tR\n" +
	"rootfsPath\x12!\n" +
	"\fmemfile_path\x18\x04 \x01(\tR\vmemfilePath\x12#\n" +
	"\rsnapfile_path\x18\x05 \x01(\tR\fsnapfilePath\x12&\n" +
	"\x0fcreated_at_unix\x18\x06 \x01(\x03R\rcreatedAtUnix\x12>\n" +
	"\x06labels\x18\x14 \x03(\v2&.novitabox.v1.SnapshotInfo.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbb\x02\n" +
	"\fTemplateInfo\x12\x1f\n" +
	"\vtemplate_id\x18\x01 \x01(\tR\n" +
	"templateId\x12\x1f\n" +
	"\vrootfs_path\x18\x02 \x01(\tR\n" +
	"rootfsPath\x12!\n" +
	"\fmemfile_path\x18\x03 \x01(\tR\vmemfilePath\x12#\n" +
	"\rsnapfile_path\x18\x04 \x01(\tR\fsnapfilePath\x12&\n" +
	"\x0fcreated_at_unix\x18\x05 \x01(\x03R\rcreatedAtUnix\x12>\n" +
	"\x06labels\x18\x14 \x03(\v2&.novitabox.v1.TemplateInfo.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe7\x01\n" +
	"\tImageInfo\x12\x19\n" +
	"\bimage_id\x18\x01 \x01(\tR\aimageId\x12\x1f\n" +
	"\vrootfs_path\x18\x02 \x01(\tR\n" +
	"rootfsPath\x12&\n" +
	"\x0fcreated_at_unix\x18\x03 \x01(\x03R\rcreatedAtUnix\x12;\n" +
	"\x06labels\x18\x14 \x03(\v2#.novitabox.v1.ImageInfo.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"n\n" +
	"\vMachineSpec\x12\x12\n" +
	"\x04vcpu\x18\x01 \x01(\rR\x04vcpu\x12\x1b\n" +
	"\tmemory_mb\x18\x02 \x01(\rR\bmemoryMb\x12\x1c\n" +
	"\thugepages\x18\x03 \x01(\bR\thugepages\x12\x10\n" +
	"\x03gpu\x18\x04 \x01(\rR\x03gpu\"\xe7\x01\n" +
	"\vBalloonSpec\x12\x1d\n" +
	"\n" +
	"amount_mib\x18\x01 \x01(\rR\tamountMib\x12$\n" +
	"\x0edeflate_on_oom\x18\x02 \x01(\bR\fdeflateOnOom\x127\n" +
	"\x18stats_polling_interval_s\x18\x03 \x01(\rR\x15statsPollingIntervalS\x12*\n" +
	"\x11free_page_hinting\x18\x04 \x01(\bR\x0ffreePageHinting\x12.\n" +
	"\x13free_page_reporting\x18\x05 \x01(\bR\x11freePageReporting\"\xe9\x01\n" +
	"\rBalloonConfig\x12\x1d\n" +
	"\n" +
	"amount_mib\x18\x01 \x01(\rR\tamountMib\x12$\n" +
	"\x0edeflate_on_oom\x18\x02 \x01(\bR\fdeflateOnOom\x127\n" +
	"\x18stats_polling_interval_s\x18\x03 \x01(\rR\x15statsPollingIntervalS\x12*\n" +
	"\x11free_page_hinting\x18\x04 \x01(\bR\x0ffreePageHinting\x12.\n" +
	"\x13free_page_reporting\x18\x05 \x01(\bR\x11freePageReporting\"\xce\x05\n" +
	"\fBalloonStats\x12\x1d\n" +
	"\n" +
	"target_mib\x18\x01 \x01(\rR\ttargetMib\x12\x1d\n" +
	"\n" +
	"actual_mib\x18\x02 \x01(\rR\tactualMib\x12\x17\n" +
	"\aswap_in\x18\x03 \x01(\x04R\x06swapIn\x12\x19\n" +
	"\bswap_out\x18\x04 \x01(\x04R\aswapOut\x12!\n" +
	"\fmajor_faults\x18\x05 \x01(\x04R\vmajorFaults\x12!\n" +
	"\fminor_faults\x18\x06 \x01(\x04R\vminorFaults\x12\x1f\n" +
	"\vfree_memory\x18\a \x01(\x04R\n" +
	"freeMemory\x12!\n" +
	"\ftotal_memory\x18\b \x01(\x04R\vtotalMemory\x12)\n" +
	"\x10available_memory\x18\t \x01(\x04R\x0favailableMemory\x12\x1f\n" +
	"\vdisk_caches\x18\n" +
	" \x01(\x04R\n" +
	"diskCaches\x12/\n" +
	"\x13hugetlb_allocations\x18\v \x01(\x04R\x12hugetlbAllocations\x12)\n" +
	"\x10hugetlb_failures\x18\f \x01(\x04R\x0fhugetlbFailures\x12#\n" +
	"\rshared_memory\x18\r \x01(\x04R\fsharedMemory\x12-\n" +
	"\x12unevictable_memory\x18\x0e \x01(\x04R\x11unevictableMemory\x12\x19\n" +
	"\boom_kill\x18\x0f \x01(\x04R\aoomKill\x12\x1f\n" +
	"\valloc_stall\x18\x10 \x01(\x04R\n" +
	"allocStall\x12\x1d\n" +
	"\n" +
	"async_scan\x18\x11 \x01(\x04R\tasyncScan\x12\x1f\n" +
	"\vdirect_scan\x18\x12 \x01(\x04R\n" +
	"directScan\x12#\n" +
	"\rasync_reclaim\x18\x13 \x01(\x04R\fasyncReclaim\x12%\n" +
	"\x0edirect_reclaim\x18\x14 \x01(\x04R\rdirectReclaim\"\x89\x01\n" +
	"\x14BalloonHintingStatus\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12\x19\n" +
	"\bhost_cmd\x18\x03 \x01(\rR\ahostCmd\x12 \n" +
	"\tguest_cmd\x18\x04 \x01(\rH\x00R\bguestCmd\x88\x01\x01B\f\n" +
	"\n" +
	"_guest_cmdJ\x04\b\x02\x10\x03R\n" +
	"interval_s\"k\n" +
	"\n" +
	"KernelSpec\x12\x1f\n" +
	"\vkernel_path\x18\x01 \x01(\tR\n" +
	"kernelPath\x12\x1b\n" +
	"\tinit_path\x18\x02 \x01(\tR\binitPath\x12\x1f\n" +
	"\vkernel_args\x18\x03 \x03(\tR\n" +
	"kernelArgs\"T\n" +
	"\n" +
	"RootfsSpec\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1a\n" +
	"\breadonly\x18\x02 \x01(\bR\breadonly\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\"n\n" +
	"\tDriveSpec\x12\x19\n" +
	"\bdrive_id\x18\x01 \x01(\tR\adriveId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x1a\n" +
	"\breadonly\x18\x03 \x01(\bR\breadonly\x12\x16\n" +
	"\x06format\x18\x04 \x01(\tR\x06format\"{\n" +
	"\fSnapshotSpec\x12!\n" +
	"\fmemfile_path\x18\x01 \x01(\tR\vmemfilePath\x12#\n" +
	"\rsnapfile_path\x18\x02 \x01(\tR\fsnapfilePath\x12#\n" +
	"\rsnapshot_type\x18\x03 \x01(\tR\fsnapshotType\"\xd5\x01\n" +
	"\vNetworkSpec\x12%\n" +
	"\x0enamespace_name\x18\x01 \x01(\tR\rnamespaceName\x12\x19\n" +
	"\btap_name\x18\x02 \x01(\tR\atapName\x12\x19\n" +
	"\bguest_ip\x18\x03 \x01(\tR\aguestIp\x12\x1d\n" +
	"\n" +
	"gateway_ip\x18\x04 \x01(\tR\tgatewayIp\x12$\n" +
	"\x0ehost_access_ip\x18\x05 \x01(\tR\fhostAccessIp\x12\x10\n" +
	"\x03mac\x18\x06 \x01(\tR\x03mac\x12\x12\n" +
	"\x04slot\x18\a \x01(\rR\x04slot\"e\n" +
	"\tAgentSpec\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1a\n" +
	"\bprotocol\x18\x02 \x01(\tR\bprotocol\x12\x12\n" +
	"\x04port\x18\x03 \x01(\rR\x04port\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\"\xb3\x01\n" +
	"\n" +
	"JailerSpec\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1d\n" +
	"\n" +
	"chroot_dir\x18\x02 \x01(\tR\tchrootDir\x12\x10\n" +
	"\x03uid\x18\x03 \x01(\tR\x03uid\x12\x10\n" +
	"\x03gid\x18\x04 \x01(\tR\x03gid\x12\x1f\n" +
	"\vcgroup_path\x18\x05 \x01(\tR\n" +
	"cgroupPath\x12'\n" +
	"\x0fseccomp_profile\x18\x06 \x01(\tR\x0eseccompProfile\"\xca\x06\n" +
	"\vRuntimeSpec\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12<\n" +
	"\fruntime_type\x18\x02 \x01(\x0e2\x19.novitabox.v1.RuntimeTypeR\vruntimeType\x123\n" +
	"\amachine\x18\x03 \x01(\v2\x19.novitabox.v1.MachineSpecR\amachine\x120\n" +
	"\x06kernel\x18\x04 \x01(\v2\x18.novitabox.v1.KernelSpecR\x06kernel\x120\n" +
	"\x06rootfs\x18\x05 \x01(\v2\x18.novitabox.v1.RootfsSpecR\x06rootfs\x126\n" +
	"\bsnapshot\x18\x06 \x01(\v2\x1a.novitabox.v1.SnapshotSpecR\bsnapshot\x123\n" +
	"\anetwork\x18\a \x01(\v2\x19.novitabox.v1.NetworkSpecR\anetwork\x12-\n" +
	"\x05agent\x18\b \x01(\v2\x17.novitabox.v1.AgentSpecR\x05agent\x120\n" +
	"\x06jailer\x18\t \x01(\v2\x18.novitabox.v1.JailerSpecR\x06jailer\x12:\n" +
	"\fextra_drives\x18\n" +
	" \x03(\v2\x17.novitabox.v1.DriveSpecR\vextraDrives\x123\n" +
	"\aballoon\x18\v \x01(\v2\x19.novitabox.v1.BalloonSpecR\aballoon\x12=\n" +
	"\x06labels\x18\x14 \x03(\v2%.novitabox.v1.RuntimeSpec.LabelsEntryR\x06labels\x12L\n" +
	"\vannotations\x18\x15 \x03(\v2*.novitabox.v1.RuntimeSpec.AnnotationsEntryR\vannotations\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xad\x02\n" +
	"\vRuntimeInfo\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12<\n" +
	"\fruntime_type\x18\x02 \x01(\x0e2\x19.novitabox.v1.RuntimeTypeR\vruntimeType\x120\n" +
	"\x05state\x18\x03 \x01(\x0e2\x1a.novitabox.v1.RuntimeStateR\x05state\x12\x10\n" +
	"\x03pid\x18\x04 \x01(\x03R\x03pid\x12(\n" +
	"\x10shim_socket_path\x18\x05 \x01(\tR\x0eshimSocketPath\x12.\n" +
	"\x13runtime_socket_path\x18\x06 \x01(\tR\x11runtimeSocketPath\x12#\n" +
	"\rerror_message\x18\a \x01(\tR\ferrorMessage\"\x88\x05\n" +
	"\x13RuntimeCapabilities\x12(\n" +
	"\x10start_from_image\x18\x01 \x01(\bR\x0estartFromImage\x12.\n" +
	"\x13start_from_template\x18\x02 \x01(\bR\x11startFromTemplate\x12.\n" +
	"\x13start_from_snapshot\x18\x03 \x01(\bR\x11startFromSnapshot\x12\x14\n" +
	"\x05pause\x18\n" +
	" \x01(\bR\x05pause\x12\x16\n" +
	"\x06resume\x18\v \x01(\bR\x06resume\x12#\n" +
	"\rfull_snapshot\x18\f \x01(\bR\ffullSnapshot\x12#\n" +
	"\rdiff_snapshot\x18\r \x01(\bR\fdiffSnapshot\x12\x10\n" +
	"\x03gpu\x18\x14 \x01(\bR\x03gpu\x12\x14\n" +
	"\x05vsock\x18\x15 \x01(\bR\x05vsock\x12\x1f\n" +
	"\vtap_network\x18\x16 \x01(\bR\n" +
	"tapNetwork\x12!\n" +
	"\fhotplug_disk\x18\x17 \x01(\bR\vhotplugDisk\x12'\n" +
	"\x0fhotplug_network\x18\x18 \x01(\bR\x0ehotplugNetwork\x12&\n" +
	"\x0flive_resize_cpu\x18\x19 \x01(\bR\rliveResizeCpu\x12,\n" +
	"\x12live_resize_memory\x18\x1a \x01(\bR\x10liveResizeMemory\x12\x18\n" +
	"\aballoon\x18\x1b \x01(\bR\aballoon\x12+\n" +
	"\x11graceful_shutdown\x18\x1e \x01(\bR\x10gracefulShutdown\x12%\n" +
	"\x0eserial_console\x18\x1f \x01(\bR\rserialConsole\x12\x16\n" +
	"\x06jailer\x18  \x01(\bR\x06jailer*\x8f\x03\n" +
	"\fSandboxState\x12\x1d\n" +
	"\x19SANDBOX_STATE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16SANDBOX_STATE_CREATING\x10\x01\x12\x19\n" +
	"\x15SANDBOX_STATE_RUNNING\x10\x02\x12\x19\n" +
	"\x15SANDBOX_STATE_PAUSING\x10\x03\x12\x18\n" +
	"\x14SANDBOX_STATE_PAUSED\x10\x04\x12\x1a\n" +
	"\x16SANDBOX_STATE_RESUMING\x10\x05\x12\x1a\n" +
	"\x16SANDBOX_STATE_STOPPING\x10\x06\x12\x19\n" +
	"\x15SANDBOX_STATE_STOPPED\x10\a\x12\x1a\n" +
	"\x16SANDBOX_STATE_STARTING\x10\b\x12\x1b\n" +
	"\x17SANDBOX_STATE_REBOOTING\x10\t\x12\x19\n" +
	"\x15SANDBOX_STATE_KILLING\x10\n" +
	"\x12\x18\n" +
	"\x14SANDBOX_STATE_KILLED\x10\v\x12\x18\n" +
	"\x14SANDBOX_STATE_FAILED\x10\f\x12\x19\n" +
	"\x15SANDBOX_STATE_UNKNOWN\x10\r*\x88\x01\n" +
	"\vRuntimeType\x12\x1c\n" +
	"\x18RUNTIME_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18RUNTIME_TYPE_FIRECRACKER\x10\x01\x12!\n" +
	"\x1dRUNTIME_TYPE_CLOUD_HYPERVISOR\x10\x02\x12\x1a\n" +
	"\x16RUNTIME_TYPE_CONTAINER\x10\x03*\xe7\x01\n" +
	"\fRuntimeState\x12\x1d\n" +
	"\x19RUNTIME_STATE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15RUNTIME_STATE_CREATED\x10\x01\x12\x19\n" +
	"\x15RUNTIME_STATE_RUNNING\x10\x02\x12\x18\n" +
	"\x14RUNTIME_STATE_PAUSED\x10\x03\x12\x19\n" +
	"\x15RUNTIME_STATE_STOPPED\x10\x04\x12\x18\n" +
	"\x14RUNTIME_STATE_EXITED\x10\x05\x12\x18\n" +
	"\x14RUNTIME_STATE_FAILED\x10\x06\x12\x19\n" +
	"\x15RUNTIME_STATE_UNKNOWN\x10\aBFZDgithub.com/novitalabs/NovitaBox/internal/pb/novitabox/v1;novitaboxv1b\x06proto3"

var (
	file_novitabox_v1_types_proto_rawDescOnce sync.Once
	file_novitabox_v1_types_proto_rawDescData []byte
)

func file_novitabox_v1_types_proto_rawDescGZIP() []byte {
	file_novitabox_v1_types_proto_rawDescOnce.Do(func() {
		file_novitabox_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_novitabox_v1_types_proto_rawDesc), len(file_novitabox_v1_types_proto_rawDesc)))
	})
	return file_novitabox_v1_types_proto_rawDescData
}

var file_novitabox_v1_types_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_novitabox_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_novitabox_v1_types_proto_goTypes = []any{
	(SandboxState)(0),            // 0: novitabox.v1.SandboxState
	(RuntimeType)(0),             // 1: novitabox.v1.RuntimeType
	(RuntimeState)(0),            // 2: novitabox.v1.RuntimeState
	(*SandboxInfo)(nil),          // 3: novitabox.v1.SandboxInfo
	(*SnapshotInfo)(nil),         // 4: novitabox.v1.SnapshotInfo
	(*TemplateInfo)(nil),         // 5: novitabox.v1.TemplateInfo
	(*ImageInfo)(nil),            // 6: novitabox.v1.ImageInfo
	(*MachineSpec)(nil),          // 7: novitabox.v1.MachineSpec
	(*BalloonSpec)(nil),          // 8: novitabox.v1.BalloonSpec
	(*BalloonConfig)(nil),        // 9: novitabox.v1.BalloonConfig
	(*BalloonStats)(nil),         // 10: novitabox.v1.BalloonStats
	(*BalloonHintingStatus)(nil), // 11: novitabox.v1.BalloonHintingStatus
	(*KernelSpec)(nil),           // 12: novitabox.v1.KernelSpec
	(*RootfsSpec)(nil),           // 13: novitabox.v1.RootfsSpec
	(*DriveSpec)(nil),            // 14: novitabox.v1.DriveSpec
	(*SnapshotSpec)(nil),         // 15: novitabox.v1.SnapshotSpec
	(*NetworkSpec)(nil),          // 16: novitabox.v1.NetworkSpec
	(*AgentSpec)(nil),            // 17: novitabox.v1.AgentSpec
	(*JailerSpec)(nil),           // 18: novitabox.v1.JailerSpec
	(*RuntimeSpec)(nil),          // 19: novitabox.v1.RuntimeSpec
	(*RuntimeInfo)(nil),          // 20: novitabox.v1.RuntimeInfo
	(*RuntimeCapabilities)(nil),  // 21: novitabox.v1.RuntimeCapabilities
	nil,                          // 22: novitabox.v1.SandboxInfo.LabelsEntry
	nil,                          // 23: novitabox.v1.SandboxInfo.AnnotationsEntry
	nil,                          // 24: novitabox.v1.SnapshotInfo.LabelsEntry
	nil,                          // 25: novitabox.v1.TemplateInfo.LabelsEntry
	nil,                          // 26: novitabox.v1.ImageInfo.LabelsEntry
	nil,                          // 27: novitabox.v1.RuntimeSpec.LabelsEntry
	nil,                          // 28: novitabox.v1.RuntimeSpec.AnnotationsEntry
}
var file_novitabox_v1_types_proto_depIdxs = []int32{
	0,  // 0: novitabox.v1.SandboxInfo.state:type_name -> novitabox.v1.SandboxState
	1,  // 1: novitabox.v1.SandboxInfo.runtime_type:type_name -> novitabox.v1.RuntimeType
	22, // 2: novitabox.v1.SandboxInfo.labels:type_name -> novitabox.v1.SandboxInfo.LabelsEntry
	23, // 3: novitabox.v1.SandboxInfo.annotations:type_name -> novitabox.v1.SandboxInfo.AnnotationsEntry
	24, // 4: novitabox.v1.SnapshotInfo.labels:type_name -> novitabox.v1.SnapshotInfo.LabelsEntry
	25, // 5: novitabox.v1.TemplateInfo.labels:type_name -> novitabox.v1.TemplateInfo.LabelsEntry
	26, // 6: novitabox.v1.ImageInfo.labels:type_name -> novitabox.v1.ImageInfo.LabelsEntry
	1,  // 7: novitabox.v1.RuntimeSpec.runtime_type:type_name -> novitabox.v1.RuntimeType
	7,  // 8: novitabox.v1.RuntimeSpec.machine:type_name -> novitabox.v1.MachineSpec
	12, // 9: novitabox.v1.RuntimeSpec.kernel:type_name -> novitabox.v1.KernelSpec
	13, // 10: novitabox.v1.RuntimeSpec.rootfs:type_name -> novitabox.v1.RootfsSpec
	15, // 11: novitabox.v1.RuntimeSpec.snapshot:type_name -> novitabox.v1.SnapshotSpec
	16, // 12: novitabox.v1.RuntimeSpec.network:type_name -> novitabox.v1.NetworkSpec
	17, // 13: novitabox.v1.RuntimeSpec.agent:type_name -> novitabox.v1.AgentSpec
	18, // 14: novitabox.v1.RuntimeSpec.jailer:type_name -> novitabox.v1.JailerSpec
	14, // 15: novitabox.v1.RuntimeSpec.extra_drives:type_name -> novitabox.v1.DriveSpec
	8,  // 16: novitabox.v1.RuntimeSpec.balloon:type_name -> novitabox.v1.BalloonSpec
	27, // 17: novitabox.v1.RuntimeSpec.labels:type_name -> novitabox.v1.RuntimeSpec.LabelsEntry
	28, // 18: novitabox.v1.RuntimeSpec.annotations:type_name -> novitabox.v1.RuntimeSpec.AnnotationsEntry
	1,  // 19: novitabox.v1.RuntimeInfo.runtime_type:type_name -> novitabox.v1.RuntimeType
	2,  // 20: novitabox.v1.RuntimeInfo.state:type_name -> novitabox.v1.RuntimeState
	21, // [21:21] is the sub-list for method output_type
	21, // [21:21] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_novitabox_v1_types_proto_init() }
func file_novitabox_v1_types_proto_init() {
	if File_novitabox_v1_types_proto != nil {
		return
	}
	file_novitabox_v1_types_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_novitabox_v1_types_proto_rawDesc), len(file_novitabox_v1_types_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_novitabox_v1_types_proto_goTypes,
		DependencyIndexes: file_novitabox_v1_types_proto_depIdxs,
		EnumInfos:         file_novitabox_v1_types_proto_enumTypes,
		MessageInfos:      file_novitabox_v1_types_proto_msgTypes,
	}.Build()
	File_novitabox_v1_types_proto = out.File
	file_novitabox_v1_types_proto_goTypes = nil
	file_novitabox_v1_types_proto_depIdxs = nil
}
